- REQUIRE
- docs/src/lib/representations.md
- src/LazySets.jl
- src/Polygon.jl
need to consider about the save to file feature that we used. how does it work with Plots? document it.
> add recipes for HPolygon

- src/CartesianProduct.jl
- src/ExponentialMap.jl
- src/LinearMap.jl
- src/MinkowskiSum.jl
- src/Polygon.jl
- src/Polyhedron.jl
> #17 - changed mutable structs to structs

- docs/make.jl
- docs/src/index.md
- src/Polyhedron.jl
- test/unit_Polyhedron.jl
> save dim field in polyhedron

- src/VPolygon.jl
- src/plot_recipes.jl
example:
```julia
using LazySets, Plots
n = 50
v = rand(n, 2)
vp = VPolygon([v[i, :] for i in 1:n])
plot([Singleton(v[i, :]) for i in 1:n], color="red")
plot!(vp, alpha=0.1)
plot!(singleton_list(vp), color="blue")
```
> convenience plot for singleton list

- src/LinearConstraints.jl
> #85 - output empty vector for parallel Line intersection

- src/convex_hull_algorithms.jl
- test/unit_Polygon.jl
> #59 - make sorting in CH algorithm optional

- src/Ball1.jl
> #84 - vertices_list for Ball1

- src/AbstractPointSymmetricPolytope.jl
> #97 - AbstractPointSymmetricPolytope <: AbstractPolytope

- docs/src/lib/approximations.md
- docs/src/man/iterative_refinement.md
> WIP - docs iterative refinement

- src/Approximations/2D_approximations.jl
- src/Approximations/Approximations.jl
- src/Approximations/decompositions.jl
> #106 - type parameter for overapproximate/decompose

- docs/src/lib/representations.md
- src/Ball2.jl
- test/unit_Ball2.jl
See #67. This one was a low-hanging fruit.
Should either be merged before solving #117 or must be modified.
> #67 - intersection of Ball2

- src/Approximations/decompositions.jl
> #141 - Fix Hyperrectangle decomposition

- .travis.yml
pull out duplicate `Pkg.add("Coverage")`
> Simplification .travis.yml

- docs/src/lib/operations.md
- src/Intersection.jl
- src/LazySets.jl
- test/runtests.jl
- test/unit_Intersection.jl
> #139 - Intersection of two sets

- docs/src/lib/operations.md
- src/AbstractHyperrectangle.jl
- src/LazySets.jl
- src/SymmetricIntervalHull.jl
- test/runtests.jl
- test/unit_SymmetricIntervalHull.jl
> #3 - lazy symmetric interval hull

- docs/make.jl
> #144 - set GR to 'no output'

- docs/src/lib/representations.md
- src/AbstractPointSymmetric.jl
- src/Ellipsoid.jl
- src/LazySets.jl
- test/runtests.jl
- test/unit_Ellipsoid.jl
> Implement lazy Ellipsoid

- docs/src/lib/representations.md
- src/HalfSpace.jl
- src/Hyperplane.jl
- src/LazySets.jl
- test/runtests.jl
- test/unit_HalfSpace.jl
- test/unit_Hyperplane.jl
Closes #149.
Closes #150.
The implementation idea is sketched [here](https://github.com/JuliaReach/LazySets.jl/issues/57#issuecomment-358692135).
> #149/#150 - HalfSpace/Hyperplane

- docs/src/lib/operations.md
- docs/src/man/convex_hulls.md
- docs/src/man/decompose_example.md
- src/ConvexHull.jl
- test/unit_ConvexHull.jl
> #103 - Implement convex hull for an array of sets

- docs/src/lib/operations.md
- docs/src/lib/representations.md
- src/HPolytope.jl
- src/Intersection.jl
- test/runtests.jl
- test/unit_Intersection.jl
- test/unit_Polytope.jl
> #77 - Containment checks Intersection/HPolytope

- src/Ball1.jl
> #170 - fix support vector for Ball1

- docs/src/lib/representations.md
- src/Zonotope.jl
- test/unit_Zonotope.jl
> Concrete operations for zonotopes

- src/ExponentialMap.jl
> ExponentialMap parametric N

- src/Approximations/2D_approximations.jl
- src/Approximations/Approximations.jl
- src/Approximations/box_approximations.jl
- src/Approximations/decompositions.jl
- src/Approximations/iterative_refinement.jl
> #182 - generalize numeric type of Approximations module

- docs/src/lib/representations.md
- docs/src/lib/utils.md
- src/AbstractPolygon.jl
- src/helper_functions.jl
- test/unit_Polygon.jl
> Alternative <= function

- src/Approximations/Approximations.jl
- test/unit_CartesianProduct.jl
- test/unit_Polygon.jl
- test/unit_ballinf_approximation.jl
- test/unit_decompose.jl
> #180 - numeric types in unit tests

- src/LinearMap.jl
- test/unit_LinearMap.jl
> #203 - fix scalar multiplication of a LinearMap

- src/ExponentialMap.jl
- test/unit_ExponentialMap.jl
> #206 - allow arbitrary vectors for ExponentialMap's σ

- docs/src/lib/binary_functions.md
- src/is_intersection_empty.jl
- test/unit_Zonotope.jl
> #208 - Check for empty intersection of zonotope with hyperplane

- src/Zonotope.jl
- src/is_intersection_empty.jl
> #212 - use ngens function

- src/LazySets.jl
> #210 - export Approximations module

- docs/src/man/concrete_polyhedra.md
- src/AbstractHPolygon.jl
- src/HPolygon.jl
- src/HPolygonOpt.jl
- src/HPolytope.jl
- test/unit_Polygon.jl
- test/unit_decompose.jl
- test/unit_overapproximation2D.jl
This point was discussed in #191
> change type field constraints_list -> constraints

- src/is_intersection_empty.jl
This fixes a warning when building the docs.
> add missing documentation

- docs/src/index.md
- docs/src/lib/operations.md
- src/LinearMap.jl
- test/unit_LinearMap.jl
Closes #221.
This is part of #161
> change field name in LinearMap

- docs/src/lib/operations.md
- src/CartesianProduct.jl
- src/ConvexHull.jl
- src/MinkowskiSum.jl
- test/unit_CartesianProduct.jl
- test/unit_ConvexHull.jl
- test/unit_MinkowskiSum.jl
- test/unit_decompose.jl
Remaining cases for #161.
Should be merged together with #224 because this will break `Reachability.jl`.
> #161 - rename array set types' field; add array getter

- docs/make.jl
- docs/src/index.md
- docs/src/man/reach_zonotopes_hybrid.md
> #201 - hybrid zonotope reach example

- docs/src/lib/approximations.md
- src/Approximations/Approximations.jl
- src/Approximations/overapproximate.jl
- test/runtests.jl
- test/unit_overapproximate.jl
> add overapproximate specialization

- src/Approximations/overapproximate.jl
> Overapproximate CH(Z1, Z2) assertion

- src/Intersection.jl
> #244 - use @absorbing macro for Intersection

- src/Approximations/iterative_refinement.jl
> #260 - AssertionError in Iterative refinement

- src/is_subset.jl
- test/unit_LineSegment.jl
> subset check for LineSegment

- src/CartesianProduct.jl
- src/ConvexHull.jl
- src/MinkowskiSum.jl
- src/helper_functions.jl
- test/unit_CartesianProduct.jl
- test/unit_ConvexHull.jl
- test/unit_MinkowskiSum.jl
Closes #250.
EDIT: We *do not* need to adapt `Reachability.jl` after merging.
> #250 - Inplace array n-ary constructors

- docs/src/lib/approximations.md
- src/Approximations/decompositions.jl
- test/unit_decompose.jl
> #136 - Generalize decomposition into general block structures

- src/Approximations/overapproximate.jl
> #242 - revise overapproximate

- src/Approximations/decompositions.jl
> #273 - Fix decompose for Hyperrectangle

- src/Approximations/decompositions.jl
- src/Approximations/overapproximate.jl
- test/unit_decompose.jl
- test/unit_overapproximate.jl
> Interval approximation/decomposition

- src/AbstractPointSymmetricPolytope.jl
- src/Interval.jl
- src/convert.jl
some fixes and proposal to modify the `Interval` types signature having `N<:Real`.
> Interval related doctest fixes

- docs/src/lib/representations.md
- src/Interval.jl
- add interval to docs
- fix some doctests
- add docstrings to usual arithmetic operations between intervals
> Add Interval to docs

- src/Approximations/overapproximate.jl
> #287 - generalize overapproximate(S, ::Hyperrectangle) to nD

- src/LinearMap.jl
> #292 - Remove zero matrix check from LinearMap

- src/AbstractHPolygon.jl
> #298 - Index problems with convex hull

- src/ExponentialMap.jl
> change output types in ExponentialMap

- src/ExponentialMap.jl
- test/unit_ExponentialMap.jl
> #308 - add method `eye` for `SparseMatrixExp`

- src/ExponentialMap.jl
> #311 - SparseMatrixExp subtype AbstractMatrix

- src/HPolygon.jl
- src/HPolytope.jl
> #319 - Wrong creation of empty polygon/polytope

- src/Line.jl
> #332 - Revisit Line

- src/Approximations/Approximations.jl
- src/Approximations/template_directions.jl
- test/unit_template_directions.jl
> #343 - Octagon template directions

- REQUIRE
- src/Ballp.jl
- src/ExponentialMap.jl
- src/LazySets.jl
- src/LinearMap.jl
- src/MinkowskiSum.jl
- src/Zonotope.jl
- src/concrete_intersection.jl
- src/helper_functions.jl
- src/is_intersection_empty.jl
- src/plot_recipes.jl
a branch for testing compatibility with julia 0.7
See #121.
> Julia 0.7 compat

- src/ExponentialMap.jl
- src/LazySets.jl
- src/LinearMap.jl
- src/Zonotope.jl
- src/compat.jl
> #205 - fix performance regression in LinearMap

- benchmark/benchmarks.jl
- benchmark/support_vector.jl
> #356 - add benchmarks file

- src/LazySets.jl
> remove duplicate include

- src/ExponentialMap.jl
> #360 - Skip copy of unmodified matrix

- src/MinkowskiSum.jl
- test/unit_MinkowskiSum.jl
> #367 - CacheMinkowskiSum's directions are modified

- docs/src/lib/interfaces.md
- docs/src/lib/representations.md
- src/AbstractHyperrectangle.jl
- src/AbstractPolytope.jl
- src/AbstractSingleton.jl
- src/ZeroSet.jl
- test/unit_Hyperrectangle.jl
- test/unit_Singleton.jl
- test/unit_ZeroSet.jl
> #371 -  Add concrete linear map for abstract hyperrectangles

- src/AbstractHyperrectangle.jl
- src/AbstractPolytope.jl
- src/AbstractSingleton.jl
- src/LinearMap.jl
- src/ZeroSet.jl
- src/Zonotope.jl
> #382 - Add assertions in concrete linear_map

- .travis.yml
> #389 - Change Travis build versions

- docs/src/lib/operations.md
- src/Intersection.jl
- test/unit_Intersection.jl
> #323 - Intersection Array

- src/VPolygon.jl
- src/VPolytope.jl
- test/unit_Polygon.jl
- test/unit_overapproximate.jl
> #385 `vertices` and `vertices_list`

- src/HalfSpace.jl
- src/LineSegment.jl
- test/unit_HalfSpace.jl
- test/unit_LineSegment.jl
> #406 Typo in halfspace_right

- test/unit_ConvexHull.jl
- test/unit_Hyperplane.jl
- test/unit_Intersection.jl
- test/unit_Interval.jl
- test/unit_LinearMap.jl
- test/unit_ZeroSet.jl
> #130 - Increase code coverage

- REQUIRE
> #412 - Add fixed versions for packages in REQUIRE

- src/HPolytope.jl
> #424 - Fix vertices_list of HPolytope and add doctest

- docs/src/lib/conversion.md
- docs/src/lib/representations.md
> #400 - Documenter error with `convert`

- src/LazySet.jl
> Fix doctest

- .travis.yml
We added two packages that are already in our REQUIRE list, so they are already installed.
> Clean-up .travis.yml

- docs/src/lib/operations.md
- src/Intersection.jl
See #427 for related discussion.
> Fix intersect

- src/Ellipsoid.jl
Motivation: Consistency with `Ball2`.
> Change numeric type of Ellipsoid

- src/Ellipsoid.jl
Motivation: search for "ellipse" in the docs hits this type.
> Ellipsoid's docstring mentions ellipse

- .travis.yml
> #402 - Use old version of Documenter for Travis build

- .travis.yml
> #402 - Use Pkg.pin to lock Documenter version

- src/SymmetricIntervalHull.jl
- test/unit_SymmetricIntervalHull.jl
> #420 - SymmetricIntervalHull's radius_hyperrectangle function is broken

- src/AbstractSingleton.jl
> #446 - Remove redundant an_element function in AbstractSingleton

- src/AbstractPolygon.jl
Motivation: Have the two methods `<=` below each other.
> Reorder functions

- src/Interval.jl
> #444 - More efficient an_element function for Interval

- src/AbstractPointSymmetricPolytope.jl
- src/LazySet.jl
- src/LineSegment.jl
- test/unit_LineSegment.jl
> #445 - Make LineSegment an AbstractPointSymmetricPolytope

- docs/src/lib/binary_functions.md
- src/Interval.jl
- src/is_subset.jl
- test/check_method_ambiguity_binary.jl
- test/unit_binary_operations.jl
> #456 - Rename is_subset to ⊆

- src/EmptySet.jl
- test/unit_EmptySet.jl
Closes #455.
Docs will come in #436 after a rebase.
> #455 - Override LazySet functions for EmptySet

- src/is_intersection_empty.jl
This removes some unreachable code.
> Remove dead code in is_intersection_empty for LineSegment

- docs/src/index.md
- docs/src/lib/operations.md
- src/LinearMap.jl
- test/unit_LinearMap.jl
> #451 - Revise type parameters of LinearMap

- docs/src/lib/utils.md
- src/AbstractHPolygon.jl
- src/HPolygon.jl
- src/HPolygonOpt.jl
- test/unit_Polygon.jl
Closes #111.
(wrong branch name)
> #111 - Binary search for HPolygon functions

- src/Approximations/box_approximations.jl
- src/compat.jl
- src/convex_hull_algorithms.jl
> Fix some julia 0.7 depwarns in tests

- src/Hyperplane.jl
> #121 - Replace findfirst by findnext

- test/runtests.jl
> #121 - include compat.jl in unit tests

- src/Ball1.jl
- src/compat.jl
> #121 - Replace indmax -> argmax

- src/AbstractPolygon.jl
> #121 - Replace atan2 by atan

- src/Approximations/overapproximate.jl
- src/Ball2.jl
- src/Hyperrectangle.jl
- src/MinkowskiSum.jl
These are just some simplifications.
> Simplifications: remove eltype, remove leading underscore

- test/check_method_ambiguity_binary.jl
- test/check_method_implementation.jl
- test/unit_ExponentialMap.jl
> #121 - Replace 'method_exists' -> 'hasmethod'

- src/Zonotope.jl
> #121 - Replace 'vecnorm' by 'norm'

- test/check_method_ambiguity_binary.jl
- test/unit_Ellipsoid.jl
- test/unit_LinearMap.jl
- test/unit_Zonotope.jl
- test/unit_template_directions.jl
> #121 - Replace 'eye(N, n)' -> 'Matrix{N}(I, n, n)'

- test/check_method_implementation.jl
> #121 - Add package InteractiveUtils for v0.7 (for 'subtypes' function)

- test/unit_ExponentialMap.jl
> #121 - Replace 'full' -> 'Matrix'

- test/unit_ExponentialMap.jl
> #121 - Replace 'assert' -> '@assert'

- src/compat.jl
- test/check_method_implementation.jl
> #121 - Change 8e6765e

- test/unit_ExponentialMap.jl
> #121 - Fix remaining deprecations in unit tests for ExponentialMap

- src/Ellipsoid.jl
- src/Zonotope.jl
- src/convert.jl
- test/unit_Ellipsoid.jl
- test/unit_Hyperrectangle.jl
> #121 - Replace 'diagm' -> 'Diagonal'

- .travis.yml
- REQUIRE
- test/check_method_implementation.jl
- test/runtests.jl
- test/unit_interfaces.jl
> #539 - Separate test suite for Polyhedra

- src/HPolytope.jl
This fixes a bug introduced in #543.
> Fix recently introduced bug in doctest

- src/HPolytope.jl
My fix in #548 was not complete :-1:
> Yet another doctest fix

- docs/make_doctests_only.jl
- docs/src/lib/approximations.md
- test/runtests.jl
> #71 - Strict doctests

- test/runtests.jl
- test/unit_Ball1.jl
> Fix unit tests for Ball1

- src/HPolygonOpt.jl
> #555 - HPolygonOpt stores wrong index in special case

- Project.toml
- src/AbstractHPolygon.jl
- src/AbstractHyperrectangle.jl
- src/AbstractPointSymmetric.jl
- src/AbstractPointSymmetricPolytope.jl
- src/AbstractPolygon.jl
- src/AbstractPolytope.jl
- src/AbstractSingleton.jl
- src/Approximations/decompositions.jl
- src/Approximations/overapproximate.jl
- src/Ball1.jl
- src/Ball2.jl
- src/BallInf.jl
- src/Ballp.jl
- src/ConvexHull.jl
- src/Ellipsoid.jl
- src/HPolytope.jl
- src/HalfSpace.jl
- src/Hyperplane.jl
- src/Hyperrectangle.jl
- src/Interval.jl
- src/LazySet.jl
- src/Line.jl
- src/LineSegment.jl
- src/VPolytope.jl
- src/Zonotope.jl
- src/concrete_intersection.jl
- src/convert.jl
- test/runtests.jl
> Make doctests work in v0.7

- test/runtests.jl
- test/unit_Polytope.jl
- test/unit_interfaces.jl
> #130 - Add unit tests for Polyhedra functions

- src/Approximations/iterative_refinement.jl
> #567 - Error tolerance should be compared using <= instead of <

- src/AbstractHyperrectangle.jl
> #54 - Improved norm for hyperrectangular sets

- docs/src/about.md
https://github.com/JuliaReach/LazySets.jl/pull/604#issuecomment-418333365
Why not? 😁
> Add "Tomer Arnon" to "Credits"

- src/Zonotope.jl
* "line elements" → "line segments"
* some line breaks
> improve docs for Zonotope.jl

- src/HPolytope.jl
- src/VPolytope.jl
- src/concrete_intersection.jl
- src/init.jl
> #630 - Concrete intersection between HPolytope and VPolytope

- docs/src/lib/utils.md
- src/helper_functions.jl
- test/runtests.jl
- test/unit_Ball1.jl
- test/unit_BallInf.jl
- test/unit_Hyperrectangle.jl
- test/unit_LineSegment.jl
- test/unit_Polytope.jl
> #617 - Add function to check for vector permutation

- src/concrete_intersection.jl
- test/unit_Polytope.jl
> #645 - Concrete intersection for polytopic sets

- .travis.yml
- Project_tmp
- REQUIRE
- test/runtests.jl
> #647 - Remove Plots from REQUIRE

- docs/src/lib/binary_functions.md
- src/is_intersection_empty.jl
- test/unit_HalfSpace.jl
> #658 - Check for intersection of a compact set and a HalfSpace

- src/Zonotope.jl
> #669 - Remove convex_hull! in vertices list of Zonotope and improve docstring

- docs/src/lib/operations.md
- src/CartesianProduct.jl
- src/ExponentialMap.jl
- src/LinearMap.jl
- test/unit_CartesianProduct.jl
- test/unit_ExponentialMap.jl
- test/unit_LinearMap.jl
> #667 - vertices_list function for lazy operations

- src/Approximations/overapproximate.jl
- src/Intersection.jl
> #686 - Overapproximate lazy intersection with template directions

- src/HPolytope.jl
> #710 - Add boundedness check for support vector of polytope

- docs/src/lib/binary_functions.md
- src/is_intersection_empty.jl
- test/unit_Polygon.jl
> #712 - Add intersection of set and polytope

- src/ConvexHull.jl
- src/ExponentialMap.jl
- src/MinkowskiSum.jl
> #715 - Add some ρ's

- src/Approximations/upper_bounds.jl
- src/Intersection.jl
- src/is_intersection_empty.jl
> #722 - Add upper bound option to intersection

- docs/src/lib/representations.md
- src/LineSegment.jl
- test/unit_LineSegment.jl
> #727 - Constraints list of line segment

- src/Approximations/box_approximations.jl
- src/Approximations/overapproximate.jl
> #739 - Add upper_bound argument to overapproximate methods

- src/Approximations/upper_bounds.jl
- src/LinearMap.jl
> #742 - Add kwargs to LinearMap's support function

- src/HalfSpace.jl
- src/Hyperplane.jl
- test/unit_HalfSpace.jl
> #746 - Wrong support vector of HalfSpace in opposite direction of normal vector

- docs/src/lib/representations.md
- src/AbstractHyperrectangle.jl
- src/HalfSpace.jl
- test/unit_HalfSpace.jl
> #762 - Add constraints_list for HalfSpace

- docs/src/lib/binary_functions.md
- src/concrete_intersection.jl
- test/unit_Polytope.jl
> #764 - Add concrete intersection of HalfSpace and HPolytope

- src/concrete_intersection.jl
> #770 - Intersection of polyhedron and polytope should be a polytope

- src/Approximations/overapproximate.jl
> #790 Overapproximate intersection of compact set with HPolyhedron

- src/is_intersection_empty.jl
> #788 - Intersection emptiness check for compact set with HPolyhedron

- src/Intersection.jl
> #805 - Fix dispatch of lazy intersection of HPolyhedron and polytope

- src/Line.jl
- test/unit_Line.jl
> #807 - Constructor of Line from 2 points

- src/Intersection.jl
> #813 - Intersection's cache is not used in ρ

- src/Approximations/overapproximate.jl
> Add disambiguations/symmetric methods for overapproximate

- src/AbstractPolytope.jl
- src/HPolyhedron.jl
- src/HPolytope.jl
- src/VPolytope.jl
> #690 - Fix T parameter and remove deprecated imports

- src/HPolyhedron.jl
> cleanup in HPolyhedron eval

- src/ExponentialMap.jl
- test/unit_ExponentialMap.jl
> #828 - Remove eye(::SparseMatrixExp)

- test/unit_Polytope.jl
> #834 - Exclude unit test for v1.0

- test/runtests.jl
> #833 - Fix polyhedra doctests in 0.7

- docs/src/man/reach_zonotopes.md
- docs/src/man/reach_zonotopes_hybrid.md
- src/compat.jl
> #832 - Remove eye from docs

- .travis.yml
>  #620 - Pin GR version to prevent small plots

- .travis.yml
> Use correct command to pin GR

- src/plot_recipes.jl
- test/unit_plot.jl
See https://github.com/JuliaReach/LazySets.jl/issues/820.
> Add dimension assertions for plots

- src/HPolyhedron.jl
- src/HPolytope.jl
- test/unit_Polyhedron.jl
> #820 - Vertices list of polyhedron

- src/is_intersection_empty.jl
> #855 - Method ambiguities

- src/compat.jl
- test/check_method_ambiguity_binary.jl
- test/unit_binary_operations.jl
> #852 - Add method ambiguity checks for binary functions

- .travis.yml
- test/runtests.jl
Closes #440.
The crash seems to be fixed.
However, I had to cap the version again (see #866).
> Update Documenter version

- docs/make.jl
> Deploy docs from v0.7 build

- docs/src/lib/binary_functions.md
- src/Hyperplane.jl
- src/is_intersection_empty.jl
- test/unit_Zonotope.jl
> #208 - Witness production for empty intersection check of zonotope with hyperplane

- src/Approximations/iterative_refinement.jl
> #115 - Avoid array insertion in iterative refinement

- docs/src/lib/approximations.md
- docs/src/man/iterative_refinement.md
- src/Approximations/iterative_refinement.jl
Closes #879.
I had to remove the second to last section about the error because this is not available anymore.
> #879 - Adapt iterative refinement section to recent changes

- src/convex_hull_algorithms.jl
- test/unit_ConvexHull.jl
> #876 - Convex hull does not sort two vertex input

- src/AbstractHPolygon.jl
- src/Approximations/decompositions.jl
- src/Approximations/iterative_refinement.jl
- src/Approximations/overapproximate.jl
- src/HPolygon.jl
- src/HPolygonOpt.jl
- src/concrete_intersection.jl
> sort constraints of hpolygon on construction

- docs/src/lib/representations.md
- src/HPolyhedron.jl
- src/HPolytope.jl
- test/unit_Polyhedron.jl
- test/unit_Polytope.jl
https://www.cs.mcgill.ca/~fukuda/soft/polyfaq/node24.html
> Remove redundancies of HPoly using an LP

- src/AbstractPolytope.jl
- src/HPolyhedron.jl
- src/HPolytope.jl
- src/Intersection.jl
> use MODULE instead of Main in isdefined

- src/plot_recipes.jl
See https://github.com/JuliaReach/LazySets.jl/issues/237.
> Add assertion in singleton plot

- src/HPolyhedron.jl
> Use backend in remove_redundant_constraints

- docs/src/man/concrete_polyhedra.md
- docs/src/man/convex_hulls.md
- docs/src/man/interval_hulls.md
- docs/src/man/iterative_refinement.md
- docs/src/man/reach_zonotopes.md
- docs/src/man/reach_zonotopes_hybrid.md
- src/plot_recipes.jl
> swap using in some places

- src/convex_hull_algorithms.jl
> #942 - Add assertions in convex hull

- src/Singleton.jl
- src/concrete_intersection.jl
- test/unit_Singleton.jl
> #968 - Allow abstract vector in singleton

- docs/make_doctests_only.jl
> #906 - Add optional packages to make_doctests_only.jl

- src/macros.jl
> #990 - declare_array_version docstring

- src/HPolytope.jl
- test/unit_Polytope.jl
> #995 - Error in vertices_list of HPolytope with no constraints

- docs/src/lib/interfaces.md
- docs/src/lib/representations.md
- src/HPolyhedron.jl
- src/LazySet.jl
- test/unit_Polytope.jl
- test/unit_interfaces.jl
Closes #904.
Related to this PR:
- https://discourse.julialang.org/t/what-is-the-difference-between-copy-and-deepcopy/3918/2
- https://stackoverflow.com/questions/51956958/how-to-copy-a-struct-in-julia
> #904 - Override copy for LazySets

- test/unit_comparisons.jl
> #1023 - remove new variables

- test/unit_Polytope.jl
> Move test code inside loop & use N

- docs/src/lib/representations.md
- docs/src/man/set_operations.md
- src/VPolytope.jl
- test/unit_Polytope.jl
> #599 - Set membership for VPolytope

- docs/src/lib/representations.md
- docs/src/lib/utils.md
- docs/src/man/set_operations.md
- src/HPolyhedron.jl
- src/LinearMap.jl
- src/compat.jl
- src/helper_functions.jl
- test/unit_LinearMap.jl
- test/unit_Polyhedron.jl
- test/unit_Polytope.jl
- test/unit_util.jl
> #962 #769 - Invertible linear map

- docs/src/lib/representations.md
- src/Hyperplane.jl
- src/Line.jl
- test/unit_Hyperplane.jl
- test/unit_Line.jl
> #1045 - Constraints list of Hyperplane and Line

- src/concrete_intersection.jl
> fix intersection

- docs/src/lib/representations.md
- src/EmptySet.jl
- test/unit_EmptySet.jl
> #1061 - Add linear map of empty set

- docs/src/lib/operations.md
- src/Intersection.jl
- test/unit_Intersection.jl
> #1060 - Concrete linear map of an intersection

- docs/src/lib/operations.md
- src/concrete_intersection.jl
- test/unit_LinearMap.jl
> #1063 - Add intersection of linearmap

- src/VPolygon.jl
- test/unit_Polygon.jl
> #1070 - Wrong handling of type parameter in tohrep of VPolygon

- src/concrete_intersection.jl
> Missing part of #1069

- src/Intersection.jl
> #1074 - Intersection with bounded set computes an unbounded support value

- .travis.yml
- docs/make.jl
- docs/src/index.md
- docs/src/man/lazy_intersections.md
Closes #1088.
~~disclaimer: i didn't make these new docs in my machine yet.~~ looks good now.
> #1088 - Add lazy intersections page

- docs/src/lib/representations.md
- src/HPolygon.jl
- src/HPolygonOpt.jl
- src/HPolyhedron.jl
- src/HPolytope.jl
- src/HalfSpace.jl
- test/unit_HalfSpace.jl
- test/unit_Polygon.jl
> #1101 - Add constraints_list method from matrix and vector

- src/Intersection.jl
> #1106 - Fix ambiguity in intersection of halfspaces

- docs/src/lib/binary_functions.md
- src/concrete_intersection.jl
- test/unit_ResetMap.jl
> #1123 - Concrete intersection between half-space and polytopic reset map

- src/AbstractHyperrectangle.jl
> Add assertion

- src/Zonotope.jl
- test/unit_Zonotope.jl
> #1130 - Add constraints list of zonotope test

- src/convert.jl
> #932 - Use constraints list in HPolytope conversion

- docs/src/lib/conversion.md
- src/Approximations/overapproximate.jl
- src/convert.jl
- test/unit_Interval.jl
> #1140 - Add conversion to interval methods

- docs/src/lib/utils.md
- src/helper_functions.jl
- test/unit_util.jl
> #1163 - Check for square matrix in isinvertible

- docs/src/lib/conversion.md
- src/Approximations/overapproximate.jl
- src/convert.jl
- test/unit_CartesianProduct.jl
> #1143 - Faster overapproximation of CartesianProductArray of hyperrectangular sets

- docs/src/lib/operations.md
- src/concrete_convex_hull.jl
- test/unit_convex_hull.jl
> Refactor convex hull for higher dimensional point sets

- src/Approximations/overapproximate.jl
> #1178 - Use support function for box approximation with HPolygon

- src/AbstractPolyhedron_functions.jl
- src/HPolytope.jl
- test/unit_Polytope.jl
This covers a particular case from https://github.com/JuliaReach/LazySets.jl/issues/965.
> Use promotion for linear map of polyhedra

- docs/src/lib/operations.md
- src/LazySet.jl
- src/LazySets.jl
- src/Translation.jl
- src/helper_functions.jl
- test/unit_Translation.jl
> #882 - Add lazy Translation

- docs/src/lib/approximations.md
- src/Approximations/decompositions.jl
- test/unit_decompose.jl
> #1177 - Revise decompose interface

- docs/src/man/polyhedral_approximations.md
> Update Polyhedral Approximations docs

- src/HPolyhedron.jl
> #1194 - HPolyhedron.isempty requires Polyhedra

- src/Approximations/overapproximate.jl
- test/unit_overapproximate.jl
- test/unit_template_directions.jl
> #1196 - Add overapproximate with raw template-directions type

- src/helper_functions.jl
- test/unit_HalfSpace.jl
> #1211 - constrained dimensions of halfspace with sparse normal vector

- docs/make.jl
- docs/make_doctests_only.jl
- src/AbstractPolygon.jl
- src/AbstractPolytope.jl
- src/Approximations/Approximations.jl
- src/HalfSpace.jl
- src/Intersection.jl
- src/Interval.jl
- src/LazySet.jl
- src/LazySets.jl
- src/compat.jl
- src/convert.jl
- src/helper_functions.jl
- src/plot_recipes.jl
- test/runtests.jl
- test/unit_Hyperrectangle.jl
- test/unit_Intersection.jl
- test/unit_Interval.jl
- test/unit_LinearMap.jl
- test/unit_Polyhedron.jl
- test/unit_Singleton.jl
- test/unit_ballinf_approximation.jl
- test/unit_box_approximation.jl
- test/unit_comparisons.jl
- test/unit_convex_hull.jl
- test/unit_decompose.jl
- test/unit_overapproximate.jl
- test/unit_plot.jl
- test/unit_template_directions.jl
> #1095 -  Revise usage of `using` vs. `import`

- docs/src/lib/interfaces.md
- docs/src/lib/operations.md
- src/AbstractHyperrectangle.jl
- src/AbstractSingleton.jl
- src/BallInf.jl
- src/Hyperrectangle.jl
- src/ResetMap.jl
- src/SymmetricIntervalHull.jl
- test/unit_Hyperrectangle.jl
- test/unit_ResetMap.jl
- test/unit_Singleton.jl
> #1119 - constraints_list for ResetMap of hyperrectangle

- docs/src/lib/conversion.md
- src/convert.jl
- test/unit_Zonotope.jl
> #1231 - Convert lazy linear map of hyperrectangular set to zonotope

- src/Zonotope.jl
> #1240 - constraints_list for Zonotopes of order < 1

- docs/src/lib/representations.md
- src/plot_recipes.jl
- test/unit_plot.jl
> #577 - Add a plot recipe for EmptySet

- src/Approximations/overapproximate.jl
- test/unit_template_directions.jl
> #1256 - overapproximate of lazy Intersection with template directions is ambiguous

- docs/src/lib/interfaces.md
- src/AbstractHyperrectangle.jl
- src/Approximations/template_directions.jl
- src/compat.jl
- test/unit_BallInf.jl
- test/unit_Hyperrectangle.jl
> #1263 - Partition of hyperrectangular set into smaller blocks

- src/Ellipsoid.jl
- src/Zonotope.jl
Closes #1265.
Unfortunately, I pushed the changes directly to `master` ([here](https://github.com/JuliaReach/LazySets.jl/commit/baae3ee9fae1bc7cb7254e5be618373567369fa1) and [here](https://github.com/JuliaReach/LazySets.jl/commit/2a171c701bb52a145dce80d771ab0bb21c0b3427)).
So this PR just brings the required changes.
> #1265 - Support function for Zonotope and Ellipsoid

- src/plot_recipes.jl
> #1268 - Catch empty polygons in plots

- src/AbstractSingleton.jl
- src/is_subset.jl
- test/unit_Singleton.jl
> Better error msg for inclusion and membership

- src/Translation.jl
- test/unit_Translation.jl
> #1301 - Apply translation from the left

- .travis.yml
- Project.toml
- REQUIRE
> Add Project.toml file and remove REQUIRE

- .travis.yml
- docs/make_doctests_only.jl
> Update .travis.yml (build docs; drop artifacts)

- docs/src/lib/binary_functions.md
- src/is_intersection_empty.jl
- test/unit_Interval.jl
> #1315 - Faster disjointess check for intervals

- docs/src/lib/conversion.md
- src/convert.jl
- test/unit_CartesianProduct.jl
> Conversions to CP and CPA

- src/AbstractHPolygon.jl
- src/HPolygon.jl
- src/HPolygonOpt.jl
- src/convert.jl
- src/plot_recipes.jl
> Choose to prune=true by default

- src/plot_recipes.jl
Closes #1300.
Closes #703.
Requires #1272.
> #1300 - Set plot defaults properly

- docs/src/lib/operations.md
- src/Translation.jl
- test/unit_Translation.jl
> #1358 - Add in for lazy translation

- src/Approximations/template_directions.jl
- test/unit_template_directions.jl
> #1359 - Diagonal times unit vector

- docs/src/lib/utils.md
- src/helper_functions.jl
- test/unit_util.jl
> Add 'rectify' helper function

- src/VPolytope.jl
- test/unit_Polytope.jl
Related to https://github.com/JuliaReach/LazySets.jl/issues/947.
> Empty VPolytope to polyhedron conversion

- docs/src/man/iterative_refinement.md
> 1356 - Hide legend in local approximation plot in manual

- src/VPolygon.jl
> #927 - Make VPolygon's vertices field be abstract 

- docs/src/lib/conversion.md
- docs/src/lib/operations.md
- docs/src/man/set_operations.md
- src/LazySets.jl
- src/Rectification.jl
- src/convert.jl
- test/runtests.jl
- test/unit_Rectification.jl
> #1176 - Lazy ReLU operation

- docs/src/man/concrete_polyhedra.md
> #560 - Clarify numeric-type discussion related to Polyhedra

- src/ExponentialMap.jl
- src/helper_functions.jl
> #310 - Generalize sparse matrix type

- .travis.yml
- docs/make.jl
> #1326 - Travis terminates building the docs

- src/AbstractHPolygon.jl
- src/HPolygon.jl
- src/HPolygonOpt.jl
> #476 - Better document AbstractHPolygon

- docs/src/lib/interfaces.md
- src/LazySet.jl
> #378 - Add isapprox between sets

- src/Approximations/overapproximate.jl
> Simplifications in overapproximate

- src/LinearMap.jl
- test/unit_LinearMap.jl
> #1355 - Remove redundant vertices of LinearMap

- src/HPolytope.jl
The `*` was missing, so the message was just
```
ERROR: AssertionError: the function `vertices_list`
```
> Fix error message

- docs/src/lib/operations.md
- src/Translation.jl
- test/unit_Translation.jl
> #1364 - Concrete linear map of a translation

- docs/src/lib/utils.md
- src/AbstractPolyhedron_functions.jl
- src/AbstractPolytope.jl
- src/HPolyhedron.jl
- src/HPolytope.jl
- src/Intersection.jl
- src/VPolytope.jl
- src/init.jl
Closes #1109.
Example:
```julia
julia> B = rand(BallInf);
julia> V = rand(VPolygon);
julia> ρ([1., 0.], B ∩ V);
ERROR: AssertionError: package 'Optim' not loaded (it is required for executing `ρ` (algorithm line_search))
```
> Outsource package-requirement messages to a central place

- docs/make.jl
See the discussion started [here](https://github.com/JuliaReach/LazySets.jl/issues/1326#issuecomment-502728213).
> Activate 'strict' option in Documenter

- test/unit_Polytope.jl
> #635 - Unit tests for concrete intersection of polytopes

- src/AbstractPolyhedron.jl
- src/AbstractPolytope.jl
> #638 - Revise AbstractPolytope interface documentation

- src/Zonotope.jl
- test/unit_Zonotope.jl
- test/unit_overapproximate.jl
> #1450 - Wrong constraints_list of zonotope with non-full-rank generator matrix

- Project.toml
- test/runtests.jl
- test/unit_Polytope.jl
> #1480 - Add CDDLib to tests

- src/Approximations/overapproximate.jl
- test/unit_overapproximate.jl
See [this comment](https://github.com/JuliaReach/Reachability.jl/pull/641#discussion_r299186663).
> Let identity version of overapproximate accept kwargs

- src/Arrays/matrix_operations.jl
- test/unit_util.jl
> #1497 - Define rank for sparse Submatrix

- docs/src/lib/binary_functions.md
- docs/src/lib/interfaces.md
- docs/src/lib/operations.md
- docs/src/lib/representations.md
- src/HPolyhedron.jl
- src/VPolytope.jl
> #1486 - Move docs of binary functions to binary_functions.md

- src/HalfSpace.jl
- src/Hyperplane.jl
- src/Line.jl
- test/unit_HalfSpace.jl
- test/unit_Hyperplane.jl
- test/unit_Line.jl
> #422 - Require non-zero normal directions in Line/Hyperplane/HalfSpace

- src/Arrays/SingleEntryVector.jl
- src/Translation.jl
- test/unit_util.jl
> #1216 - Negation of SingleEntryVector

- test/unit_Polygon.jl
- test/unit_Polyhedron.jl
- test/unit_Polytope.jl
> #786 - Revise tests of polyhedra

- docs/src/lib/interfaces.md
- docs/src/lib/representations.md
- src/AbstractHyperrectangle.jl
- src/BallInf.jl
- src/Interval.jl
- test/unit_BallInf.jl
- test/unit_Hyperrectangle.jl
> #1346 - Add isflat for AbstractHyperrectangle

- test/unit_Polyhedron.jl
Follow-up of https://github.com/JuliaReach/LazySets.jl/pull/1518#pullrequestreview-267477201.
> Add comparisons to polyhedra intersection tests

- docs/src/lib/operations.md
- src/CartesianProduct.jl
- src/ConvexHull.jl
- src/Intersection.jl
- src/MinkowskiSum.jl
- src/UnionSet.jl
- test/unit_CartesianProduct.jl
- test/unit_ConvexHull.jl
- test/unit_Intersection.jl
- test/unit_MinkowskiSum.jl
- test/unit_UnionSet.jl
> #817 - Add swap methods to binary lazy operations

- src/ResetMap.jl
- test/unit_ResetMap.jl
> #1124 - Use Diagonal for ResetMap.get_A

- src/Ball1.jl
- src/Ball2.jl
- src/Ballp.jl
- src/CartesianProduct.jl
- src/EmptySet.jl
- src/ExponentialMap.jl
- src/LineSegment.jl
- src/LinearMap.jl
- src/Translation.jl
- src/Universe.jl
- src/VPolygon.jl
- src/ZeroSet.jl
- src/Zonotope.jl
- src/is_subset.jl
- test/unit_Ball2.jl
- test/unit_BallInf.jl
- test/unit_CartesianProduct.jl
- test/unit_Complement.jl
- test/unit_EmptySet.jl
- test/unit_Hyperrectangle.jl
- test/unit_Intersection.jl
- test/unit_Interval.jl
- test/unit_LineSegment.jl
- test/unit_Polygon.jl
- test/unit_Polyhedron.jl
- test/unit_Singleton.jl
- test/unit_UnionSet.jl
- test/unit_Universe.jl
- test/unit_ZeroSet.jl
> #1033 - Use infix / negated unicode characters

- src/SymmetricIntervalHull.jl
- test/unit_SymmetricIntervalHull.jl
> #1116 - SymmetricIntervalHull of unbounded set

- src/Hyperrectangle.jl
- test/unit_Hyperrectangle.jl
> #811 - Check low .< high in hyperrectangle constructor

- docs/src/lib/operations.md
- src/ExponentialMap.jl
- src/LinearMap.jl
- test/unit_ExponentialMap.jl
- test/unit_LinearMap.jl
> #1006 - Define absorbing elements for map types

- src/UnionSet.jl
- test/unit_UnionSet.jl
> #1005 - Declare neutral element of UnionSet

- src/HPolyhedron.jl
- src/HPolytope.jl
> #1539 - Ignore constraints with zero normal vector

- docs/src/lib/binary_functions.md
- docs/src/lib/interfaces.md
- src/AbstractPolytope.jl
- src/HPolytope.jl
- src/LazySets.jl
- src/VPolytope.jl
- src/concrete_minkowski_sum.jl
- src/init.jl
- src/init_CDDLib.jl
Closes #1496.
~~Requires: #1539.~~
---
For an illustration see https://nbviewer.jupyter.org/github/mforets/escritoire/blob/master/sets/HigherDimRefinement.ipynb.
> #1496 - Concrete m-sum in Hrep

- docs/src/lib/operations.md
- src/AffineMap.jl
- src/LazySet.jl
- src/LazySets.jl
- test/runtests.jl
- test/unit_AffineMap.jl
Closes #1111.
~Requires: https://github.com/JuliaReach/LazySets.jl/issues/1364~
> #1111 - Add AffineMap

- docs/src/lib/binary_functions.md
- src/is_intersection_empty.jl
- test/unit_CartesianProduct.jl
Closes #641.
~Requires #1457 for the tests to pass.~
> #641 - Check for intersection of CartesianProductArray and high-dimensional Cartesian set

- src/AbstractPolyhedron_functions.jl
- test/unit_Polyhedron.jl
> #909 - Fix repeated-constraint removal of HPolyhedron

- src/Approximations/Approximations.jl
- src/Approximations/iterative_refinement.jl
> #1548 - Use _rtol in Approximations

- docs/src/lib/operations.md
- src/Rectification.jl
- test/unit_Rectification.jl
> #1176 - Support function for Rectification

- docs/src/lib/interfaces.md
- src/AbstractHyperrectangle.jl
- src/convert.jl
- test/unit_Hyperrectangle.jl
> #1547 - Add concrete rectification for hyperrectangular set

- src/Zonotope.jl
- test/unit_Zonotope.jl
> #1021 - Remove redundancies in zonotope's vertices list

- docs/src/lib/binary_functions.md
- src/is_subset.jl
- test/unit_Ball2.jl
> #1537 - Inclusion check of LazySet in polyhedral LazySet

- docs/src/lib/binary_functions.md
- src/concrete_minkowski_sum.jl
- test/unit_Hyperrectangle.jl
> #1564 - Concrete minkowski sum for AbstractHyperrectangle

- docs/src/lib/operations.md
- src/MinkowskiSum.jl
- test/unit_MinkowskiSum.jl
Closes #1563.
~Requires:  #1568~
> #1563 - Constraints list of a polyhedral MinkowskiSum

- src/AbstractHyperrectangle.jl
- test/unit_Hyperrectangle.jl
> #1576 - Robust set membership for AbstractHyperrectangle

- .travis.yml
- codecov.yml
> Fix Codecov command

- docs/src/lib/approximations.md
- src/Approximations/Approximations.jl
- src/Approximations/underapproximate.jl
- test/runtests.jl
- test/unit_underapproximate.jl
> #601 - Add underapproximate function

- src/init_CDDLib.jl
- test/runtests.jl
- test/unit_CDDLib.jl
> #1594 - CDDLib with :exact numbers

- src/concrete_minkowski_sum.jl
- test/unit_BallInf.jl
> #1592 - Undefined function in Minkowski sum of general lazysets

- src/VPolygon.jl
> Minkowski sum of VPolygon with small number of vertices

- docs/src/lib/operations.md
- src/AffineMap.jl
- src/Translation.jl
- test/runtests.jl
- test/unit_Translation.jl
> #1546 - Make Translation of LinearMap an AffineMap

- src/Approximations/overapproximate.jl
- test/unit_Zonotope.jl
- test/unit_overapproximate.jl
Closes #1374.
~Apparently either the implementation or the method is not correct (our unit test discovers this).~
> #1374 - Zonotope overapproximation of convex hull of zonotopes

- docs/src/lib/binary_functions.md
- src/concrete_intersection.jl
- test/unit_CartesianProduct.jl
> #1607 - Concrete intersection between CartesianProductArray and AbstractPolyhedron

- docs/src/lib/binary_functions.md
- src/concrete_convex_hull.jl
- test/unit_convex_hull.jl
> #1636 - Concrete convex hull of polytopes

- docs/src/lib/utils.md
- src/helper_functions.jl
> #1603 - List of LazySet types that implement a set-operation

- src/VPolytope.jl
See [here](https://juliareach.github.io/LazySets.jl/latest/lib/representations/#Base.:%E2%88%88-Union{Tuple{N},%20Tuple{AbstractArray{N,1},VPolytope{N}}}%20where%20N%3C:Real).
> Fix math formula in docs

- docs/src/lib/operations.md
- src/CartesianProduct.jl
- test/unit_CartesianProduct.jl
> #1609 - linear_map for polyhedral CartesianProductArray

- test/unit_Polygon.jl
- test/unit_Polytope.jl
These tests are the only new thing of #1617, so I moved them here for clarity.
> Unit tests

- docs/src/lib/utils.md
- src/Utils/samples.jl
- test/unit_samples.jl
> #1669 Rejection sampling follow-up

- docs/src/lib/utils.md
- src/ConcreteOperations/convex_hull.jl
- src/Utils/comparisons.jl
- test/unit_convex_hull.jl
> #1661 - Convex hull in 2D removes non-redundant vertices

- src/Approximations/overapproximate.jl
> #1680 - Generalize overapproximation methods for Zonotopes to AbstractZonotopes

- docs/src/lib/interfaces.md
- src/Interfaces/LazySet.jl
- test/unit_BallInf.jl
> #1621 - Concrete affine map

- src/Sets/EmptySet.jl
- test/unit_plot.jl
> #1705 - Plotting of empty polyhedron crashes

- .travis.yml
- Project.toml
> Run Julia v1.3 (RC) on Travis

- src/ConcreteOperations/convex_hull.jl
- test/unit_convex_hull.jl
> #1399 - Convex hull does not eliminate all redundant vertices

- src/Approximations/decompositions.jl
- src/LazyOperations/CartesianProduct.jl
- src/LazyOperations/Intersection.jl
- src/Sets/Hyperrectangle.jl
- src/convert.jl
- test/unit_Hyperrectangle.jl
> #1214 - Allow abstract vector in hyperrectangle fields

- benchmark/README.md
> Update benchmarks README

- docs/src/lib/interfaces.md
- docs/src/lib/representations.md
- src/Interfaces/AbstractHPolygon.jl
- test/unit_Polygon.jl
- test/unit_Polytope.jl
> #1405 - Apply convex hull in vertices_list of HPolygon

- src/Approximations/box_approximations.jl
- src/Approximations/overapproximate.jl
- test/unit_box_approximation.jl
- test/unit_overapproximate.jl
Closes #1556.
~Requires #1214.~
> #1556 - Make box_approximation an alias

- src/Approximations/overapproximate.jl
- test/unit_box_approximation.jl
This is a fix for a bug introduced in #1716.
> Add missing type parameter

- src/LazyOperations/Intersection.jl
> #1747 - Revise support function for Intersection with polyhedron

- src/LazyOperations/ExponentialMap.jl
- test/unit_ExponentialMap.jl
> #317 - Handling of non-square SparseMatrixExp

- src/Interfaces/AbstractPolyhedron_functions.jl
- test/unit_Polyhedron.jl
> #1751 - constrained_dimensions of an empty polyhedron

- src/Sets/Hyperrectangle.jl
> #1759 - Update Hyperrectangle docstring

- docs/src/lib/conversion.md
- src/convert.jl
> #1760 - Convert IntervalArithmetic.Interval to LazySets.Interval

- README.md
See the breaking change [here](https://github.com/JuliaDocs/Documenter.jl/blob/master/CHANGELOG.md#version-v0240).
> Update to new Documenter change

- docs/src/lib/interfaces.md
- docs/src/lib/representations.md
- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Sets/Ball2.jl
- test/unit_Ball2.jl
- test/unit_Polytope.jl
> #1110 - Add Chebyshev center

- src/Interfaces/AbstractZonotope.jl
> #1772 - NaNs in constraints list of Zonotope

- docs/src/lib/utils.md
- src/Arrays/matrix_operations.jl
- src/Interfaces/AbstractPolyhedron_functions.jl
> #1776 - Fix workflow of linear_map for polyhedra

- src/Interfaces/LazySet.jl
Closes #1115.
Most items in that issue have already been resolved, so it only remained to add some documentation :+1:
> #1115 - Add better documentation for ρ to LazySet

- docs/src/lib/operations.md
- src/LazyOperations/MinkowskiSum.jl
- test/unit_MinkowskiSum.jl
> #1793 - Add membership for msum of singleton and set

- src/ConcreteOperations/issubset.jl
> #1792 - Add algorithm option and set constraints to the default

- src/ConcreteOperations/issubset.jl
- test/unit_Polytope.jl
> #1809 - Inconsistent inclusion check

- docs/src/lib/conversion.md
- docs/src/lib/operations.md
- src/LazyOperations/ConvexHull.jl
- src/convert.jl
- test/unit_ConvexHull.jl
> #1814 - Convert lazy convex hull of singletons to VPolytope

- docs/src/lib/interfaces.md
- src/Interfaces/LazySet.jl
- test/unit_Polytope.jl
- test/unit_util.jl
> #1586  Equivalence check for sets

- src/Interfaces/AbstractHyperrectangle.jl
- src/LazyOperations/SymmetricIntervalHull.jl
- src/Sets/BallInf.jl
- src/Sets/Hyperrectangle.jl
> #1722 - Faster hyperrectangle support function for SingleEntryVector

- docs/src/lib/representations.md
- src/Sets/Ball2.jl
- test/unit_Ball2.jl
> #1828 - Add volume function for Ball2

- src/Utils/comparisons.jl
- test/unit_util.jl
> #1337 - Handle inexact vectors in ispermutation

- src/ConcreteOperations/minkowski_difference.jl
> #1587 - Minkowski difference with singleton

- docs/src/man/decompose_example.md
> #1321 - Update some manual examples

- src/Interfaces/LazySet.jl
- src/Utils/comparisons.jl
> #1823 - Use Tolerance for getfield in comparison of sets of the same type

- src/LazyOperations/Complement.jl
- test/unit_Complement.jl
> #1841 - Convexity of the complement

- src/Interfaces/AbstractHyperrectangle.jl
- src/LazyOperations/SymmetricIntervalHull.jl
- src/Sets/BallInf.jl
- src/Sets/Hyperrectangle.jl
- test/unit_BallInf.jl
> support vector particular dispatches for sev

- src/Approximations/overapproximate.jl
- test/unit_overapproximate.jl
- test/unit_template_directions.jl
> #1691 - Fallback overapproximation with an HPolytope

- docs/src/lib/conversion.md
- src/LazyOperations/ConvexHull.jl
- src/Sets/VPolygon.jl
- src/convert.jl
- test/unit_ConvexHull.jl
> #1813 - Methods for lazy convex hull array of singleton

- docs/src/lib/interfaces.md
- src/Interfaces/LazySet.jl
- test/unit_ZeroSet.jl
> #1682 - Add element type function

- src/convert.jl
> Add convert methods for identity

- docs/src/lib/interfaces.md
- src/Interfaces/AbstractPolyhedron_functions.jl
> #1619 - Add an_element for polyhedron

- docs/src/lib/interfaces.md
> #1871 - Documentation nondeterministically breaks due to missing eltype function

- .appveyor.yml
- .travis.yml
[Julia v1.3](https://julialang.org/downloads/) has been released a month ago.
> Upgrade to Julia v1.3 in builds

- src/Interfaces/AbstractZonotope.jl
- test/unit_Zonotope.jl
> #1881 - Error for vertices_list of Zonotope without generators

- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Interfaces/LazySet.jl
> #1867 - Use SingleEntryVector in an_element

- docs/src/lib/conversion.md
- src/convert.jl
- test/unit_MinkowskiSum.jl
> #1678 - add conversion

- docs/src/lib/approximations.md
- src/Approximations/iterative_refinement.jl
> #1875 -  Iterative refinement with abstract vectors

- docs/src/lib/sets/Interval.md
- src/Sets/Interval.jl
> #1903 - Constraints list for interval

- docs/src/lib/sets/Interval.md
- src/Sets/Interval.jl
- test/unit_Interval.jl
Closes https://github.com/JuliaReach/LazySets.jl/issues/1905.
> #1905 - Concrete scale of interval

- docs/src/lib/sets/Interval.md
- src/Sets/Interval.jl
- test/unit_Interval.jl
> #1902 - Concrete linear map for interval

- src/Interfaces/AbstractHPolygon.jl
> #1925 - Refactor boundnedness check for HPolygon

- docs/src/lib/utils.md
- src/Arrays/matrix_operations.jl
- test/unit_util.jl
> #1937 - Extend matrix by orthogonalization

- src/ConcreteOperations/minkowski_sum.jl
> #1960 - Pass constructor argument in concrete m-sum  

- docs/src/lib/conversion.md
- docs/src/lib/interfaces.md
- docs/src/lib/lazy_operations/SymmetricIntervalHull.md
- docs/src/lib/sets/BallInf.md
- docs/src/lib/sets/Hyperrectangle.md
- docs/src/lib/sets/Interval.md
- docs/src/lib/sets/LineSegment.md
- docs/src/lib/sets/Singleton.md
- docs/src/lib/sets/ZeroSet.md
- docs/src/lib/sets/Zonotope.md
- src/Interfaces/AbstractZonotope.jl
- src/Sets/Zonotope.jl
- src/convert.jl
- test/unit_LineSegment.jl
- test/unit_Zonotope.jl
> #1686 - Add togrep methods for AbstractZonotopes

- src/Sets/VPolytope.jl
- test/unit_Polytope.jl
> #2002 - VPolytope constructor from matrix columns

- src/Sets/Ellipsoid.jl
- test/unit_Ellipsoid.jl
> #2003 - Make isposdef check optional in Ellipsoid constructor

- src/Approximations/box_approximations.jl
> #2014 - Specialize symmetric interval hull for intervals

- docs/src/index.md
- src/LazyOperations/ConvexHull.jl
- src/Sets/Ball2.jl
> #1999 - Add vector parameter for Ball2

- docs/src/lib/sets/Ellipsoid.md
- src/Sets/Ellipsoid.jl
- test/unit_Ellipsoid.jl
> #2008 - Add shape matrix getter for Ellipsoid

- src/LazyOperations/AffineMap.jl
- src/LazyOperations/Complement.jl
- src/LazyOperations/Intersection.jl
- src/LazyOperations/LinearMap.jl
- src/LazyOperations/Translation.jl
- src/Sets/BallInf.jl
- test/unit_LinearMap.jl
> #1870 - Add type parameter in BallInf

- src/Approximations/box_approximations.jl
> #2022 - Faster symmetric interval hull for 2D hyperrectangles

- docs/src/lib/conversion.md
- docs/src/lib/sets/Interval.md
- src/Sets/Interval.jl
- src/convert.jl
- test/unit_Interval.jl
> #2020 - Make + operator lazy for intervals

- docs/src/lib/utils.md
- src/Arrays/matrix_vector_operations.jl
- test/unit_util.jl
> #2032 - Add corresponding matrix type and vector type

- docs/src/lib/interfaces.md
- src/Interfaces/LazySet.jl
- test/runtests.jl
- test/unit_area.jl
> #2055 - Area of 2D set

- src/convert.jl
- test/unit_HalfSpace.jl
> #2066 - Convert any halfspace to a Vector halfspace 

- docs/src/lib/conversion.md
- docs/src/lib/sets/Zonotope.md
- docs/src/lib/utils.md
- src/Approximations/Approximations.jl
- src/Approximations/overapproximate.jl
- src/Arrays/matrix_operations.jl
- src/ConcreteOperations/minkowski_sum.jl
- src/Sets/Interval.jl
- src/Sets/Zonotope.jl
- src/convert.jl
- test/unit_Zonotope.jl
- test/unit_util.jl
Closes https://github.com/JuliaReach/LazySets.jl/issues/1901.
Closes https://github.com/JuliaReach/LazySets.jl/issues/1975
> Remove zero gens check in zonotope constructor

- src/Sets/HalfSpace.jl
- src/Sets/Hyperplane.jl
- src/Sets/Line.jl
- test/unit_HalfSpace.jl
- test/unit_Hyperplane.jl
- test/unit_Line.jl
> #1989 - Some linear map corner cases

- src/ConcreteOperations/isdisjoint.jl
- test/unit_Interval.jl
> #2114 - Add robust intersection check for intervals

- src/Arrays/Arrays.jl
- src/Arrays/vector_operations.jl
- src/LazySets.jl
- src/Sets/VPolygon.jl
- test/unit_Polygon.jl
> #2102 - Fix numeric issue with is_right_turn

- src/Interfaces/AbstractHPolygon.jl
- test/unit_Polygon.jl
> #2103 - Fix vertices_list for empty HPolygon

- src/Sets/Hyperplane.jl
- test/unit_Hyperplane.jl
> #2115 - Add type parameter for hyperplane

- src/convert.jl
- test/unit_Zonotope.jl
> #2135 - Convert affine map of a zonotope to a zonotope

- .travis.yml
- Project.toml
This resolves #2098.
CC @giordano
> Bump RecipesBase and Julia versions

- .travis.yml
> #2141 - Avoid redundant Travis builds

- .appveyor.yml
- .travis.yml
> #2142 - Cache artifacts in CI

- src/Approximations/Approximations.jl
- src/Approximations/overapproximate.jl
- test/unit_overapproximate.jl
>  Zonotope overapproximation of polytope given generator directions 

- docs/src/lib/utils.md
- src/Approximations/decompositions.jl
- src/Arrays/matrix_operations.jl
- src/Interfaces/AbstractZonotope.jl
- src/Sets/Zonotope.jl
- test/unit_Zonotope.jl
- test/unit_util.jl
> #2147 - Remove zero generators of projected Zonotope

- src/Sets/Ballp.jl
> #2116 - Add type parameter for Ballp

- src/Approximations/template_directions.jl
- src/LazyOperations/CartesianProductArray.jl
- src/Sets/VPolygon.jl
- src/Sets/VPolytope.jl
See #2084 for the related discussion.
> Make doctests independent of Julia version

- .travis.yml
- docs/src/lib/approximations.md
- src/Approximations/Approximations.jl
- src/Approximations/distance.jl
- test/runtests.jl
- test/unit_distance.jl
I need this for some other code base but I prototyped it here so I thought I should add it here as well. I was not sure about the function name `distance`. [It seems to be a standard distance notion and not have a specific name.](https://en.wikipedia.org/wiki/Distance#Distances_between_sets_and_between_a_point_and_a_set) I am open to suggestions.
The algorithm consists of two steps: compute a shortest vector and then take the norm of that vector. Is there interest in the first part as a separate function?
Requires #2159
> Distance between two boxes

- src/ConcreteOperations/intersection.jl
- src/ConcreteOperations/issubset.jl
- src/Interfaces/AbstractHyperrectangle.jl
- src/Interfaces/AbstractZonotope.jl
- src/Sets/BallInf.jl
> #2133 - Use center(P, i) method

- docs/src/lib/lazy_operations/ConvexHull.md
- docs/src/lib/lazy_operations/UnionSet.md
- src/LazyOperations/ConvexHull.jl
- src/LazyOperations/ConvexHullArray.jl
- src/LazyOperations/UnionSet.jl
- src/LazyOperations/UnionSetArray.jl
- src/Sets/VPolytope.jl
- test/unit_ConvexHull.jl
- test/unit_UnionSet.jl
> #2152 - Vertices list of a UnionSet and ConvexHull

- src/Interfaces/AbstractPolyhedron_functions.jl
- test/unit_Polytope.jl
> #1723 Outsource linear_map_hrep_helper code given an inverse matrix

- src/Interfaces/AbstractHPolygon.jl
- test/unit_Polygon.jl
> #2168 - Rectangular linear_map from HPolygon crashes

- src/Interfaces/AbstractPolyhedron_functions.jl
- test/unit_Polytope.jl
This fixes a silly mistake from #2171.
> Fix assertion in linear_map_inverse

- docs/src/lib/lazy_operations/Rectification.md
- src/LazyOperations/Rectification.jl
- test/unit_Rectification.jl
> #2178 - Add getter function for lazy rectification

- src/ConcreteOperations/isdisjoint.jl
- test/unit_CartesianProduct.jl
> fix ambiguity error in is_intersection_empty for universal set

- docs/src/lib/interfaces.md
- docs/src/lib/sets/HPolygon.md
- docs/src/lib/sets/HPolygonOpt.md
- docs/src/lib/sets/HPolyhedron.md
- docs/src/lib/sets/HalfSpace.md
- src/Interfaces/AbstractHPolygon.jl
- src/LazySets.jl
- src/Sets/HPolyhedron.jl
- src/Sets/HalfSpace.jl
- test/unit_HalfSpace.jl
- test/unit_Polygon.jl
- test/unit_Polyhedron.jl
- test/unit_Polytope.jl
> #1698 - Function to normalize a polytope's directions

- src/Interfaces/AbstractPolyhedron_functions.jl
- test/unit_Polyhedron.jl
> #2089 - Use tolerance in membership test of Polyhedron

- src/Arrays/matrix_operations.jl
- src/Interfaces/AbstractZonotope.jl
- test/unit_Zonotope.jl
when generators are all in first/third quadrant
> Apply tricks for 2d zonotope vertex enumeration

- docs/src/lib/interfaces.md
- src/ConcreteOperations/issubset.jl
- test/unit_Zonotope.jl
> Faster Zonotope inclusion in Hyperrectangle

- src/ConcreteOperations/isdisjoint.jl
> #2202 - Extend isdisjoint for Julia v1.5 

- src/Initialization/init_Polyhedra.jl
- src/Interfaces/AbstractPolyhedron_functions.jl
- test/unit_Polytope.jl
~This is currently blocked by https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/217.~
I made the test more robust.
> Add default solver to Polyhedra backend

- src/ConcreteOperations/isdisjoint.jl
- test/unit_EmptySet.jl
> #2182 - Disjointness check with the empty set

- src/ConcreteOperations/isdisjoint.jl
> Fix duplicate isdisjoint signature

- src/Sets/Line.jl
- test/unit_Line.jl
See https://github.com/JuliaReach/LazySets.jl/pull/2210#pullrequestreview-451297693.
> Rename Line.n to Line.d

- src/Sets/PolynomialZonotope.jl
> #2117 - Add type parameters for polynomial zonotope

- src/ConcreteOperations/isdisjoint.jl
> #2113 - Robust comparison for intersection with a half-space

- test/unit_Polytope.jl
> #1036 - Add meaningful test for linear_map

- docs/src/man/polyhedral_approximations.md
> #2256 - Problems with equation rendering in documentation

- docs/src/lib/interfaces.md
- src/Interfaces/AbstractSingleton.jl
- src/Interfaces/LazySet.jl
- src/LazySets.jl
- src/Sets/LineSegment.jl
- src/Utils/iterators.jl
- test/unit_BallInf.jl
- test/unit_Polyhedron.jl
> #53 - Iterator versions of `constraints_list` and `vertices_list`

- src/Initialization/init_ModelingToolkit.jl
- src/Sets/HPolyhedron.jl
- test/unit_Polyhedron.jl
> #2222 - Add HPolyhedron constructor using symbolic vars

- src/Approximations/decompositions.jl
- test/unit_Hyperrectangle.jl
> #2190 - Concrete projection of hyperrectangular sets

- docs/src/lib/sets/Zonotope.md
- src/Sets/Zonotope.jl
- test/unit_Zonotope.jl
> #2063 - Add concrete in-place linear map for zonotope

- docs/src/lib/conversion.md
- src/Approximations/overapproximate.jl
- src/convert.jl
- test/unit_HParallelotope.jl
- test/unit_overapproximate.jl
Closes #1631.
Requires ~~https://github.com/JuliaReach/LazySets.jl/issues/1014.~~
> #1631 - Overapproximation of a zonotope with a parallelotope

- src/Approximations/decompositions.jl
- test/unit_Polygon.jl
- test/unit_Polytope.jl
> #2283 - Add concrete projection of a VPolytope

- src/Utils/comparisons.jl
- test/unit_comparisons.jl
> #2282 - Extend isapprox for matrices

- docs/src/lib/conversion.md
- src/convert.jl
- test/unit_CartesianProduct.jl
> #2299 - Convert CP and CPA of zonotopic sets to zonotope

- src/Sets/HalfSpace.jl
- test/unit_HalfSpace.jl
> #2312 - Fix robust membership test for HalfSpace

- src/ConcreteOperations/isdisjoint.jl
the implementation was sub-optimal and it was not robust. for benchmarks see https://github.com/mforets/escritoire/blob/master/2020/Week32/ZG_Disjointness.ipynb . done jointly with @SebastianGuadalupe
> Improve zonotope - hyperplane disjointness check

- docs/src/lib/utils.md
- src/Arrays/matrix_operations.jl
- src/Interfaces/AbstractZonotope.jl
- src/Sets/Zonotope.jl
- test/unit_Zonotope.jl
> #2208 - Refactor zonotope vertex enumeration methods

- src/ConcreteOperations/isdisjoint.jl
- test/unit_Hyperplane.jl
> #2327 - Hyperplane-Hyperplane intersection emptiness

- docs/src/lib/conversion.md
- src/Interfaces/LazySet.jl
- src/convert.jl
- test/unit_BallInf.jl
> Fix area for non-polygons

- docs/src/lib/sets/Zonotope.md
- src/Approximations/overapproximate.jl
- src/Sets/Zonotope.jl
- src/Utils/helper_functions.jl
- test/unit_overapproximate.jl
> #2326 - Overapproximate zonotope-hyperplane intersection using the projection method

- docs/src/lib/interfaces.md
- docs/src/lib/sets/EmptySet.md
- docs/src/lib/sets/Singleton.md
- docs/src/lib/sets/Universe.md
- docs/src/lib/sets/ZeroSet.md
- src/Interfaces/AbstractSingleton.jl
- src/Sets/EmptySet.jl
- src/Sets/Universe.jl
- test/unit_EmptySet.jl
- test/unit_Singleton.jl
- test/unit_Universe.jl
- test/unit_ZeroSet.jl
See #2264: `Universe`, `EmptySet`, `AbstractSingleton`
Bonus: `vertices_list(::EmptySet)`
> #2264 - Specialized iterator methods `constraints` and `vertices`

- src/Sets/Line.jl
- test/unit_Line.jl
> #2360 - Add new line constructor in 2d

- Project.toml
This PR updates all dependencies to their latest version. It is more general than #2358, but there will be build problems with v1.0 (which currently exist even in `master`).
> Bump all dependency limits

- src/Sets/HPolyhedron.jl
- src/Sets/HalfSpace.jl
- src/Sets/Hyperplane.jl
- test/unit_Polyhedron.jl
> #2363 - Extend HPolyhedron constructor with ModelingToolkit

- src/ConcreteOperations/minkowski_sum.jl
- src/Sets/VPolygon.jl
> #2369 - Refactor concrete minkowski sum of VPolygon

- docs/src/lib/binary_functions.md
- src/ConcreteOperations/intersection.jl
- src/ConcreteOperations/isdisjoint.jl
- test/unit_overapproximate.jl
> #2293 - Disjointness check for Line2D

- docs/src/lib/utils.md
- src/Utils/helper_functions.jl
This is code we had from https://github.com/JuliaReach/ReachabilityBenchmarks/blob/master/src/plot_GEN.jl , but it is useful quite frequently, eg. to read files generated by other tools.
> Read polygons from file

- src/Arrays/Arrays.jl
- src/Arrays/vector_operations.jl
- test/unit_Polygon.jl
> #2386 - Use approximate equality check in samedir

- .travis.yml
- deps/build_private.jl
> #2392 - Rename build script

- src/Initialization/init_ModelingToolkit.jl
- test/unit_HalfSpace.jl
> #2409 - Fix MT constructor with 1 variable

- src/Approximations/decompositions.jl
- src/Approximations/distance.jl
- src/Approximations/hausdorff_distance.jl
- src/Approximations/iterative_refinement.jl
- src/Approximations/underapproximate.jl
> Remove 'N<:Real' in Approximations

- src/Sets/HParallelotope.jl
- test/runtests.jl
- test/unit_LazySet.jl
> #2390 - `isoperationtype` is not implemented for type HParallelotope

- src/Approximations/overapproximate.jl
- test/unit_overapproximate.jl
> #2414 - MethodError for empty set overapproximation

- docs/src/man/reach_zonotopes.md
From the README at https://github.com/JuliaReach/Reachability.jl , new users should use ReachabilityAnalysis
> Refer to ReachabilityAnalysis.jl

- src/Approximations/overapproximate.jl
> #2219 - Remove 'N<:Real' in overapproximate.jl

- docs/src/lib/sets/Ball1.md
- docs/src/lib/sets/Ball2.md
- docs/src/lib/sets/BallInf.md
- docs/src/lib/sets/Ballp.md
- docs/src/lib/sets/Ellipsoid.md
- docs/src/lib/sets/EmptySet.md
- docs/src/lib/sets/Interval.md
- docs/src/lib/sets/Line2D.md
- docs/src/lib/sets/LineSegment.md
- docs/src/lib/sets/PolynomialZonotope.md
- docs/src/lib/sets/Singleton.md
- docs/src/lib/sets/Universe.md
- docs/src/lib/sets/ZeroSet.md
- docs/src/lib/sets/Zonotope.md
- src/Sets/Ball1.jl
- src/Sets/Ball2.jl
- src/Sets/BallInf.jl
- src/Sets/Ballp.jl
- src/Sets/Ellipsoid.jl
- src/Sets/EmptySet.jl
- src/Sets/Interval.jl
- src/Sets/Line.jl
- src/Sets/Line2D.jl
- src/Sets/LineSegment.jl
- src/Sets/PolynomialZonotope.jl
- src/Sets/Singleton.jl
- src/Sets/Universe.jl
- src/Sets/ZeroSet.jl
- src/Sets/Zonotope.jl
> #2219 - Remove 'N<:Real' for some set types

- docs/src/lib/binary_functions.md
- src/ConcreteOperations/isdisjoint.jl
- src/ConcreteOperations/minkowski_sum.jl
> Generalize Zonotope to AbstractZonotope in isdisjoint

- docs/src/lib/lazy_operations/Bloating.md
- src/Approximations/hausdorff_distance.jl
- src/LazyOperations/Bloating.jl
- src/Utils/helper_functions.jl
- test/unit_Bloating.jl
The last commit could be outsourced to a separate PR.
> Bloating: constraints_list and used in hausdorff_distance

- src/Interfaces/AbstractPolyhedron_functions.jl
- test/unit_plot.jl
> #2447 - Fix plot for SArray inputs

- docs/src/lib/sets/Ball2.md
- src/Sets/Ball2.jl
> Faster support function for Ball2

- src/convert.jl
> #1978 - Faster conversion from 1D hyperrectangle to interval

- src/Sets/Interval.jl
- test/unit_Interval.jl
Closes https://github.com/JuliaReach/LazySets.jl/issues/2458.
> Vertices list for degenerate interval

- src/Plotting/plot_recipes.jl
> #2464 - Specific singleton list plot

- src/Interfaces/AbstractHyperrectangle.jl
Closes https://github.com/JuliaReach/LazySets.jl/issues/2093.
This is a second take on https://github.com/JuliaReach/LazySets.jl/pull/2094.
> Add note in hyperrectangle interface

- docs/src/lib/binary_functions.md
- src/ConcreteOperations/issubset.jl
> #700 - Documentation for issubset

- docs/src/lib/interfaces.md
- docs/src/lib/lazy_operations/Complement.md
- docs/src/lib/sets/HalfSpace.md
- src/Interfaces/LazySet.jl
- src/LazyOperations/Complement.jl
- src/Sets/HalfSpace.jl
- test/unit_Complement.jl
Closes #2381.
----
I was not sure about the best location of the code (`complement` is a unary function so I didn't create a new file under `ConcreteOperations` ...).
> #2381 -- Concrete complement and constraints list of lazy complement

- docs/src/lib/interfaces.md
- src/Interfaces/AbstractZonotope.jl
- src/convert.jl
- test/unit_Zonotope.jl
See https://github.com/JuliaReach/LazySets.jl/pull/1995.
> #1995 - In-place concrete translation for AbstractZonotope

- src/LazyOperations/Intersection.jl
- test/unit_Intersection.jl
Closes https://github.com/JuliaReach/LazySets.jl/issues/2353.
> Simplification of lazy intersection of halfspaces to polyhedron

- src/convert.jl
- test/unit_Intersection.jl
See https://github.com/JuliaReach/LazySets.jl/issues/2353.
> Conversion of lazy intersection of polyhedral types

- src/ConcreteOperations/intersection.jl
- src/Sets/VPolygon.jl
- test/unit_Polygon.jl
> Rename method and reduce allocations

- src/Sets/Zonotope.jl
- test/unit_Zonotope.jl
> Apply convex hull in vertices_list(zonotope)

- docs/src/lib/binary_functions.md
- docs/src/lib/sets/HPolyhedron.md
- docs/src/lib/sets/VPolytope.md
- src/ConcreteOperations/cartesian_product.jl
- src/ConcreteOperations/convex_hull.jl
- src/ConcreteOperations/intersection.jl
- src/ConcreteOperations/minkowski_sum.jl
- src/Initialization/init_Polyhedra.jl
- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Plotting/mesh.jl
- src/Sets/HPolyhedron.jl
- src/Sets/HPolytope.jl
- src/Sets/VPolytope.jl
> #2436 - Remove argument from default_polyhedra_backend

- src/Arrays/vector_operations.jl
the function `sign_cadlag` is defined in the flie https://github.com/JuliaReach/LazySets.jl/blob/master/src/Utils/helper_functions.jl#L2
> cleanup export

- .appveyor.yml
- .github/workflows/CompatHelper.yml
- .travis.yml
- docs/src/lib/binary_functions.md
- src/ConcreteOperations/isdisjoint.jl
- src/Sets/VPolytope.jl
- src/Utils/helper_functions.jl
> #2310 - Bump CI doctests for Julia version v1.5

- test/runtests.jl
Related to https://github.com/JuliaReach/LazySets.jl/issues/2505.
> Set random seed in unit tests

- .travis.yml
> #2472 - Fix coverage integration

- src/Utils/macros.jl
> cleanup macros.jl

- docs/src/lib/conversion.md
- src/convert.jl
- test/unit_LinearMap.jl
Closes https://github.com/JuliaReach/LazySets.jl/issues/2506.
> #2506 - Generic conversion to HPolygon

- src/Sets/Singleton.jl
- test/unit_Singleton.jl
> #2519 - Concrete projection of singleton

- src/Interfaces/AbstractPolyhedron_functions.jl
- test/unit_Polytope.jl
> #2539 - Update concrete projection of HPolytope

- docs/src/lib/utils.md
- src/Utils/samples.jl
- test/unit_LineSegment.jl
Closes #2537.
Done jointly with @SebastianGuadalupe
> #2537 -- Add uniform sampling + apply it to line segment

- src/Approximations/Approximations.jl
- src/Approximations/ballinf_approximation.jl
- test/unit_ballinf_approximation.jl
> Fix robust comparison in ballinf overapproximation

- src/Sets/HPolyhedron.jl
- test/unit_Polyhedron.jl
> Fix isempty with Polyhedra backend

- docs/src/lib/lazy_operations/CartesianProduct.md
- src/LazyOperations/CartesianProduct.jl
- test/unit_Polygon.jl
This branch is based on `mforets/2528` from https://github.com/JuliaReach/LazySets.jl/pull/2530
Closes #2527.
> #2527 - Concrete projection of the cartesian product of an interval and a set in vrep

- src/ConcreteOperations/minkowski_sum.jl
- test/unit_Polygon.jl
Closes #2550.
jointly with @SebastianGuadalupe
> #2550 - Fix special case for VPolygon msum

- src/ConcreteOperations/issubset.jl
> #1298 - Singleton containment invokes the wrong method

- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Interfaces/AbstractPolytope.jl
- src/Sets/VPolygon.jl
- src/Sets/VPolytope.jl
- test/unit_Polygon.jl
- test/unit_Polytope.jl
> #674 - Remove redundant vertices from linear_map of V-reps

- src/Utils/comparisons.jl
- test/unit_util.jl
> #1337 - Fix ispermutation for approximate duplicates

- src/Interfaces/LazySet.jl
- test/unit_Polyhedron.jl
This is a proposal to fix #1916 and fix #2370 quickly.
> #1916 - Fix crash in isequivalent for same set types

- src/Sets/VPolygon.jl
- test/unit_Polygon.jl
> Use fallback _linear_map_vrep for VPolygon

- docs/src/lib/approximations.md
- src/Approximations/Approximations.jl
- src/Approximations/box_approximation.jl
- src/Approximations/init.jl
- src/Approximations/init_StaticArrays.jl
- src/Approximations/iterative_refinement.jl
- test/unit_overapproximate.jl
> #1874 - Iterative refinement fails for static vectors

- src/Sets/Interval.jl
- test/unit_Interval.jl
> #2349 - Check boundedness in Interval constructor

- docs/src/lib/binary_functions.md
- src/ConcreteOperations/intersection.jl
See https://github.com/JuliaReach/LazySets.jl/issues/2219.
> #2219 - Review dispatch on numeric type in concrete intersection

- src/ConcreteOperations/intersection.jl
- test/unit_Intersection.jl
Closes #1800.
see https://github.com/mforets/escritoire/blob/master/2021/Week7/IntersectionAxisAlignedHalfSpace.ipynb for a benchmark (the gain is ~360x in a simple 2D case, should be improve even more in higher dims).
joint with @mforets
> #1800 - Faster intersection of an axis-aligned halfspace and a hyperrectangular set

- docs/src/lib/sets/Star.md
- src/LazySets.jl
- src/Sets/Star.jl
- test/unit_Star.jl
> Change Star constructor to be an alias for a specific AffineMap

- test/unit_Polygon.jl
See https://github.com/JuliaReach/LazySets.jl/issues/2426#issue-748666506 (side note).
> Fix unit test

- test/unit_Hyperrectangle.jl
Closes #2082.
Looks like the problem was solved previously, added test just in case.
> #2082 - Type instability in hyperrectangle split

- src/Approximations/overapproximate.jl
- test/unit_overapproximate.jl
> #369 - Remove redundant constraints after iterative refinement

- src/Plotting/mesh.jl
> #1807 - Assert boundedness in plot3d

- Project.toml
- src/ConcreteOperations/convex_hull.jl
- test/runtests.jl
> #2139 - Do not depend on Plots.jl for testing

- src/Interfaces/LazySet.jl
- src/LazyOperations/CartesianProduct.jl
- test/unit_CartesianProduct.jl
> #1209 - Concrete projection of CartesianProduct

- src/LazyOperations/CartesianProduct.jl
- src/LazyOperations/CartesianProductArray.jl
- src/Sets/Line.jl
- test/unit_CartesianProduct.jl
- test/unit_Line.jl
> #1209 - Concrete projection of Line & CartesianProductArray (and modification of CartesianProduct)

- docs/src/lib/utils.md
- src/Arrays/vector_operations.jl
- test/runtests.jl
- test/unit_Polygon.jl
> #2047 - add helper function 'allequal'

- docs/src/lib/sets/HParallelotope.md
- src/Sets/HParallelotope.jl
- test/unit_HParallelotope.jl
> #2391 - Generation of random HParallelotopes

- docs/src/lib/utils.md
- src/Arrays/matrix_vector_operations.jl
- src/Sets/Star.jl
- src/Sets/Zonotope.jl
- test/unit_util.jl
> #2558 - Add `to_matrix`

- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Interfaces/AbstractPolytope.jl
- src/Sets/VPolytope.jl
Closes #2297.
Closes #2302 (I copied the idea from there and extended it to the current code base).
> #2297 - Add backend to LinearMapVRep solver

- src/Approximations/template_directions.jl
- src/Interfaces/AbstractHyperrectangle.jl
- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Interfaces/AbstractZonotope.jl
- src/Interfaces/LazySet.jl
- src/LazyOperations/CartesianProduct.jl
- src/LazyOperations/CartesianProductArray.jl
- src/LazyOperations/LinearMap.jl
- src/Sets/Ball1.jl
- src/Sets/Ball2.jl
- src/Sets/BallInf.jl
- src/Sets/Ballp.jl
- src/Sets/EmptySet.jl
- src/Sets/HalfSpace.jl
- src/Sets/Hyperplane.jl
- src/Sets/Line.jl
- src/Sets/Line2D.jl
- src/Sets/Singleton.jl
- src/Sets/Universe.jl
- src/Sets/VPolygon.jl
- src/Sets/VPolytope.jl
Closes #2301 (I copied the idea from there and extended it to the current code base).
> Accept kwargs in 'project' and pass to 'linear_map'

- src/ConcreteOperations/cartesian_product.jl
- src/convert.jl
- test/LazyOperations/CartesianProduct.jl
- test/Sets/Singleton.jl
> #2621 - Convert CP of singletons to singleton

- src/ConcreteOperations/issubset.jl
- src/Interfaces/AbstractSingleton.jl
- test/Sets/HalfSpace.jl
- test/Sets/Singleton.jl
> #2623 MethodError -> ArgumentError

- src/LazyOperations/AffineMap.jl
- src/LazyOperations/CartesianProduct.jl
- src/LazyOperations/MinkowskiSum.jl
See #1837.
This file updates the type CartesianProduct.
> update CartesianProduct docstrings

- src/LazyOperations/CartesianProductArray.jl
See #1837.
This PR addresses the CartesianProductArray type.
> Update CPA docstrings

- src/LazyOperations/Complement.jl
See #1837.
This PR updates the Complement.jl type.
> Add docs for Complement

- docs/src/lib/sets/Zonotope.md
- docs/src/lib/utils.md
- src/Arrays/matrix_operations.jl
- src/Arrays/vector_operations.jl
- src/Sets/Zonotope.jl
- test/Sets/Zonotope.jl
> #2434 - Function to remove linear dependencies in zonotope generators

- docs/src/lib/interfaces.md
- src/Interfaces/AbstractHyperrectangle.jl
- src/Interfaces/LazySet.jl
- src/LazySets.jl
- test/Sets/Polygon.jl
> #2643 - Add concrete rectification method

- docs/src/lib/conversion.md
- src/convert.jl
- test/Sets/Star.jl
> #2645 - Add conversion from polyhedral set to star set

- src/Approximations/box_approximation.jl
- src/Approximations/overapproximate.jl
- src/Interfaces/AbstractZonotope.jl
I tried out all cases. The results are identical but it saves allocations.
> Use faster sum(abs, ...)

- docs/src/lib/interfaces.md
- src/Interfaces/LazySet.jl
- test/Sets/Ball2.jl
> #2660 - Add low and high with dimension argument for arbitrary sets

- docs/src/lib/interfaces.md
- src/Interfaces/LazySet.jl
- test/Sets/Ball2.jl
> #2667 - Add low / high vectors for a LazySet

- docs/src/lib/interfaces.md
- src/Arrays/Arrays.jl
- src/Arrays/array_operations.jl
- src/Interfaces/LazySet.jl
- src/LazySets.jl
- src/Sets/HPolytope.jl
- test/Arrays/array_operations.jl
- test/Sets/HalfSpace.jl
- test/Sets/Polygon.jl
- test/runtests.jl
> #2671 -- Add rationalizion of LazySets

- src/Sets/HPolyhedron.jl
- src/Sets/HPolytope.jl
- src/Sets/HalfSpace.jl
- src/Sets/Hyperplane.jl
See https://github.com/JuliaReach/LazySets.jl/pull/2673#discussion_r619807731.
> Generalize symbolic constructors to AbstractVector

- src/ConcreteOperations/cartesian_product.jl
- test/ConcreteOperations/cartesian_product.jl
- test/runtests.jl
> cartesian_product for zonotopes and hyperrectangles

- src/LazyOperations/ExponentialMap.jl
> #1837 - Updates for ExponentialMap

- src/LazyOperations/Intersection.jl
See #1837.
I think two of the algorithms (`_line_search` and `_projection`) rely on the sets being convex (I did not thoroughly check the theory). So I added a check for convexity there and kept the requirement in the docstring.
The plot recipe also converts 1D intersections to an `Interval`. This does not work for non-convex sets (e.g., `[1, 4] ∩ ([0, 2] ∪ [3, 5]) == [1, 2] ∪ [3, 4]`). So I also added a convexity check there.
> #1837 - Updates for Intersection

- docs/src/lib/sets/Interval.md
- src/Arrays/SingleEntryVector.jl
- src/Sets/Interval.jl
- src/Utils/macros.jl
> #2682 Fix ambiguities

- src/LazyOperations/Translation.jl
> #1837 - Remove convexity requirement in Translation

- src/Arrays/vector_operations.jl
- src/LazyOperations/ResetMap.jl
See #1837.
* remove convexity assumption in docstring
* move a method to the `Arrays` module
> #1837 - Updates for ResetMap

- src/LazyOperations/AffineMap.jl
- src/LazyOperations/Bloating.jl
- src/LazyOperations/CachedMinkowskiSumArray.jl
- src/LazyOperations/CartesianProduct.jl
- src/LazyOperations/CartesianProductArray.jl
- src/LazyOperations/ExponentialMap.jl
- src/LazyOperations/Intersection.jl
- src/LazyOperations/IntersectionArray.jl
- src/LazyOperations/LinearMap.jl
- src/LazyOperations/MinkowskiSum.jl
- src/LazyOperations/MinkowskiSumArray.jl
- src/LazyOperations/ResetMap.jl
- src/LazyOperations/SymmetricIntervalHull.jl
- src/LazyOperations/Translation.jl
- src/LazyOperations/UnionSet.jl
- src/LazyOperations/UnionSetArray.jl
> #1837 - Add information about convexity preservation

- src/Plotting/plot_recipes.jl
> #2700 - Respect xlims/ylims when plotting unbounded sets

- src/Arrays/init_StaticArrays.jl
- src/Arrays/matrix_vector_operations.jl
- src/Arrays/vector_operations.jl
- src/Interfaces/AbstractHyperrectangle.jl
- src/LazySets.jl
- test/Sets/Hyperrectangle.jl
> #2651 - Fix hyperrectangle split with SVector

- docs/src/lib/interfaces.md
- src/Interfaces/LazySet.jl
- src/LazySets.jl
- src/Sets/Hyperrectangle.jl
- src/Sets/Singleton.jl
- test/Sets/Hyperrectangle.jl
- test/Sets/Singleton.jl
> #1186 - permute for Singleton and Hyperrectangle

- src/Sets/EmptySet.jl
- test/Sets/EmptySet.jl
> #2713 - Fix vertices/vertices_list for EmptySet

- docs/Project.toml
- docs/make.jl
- docs/src/lib/utils.md
- docs/src/man/tour.md
- src/Initialization/init_Symbolics.jl
See https://github.com/JuliaReach/LazySets.jl/issues/2668/
> First version of the Tour

- src/convert.jl
- test/Sets/Zonotope.jl
> #2723 - Generalize convert from Singleton to Zonotope

- docs/src/lib/binary_functions.md
- src/ConcreteOperations/intersection.jl
- test/Sets/Zonotope.jl
See https://github.com/JuliaReach/LazySets.jl/issues/2732#issuecomment-855978949.
> Add quicker concrete intersection between zonotope and halfspace

- src/Sets/HPolyhedron.jl
- src/Sets/HalfSpace.jl
- src/Sets/Hyperplane.jl
- src/convert.jl
- test/Sets/HalfSpace.jl
- test/Sets/Hyperplane.jl
> #2745 - Conversion from polyhedron to hyperplane

- src/LazySets.jl
- src/Sets/Interval.jl
> #2761 - Fix radius conflicting name with IA

- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Plotting/plot_recipes.jl
> #2763 - Fix plotting of flat 1D sets

- src/Approximations/symmetric_interval_hull.jl
- src/LazyOperations/SymmetricIntervalHull.jl
- test/LazyOperations/SymmetricIntervalHull.jl
> Add SIH constructor flag

- src/Interfaces/AbstractPolyhedron_functions.jl
- test/Sets/Polyhedron.jl
I was surprised that this never came up before :sweat_smile:
> Fix projection in unbounded dimensions

- src/ConcreteOperations/convex_hull.jl
- src/ConcreteOperations/minkowski_sum.jl
- src/LazyOperations/MinkowskiSum.jl
- test/Sets/Polygon.jl
Closes #1599.
There is a Julia error (unreachable reached). I tried many things.
> #1599 - Better concrete Minkowski sum of 2D polytopes

- src/Interfaces/AbstractSingleton.jl
- test/Sets/Singleton.jl
The version in `master` tries via `Polyhedra` and fails.
> Add chebyshev_center for singletons

- src/Sets/Ball2.jl
- test/Sets/Ball2.jl
```julia
julia> sample(rand(BallInf))
2-element Vector{Float64}:
2.1034314494918895
-1.9757450243773904
julia> sample(rand(Ball2))  # master
1-element Vector{Vector{Float64}}:
[-0.7142187306136418, 1.4464021009997]
julia> sample(rand(Ball2))  # this branch
2-element Vector{Float64}:
1.5025340666825038
-2.0303250326979714
```
> Make `sample(::Ball2)` consistent

- docs/src/lib/binary_functions.md
- src/Arrays/SingleEntryVector.jl
- src/Arrays/vector_operations.jl
- src/ConcreteOperations/cartesian_product.jl
- test/Arrays/array_operations.jl
- test/ConcreteOperations/cartesian_product.jl
> #2741 - Efficient concrete Cartesian product of hyperrectangular sets and Universe

- src/Sets/HPolygon.jl
- src/Sets/HPolygonOpt.jl
- src/Sets/HPolyhedron.jl
- src/Sets/HPolytope.jl
- src/Sets/HalfSpace.jl
- test/LazyOperations/MinkowskiSum.jl
> #2048 - Add HPoly constructors from mixed HalfSpace types

- src/Sets/Hyperplane.jl
- test/Sets/Hyperplane.jl
> #2840 - Fix isbounded of 1D Hyperplane

- src/Approximations/overapproximate.jl
> Add 'normalize' parameter to overapproximate(::TM, Zonotope)

- src/ConcreteOperations/convex_hull.jl
- test/ConcreteOperations/convex_hull.jl
> #2756 - Convex hull of a union

- src/LazyOperations/AffineMap.jl
- src/LazyOperations/Bloating.jl
- src/LazyOperations/CartesianProduct.jl
- src/LazyOperations/CartesianProductArray.jl
- src/LazyOperations/ConvexHull.jl
- src/LazyOperations/ConvexHullArray.jl
- src/LazyOperations/ExponentialMap.jl
- src/LazyOperations/Intersection.jl
- src/LazyOperations/IntersectionArray.jl
- src/LazyOperations/LinearMap.jl
- src/LazyOperations/MinkowskiSumArray.jl
- src/LazyOperations/Rectification.jl
- src/LazyOperations/ResetMap.jl
- src/LazyOperations/Translation.jl
- src/LazyOperations/UnionSet.jl
- src/LazyOperations/UnionSetArray.jl
- test/LazyOperations/AffineMap.jl
- test/LazyOperations/Bloating.jl
- test/LazyOperations/CartesianProduct.jl
- test/LazyOperations/ConvexHull.jl
- test/LazyOperations/ExponentialMap.jl
- test/LazyOperations/Intersection.jl
- test/LazyOperations/LinearMap.jl
- test/LazyOperations/MinkowskiSum.jl
- test/LazyOperations/Rectification.jl
- test/LazyOperations/ResetMap.jl
- test/LazyOperations/SymmetricIntervalHull.jl
- test/LazyOperations/Translation.jl
- test/LazyOperations/UnionSet.jl
- test/Sets/BallInf.jl
> #2776 - Add isboundedtype methods for lazy operations

- src/ConcreteOperations/isstrictsubset.jl
> Import ⊂ from IA

- src/LazyOperations/Translation.jl
This fixes a merge error in #2842 in combination with #2854.
> Fix isboundedtype(Translation)

- src/ConcreteOperations/isstrictsubset.jl
- src/LazySets.jl
> Fix ⊂ (for good)

- src/Interfaces/AbstractArraySet.jl
- src/LazySets.jl
- test/LazyOperations/CartesianProduct.jl
- test/LazyOperations/ConvexHull.jl
- test/LazyOperations/Intersection.jl
- test/LazyOperations/MinkowskiSum.jl
- test/LazyOperations/UnionSet.jl
Closes #2716.
~This branch is based on #2860.~
> #2716 - Define getindex for arrays of sets

- docs/src/lib/binary_functions.md
- src/ConcreteOperations/convex_hull.jl
Closes #2715.
~This branch is based on #2860.~
> #2715 - Make convex_hull for EmptySet a no-op

- docs/src/lib/sets/Ball1.md
- docs/src/lib/sets/Ball2.md
- docs/src/lib/sets/BallInf.md
- docs/src/lib/sets/Ballp.md
- src/Sets/Ball1.jl
- src/Sets/Ball2.jl
- src/Sets/BallInf.jl
- src/Sets/Ballp.jl
- test/Sets/Ball1.jl
- test/Sets/Ball2.jl
- test/Sets/BallInf.jl
- test/Sets/Ballp.jl
see https://github.com/JuliaReach/LazySets.jl/pull/1995
> In-place concrete translation for BallX

- docs/src/lib/sets/Ellipsoid.md
- src/Sets/Ellipsoid.jl
- test/Sets/Ellipsoid.jl
see https://github.com/JuliaReach/LazySets.jl/pull/1995
> in-place concrete translation for Ellipsoid

- src/Sets/Interval.jl
see https://github.com/JuliaReach/LazySets.jl/pull/1995/files
> Note on interval translation

- docs/src/lib/sets/VPolygon.md
- docs/src/lib/sets/VPolytope.md
- src/Sets/VPolygon.jl
- src/Sets/VPolytope.jl
- test/Sets/Polygon.jl
- test/Sets/Polytope.jl
> In-place translation for VPoly

- src/Approximations/iterative_refinement.jl
- src/Approximations/overapproximate.jl
- src/LazyOperations/ResetMap.jl
- src/Sets/VPolygon.jl
- src/Sets/VPolytope.jl
- test/Sets/Polygon.jl
- test/Sets/Polyhedron.jl
- test/Sets/Polytope.jl
> #2865 - Review usage of copy in library code

- src/Arrays/array_operations.jl
- test/Sets/Polygon.jl
> #2830 - rationalize for nested numeric vectors

- docs/make.jl
- docs/src/man/getting_started.md
- docs/src/man/optional_dependencies.md
> Move Optional Dependencies to its own page

- docs/src/lib/lazy_operations/Bloating.md
- docs/src/lib/lazy_operations/Translation.md
- src/LazyOperations/Bloating.jl
- src/LazyOperations/Translation.jl
- test/LazyOperations/Bloating.jl
- test/LazyOperations/Translation.jl
> `center` of lazy translation and bloating

- docs/src/lib/interfaces.md
- docs/src/lib/sets/Ball1.md
- docs/src/lib/sets/HParallelotope.md
- docs/src/lib/sets/HPolygon.md
- docs/src/lib/sets/HPolygonOpt.md
- docs/src/lib/sets/HPolytope.md
- docs/src/lib/sets/LineSegment.md
- docs/src/lib/sets/RotatedHyperrectangle.md
- docs/src/lib/sets/VPolygon.md
- docs/src/lib/sets/VPolytope.md
- docs/src/lib/sets/Zonotope.md
- src/Interfaces/AbstractPolytope.jl
- test/Sets/Polytope.jl
> #2111 - Volume for polytopes

- src/Sets/Singleton.jl
> #2961 - Vararg constructor for Singleton

- docs/src/lib/utils.md
- src/Utils/samples.jl
- test/Sets/Singleton.jl
Closes #2960.
```julia
@time sample(X, 10);
0.000055 seconds (31 allocations: 1.766 KiB)  # master
0.000015 seconds (13 allocations: 960 bytes)  # this branch
```
> #2960 - Special sampler for singletons

- src/Plotting/plot_recipes.jl
- test/Sets/SimpleSparsePolynomialZonotope.jl
> Add plotting recipe for SPZ

- src/ConcreteOperations/linear_combination.jl
Fixes https://github.com/JuliaReach/LazySets.jl/pull/2979#discussion_r904114933.
> Fix linear_combination for SSPZ

- src/Approximations/overapproximate.jl
> #2985 - Fix doctest (StaticArrays output changed)

- src/Approximations/overapproximate.jl
- test/Approximations/overapproximate.jl
Closes https://github.com/JuliaReach/LazySets.jl/issues/2994
> Overapproximate CH with 0-gens zonotope 

- src/Sets/Hyperplane.jl
- src/Sets/Line2D.jl
- test/Sets/Hyperplane.jl
- test/Sets/Line2D.jl
> #2919 - Numerically robust membership check for Hyperplane and Line2D

- docs/src/lib/sets/SimpleSparsePolynomialZonotope.md
- src/Sets/SimpleSparsePolynomialZonotope.jl
- test/Sets/SimpleSparsePolynomialZonotope.jl
fixes #3005
review: please check I didn't misunderstand / oversee something in the algorithm/tests :)
> add remove_redundant_generators for sspz

- src/Interfaces/ConvexSet.jl
This should have been removed in #3022.
> Remove inherited interface requirement

- src/Approximations/overapproximate.jl
- test/Sets/SparsePolynomialZonotope.jl
> add Zonotope enclosure of SPZ

- docs/src/lib/sets/SparsePolynomialZonotope.md
- src/Sets/SimpleSparsePolynomialZonotope.jl
- src/Sets/SparsePolynomialZonotope.jl
- test/Sets/SparsePolynomialZonotope.jl
> add remove_redundant_generators for SPZ

- docs/src/lib/interfaces.md
- docs/src/lib/sets/Ball2.md
- src/Interfaces/AbstractCentrallySymmetric.jl
- src/Interfaces/AbstractCentrallySymmetricPolytope.jl
- src/Interfaces/ConvexSet.jl
- src/Interfaces/LazySet.jl
- src/Sets/Ball2.jl
This is based on #3048 and #3054.
> Revise Ball2 code

- docs/src/lib/interfaces.md
- docs/src/lib/sets/Ballp.md
- src/Interfaces/AbstractCentrallySymmetric.jl
- src/Interfaces/AbstractCentrallySymmetricPolytope.jl
- src/Interfaces/ConvexSet.jl
- src/Interfaces/LazySet.jl
- src/Sets/Ballp.jl
This is based on #3048 and #3054.
> Revise Ballp code

- src/Approximations/symmetric_interval_hull.jl
- src/Approximations/underapproximate.jl
- src/ConcreteOperations/cartesian_product.jl
- src/ConcreteOperations/convex_hull.jl
- src/ConcreteOperations/minkowski_sum.jl
- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Interfaces/AbstractPolytope.jl
- src/Interfaces/ConvexSet.jl
- src/LazyOperations/Intersection.jl
- src/Plotting/mesh.jl
- src/Sets/Ball2.jl
- src/Sets/HPolyhedron.jl
- src/Sets/HPolytope.jl
- src/Sets/VPolytope.jl
> Pass __MODULE__ to require function explicitly

- docs/src/lib/sets/SparsePolynomialZonotope.md
- src/Sets/SparsePolynomialZonotope.jl
- test/Sets/SparsePolynomialZonotope.jl
- add minkowski sum for sparse polynomial zonotope
- add translate for spz
> Add translate for SPZ

- README.md
- docs/src/about.md
CC @lucaferranti
Packages: ordered alphabetically, added a new one, renamed `ClosedLoopReachability`
> Manual update: reorder packages and add contributor

- docs/src/lib/sets/EmptySet.md
- src/Sets/EmptySet.jl
- test/Sets/EmptySet.jl
The main change here is that I redefined `linear_map`. The previous implementation did not change the dimension for non-square matrices. I think that was wrong.
> Revise EmptySet code

- docs/src/lib/sets/EmptySet.md
- src/Sets/EmptySet.jl
There are some wrong docs entries (should have been part of #3079).
> Remove wrong docs entries for EmptySet

- docs/src/lib/interfaces.md
- docs/src/lib/sets/HPolyhedron.md
- docs/src/lib/sets/HalfSpace.md
- docs/src/lib/utils.md
- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Sets/HPolyhedron.jl
- src/Sets/HalfSpace.jl
- src/Sets/Hyperplane.jl
The first commit also moves some functions in the docs and changes some signatures so they only occur once in the docs.
The second and third commit change the name of two helper functions and change their signatures to avoid extra allocations.
> Revise HalfSpace code

- docs/src/lib/sets/Interval.md
- src/Initialization/init_IntervalArithmetic.jl
- src/LazySets.jl
- src/Sets/Interval.jl
- test/Sets/Interval.jl
I outsourced functionality for `IntervalArithmetic` types to its own file. The other changes are adding a helper function `_center`, some `@inbounds` annotations, and some docs improvements.
> Revise Interval code

- docs/src/lib/sets/HParallelotope.md
- docs/src/lib/sets/Interval.md
- src/Sets/HParallelotope.jl
- src/Sets/Interval.jl
This was forgotten in #3085 and #3084.
> Fix constraints_list docs HParallelotope/Interval

- docs/src/lib/sets/LineSegment.md
- src/Sets/LineSegment.jl
The main change is that I implemented `genmat` efficiently.
> Revise LineSegment code

- docs/src/lib/sets/Line.md
- src/Sets/Line.jl
- test/Sets/Line.jl
Main changes:
- fix docs setup for `constraints_list`
- fix bug in constructor with `normalize` option (did not really normalize)
- since `normalize` crashes for `Rational` numbers, I changed the default value to `false`
- fix bug in `linear_map` (could result in a line with a zero direction, thus erroring)
> Revise Line code

- docs/src/lib/binary_functions.md
- docs/src/lib/sets/Star.md
- src/Sets/Star.jl
- test/Sets/Star.jl
The only code change is in `rand`, which now generates more general star sets.
> Revise Star code

- docs/src/lib/approximations.md
- src/Approximations/template_directions.jl
The only code change is that I could remove some code duplication for `OctDirections` with different vector types.
> Revise template_directions code

- docs/src/lib/interfaces.md
- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Plotting/plot_recipes.jl
- src/Sets/VPolygonNC.jl
There are no docstrings nor tests (to be added in #3124), but the functions are simple (they were just required for plotting) and I tried plotting manually.
> Generalize plotting to non-convex sets and add some functionality for VPolygonNC

- src/ConcreteOperations/exact_sum.jl
> Fix docstring

- docs/src/lib/binary_functions.md
- src/ConcreteOperations/difference.jl
The code changes (apart from the type generalizations) are just renamings of variables.
> Revise difference code and generalize to LazySet

- docs/src/lib/interfaces.md
- docs/src/lib/sets/Singleton.md
- src/Interfaces/AbstractSingleton.jl
- src/Sets/Singleton.jl
Code changes:
- move `linear_map` to `Singleton` (was questionable to be shared by other hypothetical implementations)
- make membership check approximate
- fix plotting of 3D singletons (would previously plot in 2D instead)
> Revise AbstractSingleton code

- src/Interfaces/AbstractPolytope.jl
The only code change is to fix a TODO.
> Revise AbstractPolytope code

- docs/src/lib/binary_functions.md
- src/ConcreteOperations/intersection.jl
The main code change is:
- Fix empty intersection of two `VPolygon`s/`VPolytope`s.
> Revise intersection code and generalize to LazySet

- docs/src/lib/lazy_operations/Bloating.md
- src/LazyOperations/Bloating.jl
I added some notes and a `_bloating_ball(ε::N, p::N, n::Int)` method for clarity about negative bloating.
> Revise Bloating code

- src/Interfaces/AbstractPolyhedron_functions.jl
The only code change is a more efficient `isuniversal` method.
> Revise AbstractPolyhedron code

- src/LazyOperations/CachedMinkowskiSumArray.jl
Code change: I added `isboundedtype`.
> Revise CachedMinkowskiSum code

- docs/src/lib/lazy_operations/CartesianProduct.md
- src/LazyOperations/CartesianProduct.jl
- src/LazyOperations/CartesianProductArray.jl
Code changes:
- I renamed `linear_map_cartesian_product` to `_linear_map_cartesian_product`.
- I renamed some variables.
- The removal of the type parameter in `constraints_list` and `vertices_list` is to fix the docs entry.
> Revise CartesianProductArray code

- src/LazyOperations/ConvexHullArray.jl
Code change: Make `dim` for empty arrays consistent with other array-set types (return `0` if the array is empty).
> Revise ConvexHullArray code and generalize to LazySet

- docs/src/lib/lazy_operations/Intersection.md
- src/LazyOperations/IntersectionArray.jl
The removal of the type parameter in `constraints_list` is to fix the docs entry.
> Revise IntersectionArray code

- src/LazyOperations/InverseLinearMap.jl
The only code change is that the constructor with a `ZeroSet` and `EmptySet` now change the dimension as mentioned in the comment.
> Revise InverseLinearMap code

- src/LazyOperations/Translation.jl
- test/LazyOperations/Translation.jl
Code change: I added constructors from `EmptySet` and `Universe`, which are absorbing elements.
> Revise Translation code

- src/LazyOperations/LinearMap.jl
Code changes:
- Replace the `invoke` calls.
- Better implementation of scalar multiplication of a `LinearMap`.
- `LinearMap` of an `EmptySet` now correctly changes the dimension (as for the `ZeroSet`).
> Revise LinearMap code

- docs/src/lib/lazy_operations/Rectification.md
- src/LazyOperations/Rectification.jl
- test/LazyOperations/Rectification.jl
Code changes:
- I finished the membership test.
- I replaced support-function queries in the unit dimensions by `low`/`high`.
> Revise Rectification code and generalize to LazySet

- src/Sets/Ball2.jl
- test/Sets/Ball2.jl
> #3198 - Fix support vector of Ball2 in zero direction

- test/Sets/Polytope.jl
> #2162 - Fix warning with Polyhedra

- src/Interfaces/AbstractPolyhedron_functions.jl
See https://github.com/JuliaReach/LazySets.jl/issues/2732#issuecomment-923281040.
> #2732 - Simplify remove_redundant_constraints! code

- test/ConcreteOperations/minkowski_sum.jl
- test/runtests.jl
> Add test for #3227 (_minkowski_sum_hrep with algorithm given)

- docs/src/lib/binary_functions.md
- src/ConcreteOperations/minkowski_difference.jl
- test/Sets/Zonotope.jl
> #586 - Concrete Minkowski difference for zonotopes

- src/Approximations/overapproximate.jl
- src/Approximations/overapproximate_zonotope.jl
- src/Approximations/template_directions.jl
- test/Approximations/overapproximate.jl
>  #2833 - Fix automatic generation of template-direction instances

- docs/src/lib/interfaces.md
- docs/src/lib/sets/HPolyhedron.md
- src/Interfaces/LazySet.jl
- src/Sets/HPolyhedron.jl
> #3060 - Generalize polyhedron to LazySet

- docs/src/lib/interfaces.md
- docs/src/lib/sets/HPolyhedron.md
- src/ConcreteOperations/isdisjoint.jl
- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Interfaces/LazySet.jl
- src/LazyOperations/IntersectionArray.jl
- src/Sets/HPolyhedron.jl
- test/LazyOperations/Intersection.jl
Closes #1078.
This PR also adds `is_polyhedral(::IntersectionArray)` to fix a test.
> #1078 - Generalize isempty from HPolyhedron to (polyhedral) LazySet

- docs/src/man/getting_started.md
> Update manual (getting started)

- src/ConcreteOperations/intersection.jl
- src/Initialization/init_JuMP.jl
- src/Initialization/init_Polyhedra.jl
- src/Interfaces/AbstractPolyhedron_functions.jl
- test/Sets/Polyhedron.jl
> Remove dependency on JuMP.MOI

- src/Sets/VPolytope.jl
- test/Sets/Polytope.jl
Closes https://github.com/JuliaReach/LazySets.jl/issues/3249
> Generalize outer array container of VPolytope

- docs/make.jl
- docs/src/lib/sets/Tetrahedron.md
- src/Interfaces/AbstractPolytope.jl
- src/Interfaces/LazySet.jl
- src/LazySets.jl
- src/Sets/Tetrahedron.jl
- src/convert.jl
- test/Sets/Tetrahedron.jl
- test/runtests.jl
Closes https://github.com/JuliaReach/LazySets.jl/issues/3258
> Add Tetrahedron set type

- src/LazyOperations/CachedMinkowskiSumArray.jl
- src/LazyOperations/CartesianProductArray.jl
- src/LazyOperations/ConvexHullArray.jl
- src/LazyOperations/IntersectionArray.jl
- src/LazyOperations/MinkowskiSumArray.jl
> #232 - Remove constructor lists from docs

- .github/dependabot.yml
- .gitignore
Also gitignore `Manifest` files.
> Add dependabot

- docs/src/man/parallel_approximations.md
- src/LazyOperations/ConvexHullArray.jl
- src/Sets/SimpleSparsePolynomialZonotope.jl
- src/Sets/SparsePolynomialZonotope.jl
- src/Sets/Zonotope.jl
- test/ConcreteOperations/convex_hull.jl
- test/Interfaces/interfaces.jl
- test/Sets/LineSegment.jl
> #3302 - Fix typos

- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Interfaces/LazySet.jl
- src/Plotting/plot_recipes.jl
> #35 - 3D plot recipe for polytopes

- docs/src/lib/binary_functions.md
- src/ConcreteOperations/minkowski_difference.jl
- test/ConcreteOperations/minkowski_difference.jl
- test/Sets/Polytope.jl
- test/Sets/Zonotope.jl
- test/runtests.jl
This PR is based on #3269 to add tests.
> Add minkowski_difference for zonotopes in 1D and 2D

- src/ConcreteOperations/convex_hull.jl
- src/Interfaces/LazySet.jl
- src/LazyOperations/ConvexHullArray.jl
- src/LazyOperations/UnionSet.jl
Closes #948.
```julia
julia> C = ConvexHullArray([rand(Ball1) for _ in 1:20]);
julia> @time concretize(C)  # master
0.000117 seconds (388 allocations: 26.609 KiB)
julia> @time concretize(C)  # this branch
0.000097 seconds (142 allocations: 12.109 KiB)
```
> #948 - Faster concretize of ConvexHullArray of polytopes

- src/LazyOperations/ExponentialMap.jl
- test/LazyOperations/ExponentialMap.jl
> #823 - Convenience constructor of ExponentialMap from sparse matrix

- Project.toml
- src/Interfaces/LazySet.jl
- test/Sets/Interval.jl
> Fix linear_map with number

- src/LazyOperations/ExponentialProjectionMap.jl
> #960 - Add example to ExponentialProjectionMap docs

- src/Interfaces/LazySet.jl
- src/Utils/helper_functions.jl
- test/LazyOperations/MinkowskiSum.jl
> #1134 - tohrep/tovrep for general polyhedral sets

- src/ConcreteOperations/intersection.jl
- src/Sets/HPolytope.jl
- src/Sets/VPolytope.jl
> Do not use GLPK's presolver by default

- docs/src/lib/interfaces.md
- src/Interfaces/AbstractPolyhedron_functions.jl
- test/Sets/Polyhedron.jl
> #1057 - Feasibility test for a list of linear constraints

- src/Plotting/plot_recipes.jl
The behavior on `master` updates the plot limits only to the last set. Furthermore, if that set is unbounded, the plotting may crash. I think I covered all cases here.
(Plotting should really be revised at some point...)
> Fix plot of union

- Project.toml
- docs/Project.toml
- test/Project.toml
Closes #3401.
Closes #3399.
Closes #3398.
> Freeze version of IntervalArithmetic

- test/LazyOperations/CartesianProduct.jl
I forgot to commit the tests in #3407.
> Add tests for is_polyhedral of CartesianProductArray

- .github/workflows/CompatHelper.yml
Closes #3410.
Closes #3411.
Closes #3412.
> Stop CompatHelper from bumping frozen packages

- src/ConcreteOperations/issubset.jl
- test/ConcreteOperations/issubset.jl
> #3416 - Inclusion of zonotope without generators in polyhedron

- test/Project.toml
> IntervalMatrices v0.10 in tests

- docs/src/lib/lazy_operations/CartesianProduct.md
- src/LazyOperations/CartesianProduct.jl
- test/Aqua.jl
> Fix unbound args

- docs/src/lib/interfaces/AbstractPolygon.md
- src/Interfaces/AbstractHPolygon.jl
- src/Interfaces/AbstractPolygon.jl
- src/Sets/HPolygon.jl
- src/Sets/HPolygonOpt.jl
- test/Aqua.jl
- test/Sets/Polygon.jl
> Fix piracy with `<=`

- src/Approximations/Approximations.jl
- src/LazySets.jl
- src/Parallel/Parallel.jl
- test/Aqua.jl
> Fix piracies with `activate_assertions` & `deactivate_assertions`

- src/Utils/samples.jl
- test/Aqua.jl
> Fix piracy with `rand`

- src/Sets/Hyperplane.jl
> Temporary fix for Symbolics doctest

- src/Sets/HParallelotope/HParallelotopeModule.jl
- src/Sets/HParallelotope/constraints_list.jl
- src/Sets/HParallelotope/init_LazySets.jl
> Resolve submodule dependency via Requires

- README.md
> Add commits since last release to README

- test/Project.toml
> Allow IntervalMatrices v0.11 in tests

- docs/src/lib/sets/Interval.md
- src/Sets/Interval/IntervalModule.jl
- test/Sets/Interval.jl
> #3282 - Remove + and - methods for Interval

- src/Initialization/init_Symbolics.jl
- src/Utils/helper_functions.jl
This branch is based in #3650.
> Fix HPolytope constructor with old Symbolics version

- .github/workflows/test-pull-request.yml
- test/ConcreteOperations/isequivalent.jl
- test/Sets/Interval.jl
- test/Sets/SparsePolynomialZonotope.jl
This is needed for older Julia versions.
> Use hcat in tests

- src/Sets/VPolytope/rand.jl
- test/Sets/Polytope.jl
~This branch is based on #3677.~
> `VPolytope`: fix `rand` for `num_vertices=0`

- docs/src/lib/sets/EmptySet.md
- src/Sets/EmptySet/complement.jl
> `EmptySet`: remove type parameter from signature

- test/Sets/EmptySet.jl
> `EmptySet`: add missing test case

- docs/make.jl
To be consistent with the other packages...
> Flip order of bibliography in docs

- docs/src/lib/sets/HPolyhedron.md
- docs/src/lib/sets/HPolytope.md
- docs/src/lib/sets/VPolytope.md
- docs/src/man/concrete_polyhedra.md
- src/ConcreteOperations/intersection.jl
- src/ConcreteOperations/minkowski_sum.jl
- src/Interfaces/AbstractPolyhedron_functions.jl
- src/Sets/HPolyhedron/HPolyhedron.jl
- src/Sets/HPolyhedron/init_Polyhedra.jl
- src/Sets/HPolyhedron/tovrep.jl
- src/Sets/HPolytope/HPolytope.jl
- src/Sets/HPolytope/init_Polyhedra.jl
- src/Sets/VPolytope/VPolytope.jl
- src/Sets/VPolytope/cartesian_product.jl
- src/Sets/VPolytope/convert.jl
- src/Sets/VPolytope/init_Polyhedra.jl
- src/Sets/VPolytope/minkowski_sum.jl
- src/Sets/VPolytope/remove_redundant_vertices.jl
- test/Sets/Polyhedron.jl
- test/Sets/Polytope.jl
> Remove constructors from `HRep`/`VRep`

- src/Sets/Universe/cartesian_product.jl
I will add a test in a later PR.
> Fix numeric type in `cartesian_product` of `Universe`s

- src/ConcreteOperations/minkowski_sum.jl
I will add a test in a later PR.
> Check dimensionality in `minkowski_sum` method

- test/LazyOperations/ConvexHull.jl
- test/LazyOperations/Intersection.jl
- test/LazyOperations/MinkowskiSum.jl
- test/LazyOperations/UnionSet.jl
- test/Sets/Universe.jl
This also adds tests for #3798 and #3799.
> Revise tests for `Universe`

- test/ConcreteOperations/distance.jl
- test/ConcreteOperations/exact_sum.jl
- test/Sets/EmptySet.jl
- test/Sets/Universe.jl
- test/runtests.jl
Follow-up of #3808 testing missing new functionality.
> Add more tests for `Universe`

- docs/src/lib/concrete_binary_operations/intersection.md
- src/Approximations/overapproximate.jl
- src/ConcreteOperations/convex_hull.jl
- src/ConcreteOperations/difference.jl
- src/ConcreteOperations/distance.jl
- src/ConcreteOperations/intersection.jl
- src/ConcreteOperations/isdisjoint.jl
- src/ConcreteOperations/issubset.jl
- src/ConcreteOperations/linear_combination.jl
- src/ConcreteOperations/minkowski_difference.jl
- src/ConcreteOperations/minkowski_sum.jl
Side effect: Several of these methods used wrong variables, so they never worked. We should really add more tests...
> Collect disambiguation code

- src/LazyOperations/ConvexHull.jl
- test/LazyOperations/ConvexHull.jl
See https://github.com/JuliaReach/LazySets.jl/pull/3662#issuecomment-2657317325.
> Add alias for unary `ConvexHull`

- src/Approximations/overapproximate.jl
- test/Approximations/overapproximate.jl
Adds polytope overapproximation from #3018
> overapproximation of SPZ to VPolytope

- src/Plotting/plot_recipes.jl
This is very mildly breaking in plots.
> Revise plot recipe of small or flat 2D sets

- src/Approximations/template_directions.jl
Closes #2768.
Refactored `BoxDiagDirections` to delegate iteration logic to combined `DiagDirections` and `BoxDirections` iterators
> #2768 - Outource common code in `BoxDiagDirections`

- src/Approximations/template_directions.jl
- src/Interfaces/AbstractArraySet.jl
- src/LazyOperations/ConvexHullArray.jl
- src/LazyOperations/IntersectionArray.jl
Small tweaks and formatting of #3831 and #3832.
> Clean up code

- src/Approximations/overapproximate.jl
The code in #3821 could be improved by using the optimized `vertices_list` implementation for `Zonotope`s. This is especially useful in 2D. For the example in the test added in that PR:
```julia
julia> @time P = overapproximate(S, VPolytope)
0.000071 seconds (335 allocations: 12.062 KiB)  # master
0.000064 seconds (220 allocations: 8.297 KiB)   # this branch
```
> Simplify `overapproximate` of `SPZ` to `VPolytope`

- docs/src/lib/interfaces/AbstractZonotope.md
- docs/src/refs.bib
- src/Interfaces/AbstractZonotope.jl
- test/Sets/Zonotope.jl
Revision of #3827.
Main modifications:
- rename to `SRMB16`
- do not modify original zonotope
- add more documentation
> Revise zonotope order reduction (`SRMB16`)

- src/Utils/samples.jl
- test/ConcreteOperations/samples.jl
I added a new specialization of the `_add_generators` function to sample points on a sparse polynomial zonotopes
> add sampler for sparse polynomial zonotopes

- src/Sets/SparsePolynomialZonotope/SparsePolynomialZonotopeModule.jl
> Use new `scale` method for `SparsePolynomialZonotope`

- src/ConcreteOperations/convex_hull.jl
- src/ConcreteOperations/difference.jl
- src/ConcreteOperations/distance.jl
- src/ConcreteOperations/exact_sum.jl
- src/ConcreteOperations/intersection.jl
- src/ConcreteOperations/isdisjoint.jl
- src/ConcreteOperations/isequivalent.jl
- src/ConcreteOperations/isstrictsubset.jl
- src/ConcreteOperations/issubset.jl
- src/ConcreteOperations/linear_combination.jl
- src/ConcreteOperations/minkowski_difference.jl
- src/ConcreteOperations/minkowski_sum.jl
- src/Interfaces/AbstractHyperrectangle.jl
- src/Sets/HalfSpace/distance.jl
- src/Sets/Hyperplane/distance.jl
- src/Sets/Line/distance.jl
- src/Sets/Universe/convex_hull.jl
- src/Sets/Universe/difference.jl
- src/Sets/Universe/distance.jl
- src/Sets/Universe/intersection.jl
- src/Sets/Universe/isdisjoint.jl
- src/Sets/Universe/issubset.jl
- src/Sets/Universe/linear_combination.jl
- src/Sets/Universe/minkowski_difference.jl
- src/Sets/Universe/minkowski_sum.jl
- src/Sets/VPolytope/minkowski_sum.jl
> Remove assertions covered by `@validate`
