JuliaReach/LazySets.jl

src/Ball2.jl
src/BallInf.jl
src/CartesianProduct.jl
src/ConvexHull.jl
src/ExponentialMap.jl
src/Hyperrectangle.jl
src/LinearConstraints.jl
src/LinearMap.jl
src/MinkowskiSum.jl
src/Polygon.jl
src/Polyhedron.jl
src/Singleton.jl
src/VoidSet.jl
src/helper_functions.jl

This also fixes the recent additional unit test for `LinearMap` (I do not know why it did not work; when I tried it locally it worked; I must have done another change).
I also took the liberty and replaced `Array{X, 1}` by `Vector{X}` everywhere.

#19 - change type unions to common supertype

---

src/Hyperrectangle.jl
test/unit_Hyperrectangle.jl

The new constructor is slower and should only be used if performance is not critical.
```julia
c = ones(2)
r = [0.1, 0.2]
l = [0.9, 0.8]
h = [1.1, 1.2]
julia> @time H1 = Hyperrectangle(c, r)
0.000010 seconds (5 allocations: 192 bytes)
LazySets.Hyperrectangle([1.0, 1.0], [0.1, 0.2])
julia> @time H2 = Hyperrectangle(center=c, radius=r)
0.000048 seconds (18 allocations: 1.203 KiB)
LazySets.Hyperrectangle([1.0, 1.0], [0.1, 0.2])
julia> @time H3 = Hyperrectangle(low=l, high=h)
0.000237 seconds (68 allocations: 3.484 KiB)
LazySets.Hyperrectangle([1.0, 1.0], [0.1, 0.2])
```

#2 - alternative keyword constructor for Hyperrectangle

---

test/runtests.jl
test/unit_LazySet.jl

The test is for `σ(::Vector{Float64}, ::S)` where `S<:LazySet`.
I also added a test for `dim(S)` because it worked 😎
@mforets:
For some subtypes the `σ` test breaks with `AbstractVector`, with `Real`, and with `<:Real` (I do not know the difference to `Real`, but apparently there is one because there are less cases working).
Should we fix that?
Also, should we additionally check for the same function with `Rational`?
Since we know that for `BallInf` it will not work, we could exclude `BallInf`.

#36 - test existence of API methods

---

src/CartesianProduct.jl
src/ExponentialMap.jl
src/HPolygonOpt.jl
src/MinkowskiSum.jl

`Int` is just an alias for `Int64` on 64-bit machines and should be preferred.
`Integer` is an abstract type and should be avoided for concrete types.

rename 'Int64'/'Integer' -> 'Int'

---

docs/src/lib/operations.md
docs/src/lib/representations.md
src/Ball1.jl
src/Ball2.jl
src/BallInf.jl
src/Ballp.jl
src/CartesianProduct.jl
src/EmptySet.jl
src/ExponentialMap.jl
src/HPolygon.jl
src/HPolygonOpt.jl
src/Hyperrectangle.jl
src/LinearMap.jl
src/Singleton.jl
src/VPolygon.jl
src/ZeroSet.jl
src/Zonotope.jl

Discussion in #68.
Already available: HPolygons, CartesianProduct
Added:
* all Balls, Hyperrectangle, Singleton, VPolygon, LinearMap, Zonotope, ExponentialMap, ZeroSet, EmptySet
* conversion function for `Singleton` instead of `AbstractVector`
Missing and dismissed (outsourced to #77):
* MinkowskiSum (I have thought about it and it seems very complicated. One could subtract one set from the point and check for nonempty intersection with the other set. There is literature for the case that the sum consists of polytopes only, this could be interesting.)
* ConvexHull (I have thought about it and it seems too complicated. A sufficient test is to check containment in both generating sets, but for negative answers one has to continue, e.g., checking ray intersection from some vertex of one set …

containment methods

---

docs/src/lib/representations.md
src/Singleton.jl

A singleton is a set, so the function name did not make sense.

rename ∈ -> ⊆ for Singleton

---

src/VPolygon.jl
test/unit_Polygon.jl

#83 - fix one-vertex case for in(x, VPolygon)

---

src/Ball2.jl
src/Ballp.jl

#86 - restrict Ball2/Ballp numeric type to AbstractFloat

---

docs/make.jl

Since the docs are rendered with Documenter's native HTML renderer, MkDocs-related deps are not necessary. Just something that caught my eye.

Remove MkDocs deps from docs/make.jl

---

src/AbstractHyperrectangle.jl
src/AbstractSingleton.jl
src/Ball2.jl
test/unit_Ball2.jl
test/unit_Hyperrectangle.jl
test/unit_Singleton.jl

See #117.
I also saved a duplicate implementation for a symmetric case - could just swap the operands 👍

#117 - invert behavior of 'is_intersection_empty'

---

docs/src/index.md
docs/src/lib/operations.md
docs/src/lib/representations.md
src/AbstractHyperrectangle.jl
src/AbstractPointSymmetric.jl
src/AbstractPolytope.jl
src/AbstractSingleton.jl
src/Approximations/2D_approximations.jl
src/Approximations/decompositions.jl
src/CartesianProduct.jl
src/ConvexHull.jl
src/EmptySet.jl
src/ExponentialMap.jl
src/LazySets.jl
src/LinearMap.jl
src/MinkowskiSum.jl
src/UnionSet.jl
src/plot_recipes.jl
src/support_function.jl
test/unit_CartesianProduct.jl
test/unit_EmptySet.jl
test/unit_ZeroSet.jl

See #44.
This took way longer than I expected, and unfortunately there is a caveat:
I needed to introduce an additional numeric type parameter to the composite types (`CartesianProduct`, `MinkowskiSum`, `ConvexHull`, `LinearMap`, `ExponentialMap`) because I did not find a way how to write the signature with nested type parameters (I searched **a lot** in documentations) like this:
```julia
CartesianProduct(s::S1 where S1<:LazySet{N<:Real}, s::S2 where S2<:LazySet{N}) <: LazySet{N}
```
The problem is that `N` is not visible outside. The outer `where` syntax is only meant for functions.
@mforets: There were hidden problems in the unit tests. Let `B` be a `BallInf`. Then `2.*B` is interpreted as `2 .* B` instead of the intended `2. * B`. I changed this in a separate commit, please note this …

#44 - Parametric numeric type of a LazySet 

---

docs/src/man/reach_zonotopes.md
src/AbstractPolytope.jl
src/Approximations/decompositions.jl

```julia
!! failed to run code block.
MethodError(*, (LazySets.Zonotope{Float64}([1.0, 0.0], [0.1 0.0; 0.0 0.1]), 5.0), 0x0000000000005571) [src/man/reach_zonotopes.md]
!! failed to run code block.
MethodError(*, (LazySets.Zonotope{Float64}([1.0, 0.0, 0.0, 0.0, 0.0], [0.1 0.0 0.0 0.0 0.0; 0.0 0.1 0.0 0.0 0.0; 0.0 0.0 0.1 0.0 0.0; 0.0 0.0 0.0 0.1 0.0; 0.0 0.0 0.0 0.0 0
.1]), 5.0), 0x0000000000005571) [src/man/reach_zonotopes.md]
```
```julia
using LazySets
import LazySets.Approximations:decompose
X = Ball2(zeros(4), 1.)
Y = Hyperrectangle(3. * ones(4), 2. * ones(4))
Z = ConvexHull(X, Y)
Hd = decompose(Z, Hyperrectangle)
```
```julia
MethodError: Cannot `convert` an object of type Array{LazySets.Hyperrectangle,1} to an object of type LazySets.CartesianProductArray
This may have arisen from …
```

update set_type in decompose and doctests

---

docs/src/lib/approximations.md
src/ExponentialMap.jl
src/helper_functions.jl
test/runtests.jl
test/to_N.jl
test/unit_Ball2.jl
test/unit_BallInf.jl
test/unit_CartesianProduct.jl
test/unit_ConvexHull.jl
test/unit_Ellipsoid.jl
test/unit_EmptySet.jl
test/unit_ExponentialMap.jl
test/unit_HalfSpace.jl
test/unit_Hyperplane.jl
test/unit_Hyperrectangle.jl
test/unit_Intersection.jl
test/unit_LinearMap.jl
test/unit_MinkowskiSum.jl
test/unit_Polygon.jl
test/unit_Polytope.jl
test/unit_Singleton.jl
test/unit_SymmetricIntervalHull.jl
test/unit_UnionSet.jl
test/unit_ZeroSet.jl
test/unit_Zonotope.jl
test/unit_ballinf_approximation.jl
test/unit_box_approximation.jl
test/unit_decompose.jl
test/unit_overapproximation2D.jl
test/unit_radiusdiameter.jl

Closes #132.
There are quite a few problems that prevent using different numeric types. When they are resolved, we have to add the numeric types to the unit tests (marked with "TODO").

#132 - unit tests for different numeric types

---

REQUIRE
src/helper_functions.jl
test/runtests.jl
test/unit_interfaces.jl

Fix bug in check_method_implementation

---

docs/make.jl
docs/src/man/concrete_polyhedra.md

This branch adds some examples about `HPolytope`'s using the `Polyhedra.jl` requirement.

Docs for Concrete Polyhedra

---

docs/src/lib/representations.md
src/Zonotope.jl
test/unit_Zonotope.jl

Zonotope order reduction (Girard's algorithm)

---

docs/src/lib/representations.md
src/Zonotope.jl
test/unit_Zonotope.jl

#214 - convert from AbstractHyperrectangle to Zonotope

---

docs/make.jl
docs/src/index.md
docs/src/lib/conversion.md
src/AbstractHPolygon.jl
src/HPolygon.jl
src/HPolygonOpt.jl
src/HPolytope.jl
src/LazySets.jl
src/Zonotope.jl
src/convert.jl
test/runtests.jl
test/unit_Polygon.jl

[WIP #191] HPolygon/HPolytope conversion

---

docs/src/lib/interfaces.md
docs/src/lib/operations.md
docs/src/lib/utils.md
src/CartesianProduct.jl
src/ConvexHull.jl
src/LazySet.jl
src/MinkowskiSum.jl
src/helper_functions.jl
test/unit_MinkowskiSum.jl

See #162.
Also resolves most of #145 (had to be done in one PR) (only `ConvexHull` missing).

#162 - Add macros to automatically create boilerplate code

---

src/helper_functions.jl

The same as for other "utility functions": in a typical session these will be rarely used, thus we can opt to not clutter the namespace and search-by-tab-completion with those exports.

delete sign_cadlag helper func export

---

src/Zonotope.jl
test/unit_overapproximate.jl

Zonotope membership test using simplex

---

src/AbstractPolytope.jl
src/Approximations/box_approximations.jl
src/CartesianProduct.jl
src/HPolytope.jl
test/unit_Ball2.jl
test/unit_CartesianProduct.jl
test/unit_Ellipsoid.jl
test/unit_EmptySet.jl
test/unit_LinearMap.jl
test/unit_Polygon.jl
test/unit_Polytope.jl
test/unit_Singleton.jl
test/unit_box_approximation.jl
test/unit_overapproximate.jl
test/unit_radiusdiameter.jl

Part of #130.
100% code coverage for the `Approximations` module, interfaces, and some set types (see below).
Coverage is shown [here](https://codecov.io/gh/JuliaReach/LazySets.jl/tree/516880e03240e149a393f2f24a155b9ac9a6c695/src).

#130 - increase code coverage

---

docs/src/lib/utils.md
src/CartesianProduct.jl
src/ConvexHull.jl
src/MinkowskiSum.jl
src/helper_functions.jl

Closes #162 and closes #145 and closes #165.

#162 #145 #165 - add macro to restore old array type behavior

---

src/plot_recipes.jl

Fix hyperrectangle plot

---

src/Approximations/decompositions.jl
test/unit_decompose.jl

Modifies `default_block_structure` such that one can `decompose(S, set_type=Interval)`.

Default interval decomposition

---

src/LinearMap.jl
test/unit_interfaces.jl
test/unit_overapproximate.jl

#290 - Fix slowdown in LinearMap

---

src/ExponentialMap.jl

#306 - Revise `SparseMatrixExp`

---

src/ExponentialMap.jl

redefine eye, and add Cartesian indexing

---

docs/src/lib/representations.md
src/Interval.jl
src/convert.jl
test/unit_Interval.jl
test/unit_decompose.jl
test/unit_overapproximate.jl

#300 - Correct usage of IntervalArithmetic

---

src/LinearMap.jl
test/unit_LinearMap.jl

#321 - Vector-set multiplication

---

src/Approximations/Approximations.jl
src/Approximations/overapproximate.jl
src/Approximations/template_directions.jl
test/runtests.jl
test/unit_template_directions.jl

#326 - Template directions

---

src/HPolygonOpt.jl
src/convert.jl
test/unit_Polygon.jl

#336 - Revise conversion from HPolytope to HPolygon

---

docs/src/lib/operations.md
src/LazySet.jl
src/MinkowskiSum.jl
src/helper_functions.jl
test/unit_MinkowskiSum.jl

#342 - Add caching lazy MinkowskiSum

---

src/Approximations/decompositions.jl
src/LazySet.jl

#345 - Allow template directions in decompose

---

docs/src/lib/operations.md
src/MinkowskiSum.jl
test/unit_MinkowskiSum.jl

#350 - Add forget_sets! function to CacheMinkowskiSum

---

src/VPolytope.jl
src/helper_functions.jl

In Julia v0.7 the signature `isdefined(::Symbol)` is deprecated in favor of `isdefined(module, ::Symbol)`. 
See https://discourse.julialang.org/t/how-to-refactor-isdefined-othermodule-field-to-isdefined-v0-7/11509/6

Fix deprecated isdefined signature

---

src/AbstractHPolygon.jl
src/Ball1.jl
src/Ball2.jl
src/BallInf.jl
src/Ballp.jl
src/ConvexHull.jl
src/HPolygon.jl
src/HPolygonOpt.jl
src/HPolytope.jl
src/Hyperrectangle.jl
src/Intersection.jl
src/Line.jl
src/LineSegment.jl
src/MinkowskiSum.jl
src/VPolygon.jl
src/convert.jl
test/unit_Polygon.jl

Motivation: It should be possible to deactivate input checks in favor of performance. This is possible with `@assert` (see #70).

Use assertions for input error checks

---

docs/src/lib/binary_functions.md
docs/src/lib/representations.md
src/concrete_intersection.jl
test/unit_Hyperrectangle.jl

#396 - Concrete intersection of two hyperrectangles

---

src/LinearMap.jl

#413 - LinearMap of ZeroSet does not preserve numeric type

---

.travis.yml

`ErrorfreeArithmetic.jl`'s release got merged on `METADATA`.
Apparently the build already worked again some hours before that :confused: :question:
But anyway, now it works again.

Remove temporary 'allow failure' of v0.6.4

---

src/compat.jl

We had the condition `VERSION < v"0.7-"` and `VERSION > v"0.7-"`, which I found inconsistent. My original motivation for this PR was to unify these conditions.
In the end I merged everything into one if-then-else. I can also undo that if preferred.

Merge conditions in compat.jl

---

src/Approximations/overapproximate.jl
src/HPolytope.jl
src/LazySets.jl
src/VPolytope.jl
src/init.jl

See [this short comment](https://github.com/MikeInnes/Requires.jl#note-changes-in-v07).
I tried to be minimally invasive.

Fix depwarnings of Requires in Julia v0.7

---

docs/src/lib/representations.md
src/AbstractHPolygon.jl
src/Approximations/iterative_refinement.jl
src/HPolygon.jl
src/HPolygonOpt.jl
src/Line.jl
src/compat.jl
src/concrete_intersection.jl
test/runtests.jl
test/unit_Line.jl

#405 - Change intersection of two lines to set operation

---

docs/make.jl

See #402.
This is yet another try, should #441 not work.

#402 - Deploy docs from julia 0.6.0

---

.travis.yml

See #402.
Fix typo, and also try it with two commands again (even though this should not help).

#402 - Split travis command into two commands again

---

src/Approximations/template_directions.jl

This removes some unreachable code.

Simplify 1D case in octagon directions iterator

---

src/VPolytope.jl

Closes #461.
By default, the vertices are now copied and not shared anymore.

#461 - Change VPolytope constructor from VPolygon

---

src/AbstractHyperrectangle.jl
src/LazySet.jl

Closes #55.
@mforets: Please check that these changes are correct:
1. The diameter is *always* two times the radius (of the respective norm). So there is no need to throw an error, because it will be thrown by `radius`.
2. The diameter of a `Hyperrectangle` is defined in the same way, so we can just use the default implementation.

#55 - Revise diameter function

---

docs/make.jl
docs/src/lib/approximations.md
docs/src/lib/binary_functions.md
docs/src/lib/interfaces.md
docs/src/lib/methods_fix.md
docs/src/lib/operations.md
docs/src/lib/representations.md
docs/src/lib/utils.md
src/LazySets.jl
src/VPolytope.jl
src/plot_recipes.jl

Closes #159. Workaround for #72.
* There are still some problems with `Documenter` in case of multiple methods. As a workaround, I omit the hyperlinks when there are conflicts.
* To elaborate:
* default values (e.g., `p::Real=Inf`): This simply does not work.
* type parameters: On the lowest interface level we can use an instantiation of the type parameters, like `an_element(::LazySet{Real})`; for this case one can also create a hyperlink reference. On higher (interface/type) levels, one has to use the `where` syntax in order to use the correct method; for this case there are no hyperlinks.
* See above (`where` syntax).
* I did not find a way to make the `array` function for array types (probably due to nested type parameters) and the functions with default values …

#159, #72 - Restructuring of docs

---

docs/src/lib/operations.md

This removes docs that were wrongly introduced in #436 for two non-set types.

Remove wrong docs

---

src/ExponentialMap.jl
test/unit_ExponentialMap.jl

#484 - Fix membership test of ExponentialMap

---

src/Ball1.jl
src/Ball2.jl
src/BallInf.jl
src/Ballp.jl
src/CartesianProduct.jl
src/ConvexHull.jl
src/Ellipsoid.jl
src/EmptySet.jl
src/ExponentialMap.jl
src/HPolygon.jl
src/HPolygonOpt.jl
src/HPolytope.jl
src/Hyperrectangle.jl
src/Intersection.jl
src/Interval.jl
src/Line.jl
src/LineSegment.jl
src/LinearMap.jl
src/MinkowskiSum.jl
src/SymmetricIntervalHull.jl
src/VPolygon.jl
src/VPolytope.jl
src/ZeroSet.jl
src/Zonotope.jl
src/convex_hull_algorithms.jl

Our convenience constructors are sometimes redundant, and in Julia v0.7 they even override the default constructors (see #121). Further reading [here](https://docs.julialang.org/en/latest/manual/constructors/#Parametric-Constructors-1).

Revise set type constructors

---

src/AbstractHPolygon.jl
src/HPolytope.jl

See #121.
Possible alternative: Return something, e.g., the constraint that was added.
`push!` would return the modified array. But since the array is an implementation detail here, I would rather not return it (maybe at some point we want to change the data structure).

Void -> Nothing

---

test/to_N.jl

Use 'undef' in numeric type conversion helpers for unit tests

---

test/unit_Polygon.jl

See #121.
Julia v0.7 does not like `for p in [p, po]` anymore (and rightly so).

#121 - Rename loop variable in unit test

---

src/LinearMap.jl
test/unit_ExponentialMap.jl

See #121.
`speye` is deprecated in v0.7.

#121 - Replace 'speye' by 'sparse'

---

test/unit_ExponentialMap.jl
test/unit_ZeroSet.jl

Closes #187.
The only RNG still present is in `unit_Polygon.jl`, but it should be harmless.

#187 - Remove RNG from unit tests

---

test/unit_decompose.jl

See #121.
There was a local variable in the unit tests that was declared `const`, which is not necessary and gives a warning in v0.7.

#121 - Remove 'const' for local variable

---

test/unit_overapproximate.jl
test/unit_template_directions.jl

See #121.
This fixes the same problem as in #499, only for other operators.

#121 - Fix dot notation by adding a space

---

test/unit_decompose.jl
test/unit_template_directions.jl

See #121.
For v0.7 the imports need a stricter format.

#121 - Fix imports in v0.7

---

src/Interval.jl
test/unit_Interval.jl

#130 - Add Interval constructor and more numeric types in unit tests

---

src/HPolytope.jl
src/ZeroSet.jl

See #121.
The first commit fixes a deprecation warning.
The second commit adds type parameters where they were missing.

#121 - Add type parameters to 'zeros' function

---

src/Zonotope.jl

See #121.
Unfortunately, `using Compat: sum` leads to errors. There are several methods of `sum`, and we use at least two of them. It seems that `Compat` fixes one of them but does not support the other.

#121 - Use keyword argument form of 'sum'

---

src/Approximations/template_directions.jl

See #121.
Unfortunately, v0.7 deprecates the 'start/next/done' iterators, so now we have to support both versions.

#121 - Replace 'start/next/done' iterators -> 'iterate'

---

docs/src/lib/representations.md
src/Hyperrectangle.jl
test/unit_Hyperrectangle.jl

This is a proposal to remove one of the keyword argument constructors for `Hyperrectangle` to make the other one more efficient in Julia v0.7. We do not need the removed constructor because it just imitates the default constructor in an inefficient way.
Old version in v0.6:
```julia
julia> @time Hyperrectangle(high=[1.], low=[1.])
0.000283 seconds (72 allocations: 3.703 KiB)
LazySets.Hyperrectangle{Float64}([1.0], [0.0])
```
New version in v0.7:
```julia
julia> @time Hyperrectangle(high=[1.], low=[1.])
0.000022 seconds (15 allocations: 848 bytes)
Hyperrectangle{Float64}([1.0], [0.0])
```

More efficient alternative Hyperrectangle constructor for v0.7

---

src/Interval.jl

the comment is old, since
```julia
julia> Interval(0.0, 1.0)
LazySets.Interval{Float64,IntervalArithmetic.Interval{Float64}}([0, 1])
```

Update Interval.jl docstring

---

REQUIRE
src/AbstractHyperrectangle.jl
src/LazySets.jl
src/Zonotope.jl

See #121.
In v0.7 we could drop the dependency on `IterTools.jl`, but for now we still have it for v0.6.

#121 - Replace 'IterTools.product' -> 'Iterators.product'

---

docs/src/index.md
docs/src/lib/interfaces.md
docs/src/lib/operations.md
docs/src/lib/representations.md
docs/src/lib/utils.md
docs/src/man/reach_zonotopes.md
src/Ellipsoid.jl
src/ExponentialMap.jl
src/HPolytope.jl
src/Zonotope.jl

Fix some `Documenter` warnings for v0.7.
The remaining fails are due to #544 and #547.

Fix some problems with docs for v0.7

---

test/unit_MinkowskiSum.jl

#556 - Use different CacheMinkowskiSum constructor in unit tests

---

src/Approximations/template_directions.jl
src/CartesianProduct.jl
src/ConvexHull.jl
src/ExponentialMap.jl
src/Hyperrectangle.jl
src/Intersection.jl
src/Interval.jl
src/MinkowskiSum.jl
src/compat.jl
test/runtests.jl
test/unit_Hyperrectangle.jl

Closes #529.
#562 also adds one more `VERSION` check without `@static`, so after merging that PR we should rebase here and fix that one place, too.
EDIT: done

#529 - Use @static for Julia version switches

---

test/unit_decompose.jl
test/unit_overapproximate.jl

See #130.
This fixes two remaining TODOs in the unit tests.

#130 - Add Rational type to unit tests

---

src/AbstractHyperrectangle.jl
src/Ball1.jl
test/unit_Ball1.jl
test/unit_BallInf.jl
test/unit_Hyperrectangle.jl

#92 - Better calculation of list of vertices for degenerate centrally symmetric polytopes 

---

test/unit_Ball1.jl
test/unit_Ball2.jl
test/unit_BallInf.jl
test/unit_Ballp.jl
test/unit_CartesianProduct.jl
test/unit_ConvexHull.jl
test/unit_Ellipsoid.jl
test/unit_EmptySet.jl
test/unit_HalfSpace.jl
test/unit_Hyperplane.jl
test/unit_Hyperrectangle.jl
test/unit_Intersection.jl
test/unit_Interval.jl
test/unit_Line.jl
test/unit_LineSegment.jl
test/unit_LinearMap.jl
test/unit_MinkowskiSum.jl
test/unit_Polygon.jl
test/unit_Polytope.jl
test/unit_Singleton.jl
test/unit_SymmetricIntervalHull.jl
test/unit_ZeroSet.jl
test/unit_Zonotope.jl
test/unit_ballinf_approximation.jl
test/unit_box_approximation.jl
test/unit_overapproximate.jl
test/unit_plot.jl
test/unit_radiusdiameter.jl
test/unit_template_directions.jl

#534 - Remove redundant 'to_N(N, ...)' from unit tests

---

docs/src/lib/representations.md
docs/src/man/concrete_polyhedra.md
src/HPolytope.jl
src/VPolytope.jl
test/unit_Polytope.jl

#595 - Polytopes intersect should be intersection

---

src/plot_recipes.jl
test/unit_plot.jl

Merge recipes for polygons and add polytopes

---

src/HPolytope.jl
src/VPolytope.jl
test/unit_Polytope.jl

#559 - Tohrep, tovrep for concrete polytopes

---

docs/src/index.md

One doctest still used the old Julia v0.6 output. Not sure why this was not detected before...

Fix doctest

---

docs/src/lib/conversion.md
docs/src/lib/interfaces.md
src/AbstractHyperrectangle.jl
src/convert.jl
test/unit_Hyperrectangle.jl
test/unit_Polytope.jl

#473 - Convert AbstractHyperrectangle to HPolytope

---

test/check_method_ambiguity_binary.jl

```julia
LazySets.Approximations.decompose |   79     79
13.837921 seconds (22.25 M allocations: 1.059 GiB, 5.83% gc time)
┌ Warning: `contains(haystack, needle)` is deprecated, use `occursin(needle, haystack)` instead.
│   caller = #check_method_ambiguity_binary#20(::Bool, ::Bool, ::Function, ::typeof(is_intersection_empty)) at check_method_ambiguity_binary.jl:102
└ @ Main ~/build/JuliaReach/LazySets.jl/test/check_method_ambiguity_binary.jl:102
```

Fix "contains" deprecation

---

docs/src/lib/interfaces.md
src/LazySets.jl
src/aliases.jl
test/runtests.jl
test/unit_CompactSet.jl

#639 - Compact sets

---

docs/src/lib/binary_functions.md
src/concrete_intersection.jl
test/unit_Polygon.jl

#583 - Concrete intersection of two HPolygons

---

docs/src/lib/binary_functions.md
src/is_intersection_empty.jl
test/unit_Hyperplane.jl

#640 - Check for empty intersection of compact set with Hyperplane

---

.travis.yml
docs/src/lib/interfaces.md
docs/src/lib/methods_fix.md
src/AbstractPolytope.jl
src/VPolytope.jl
test/REQUIRE
test/runtests.jl
test/unit_Polytope.jl
test/unit_plot.jl

EDIT: Does *not* close the issue #71.

Fix broken unit tests

---

src/AbstractCentrallySymmetricPolytope.jl
src/AbstractHyperrectangle.jl
src/Interval.jl

#488 - Make Interval an AbstractHyperrectangle

---

src/AbstractPolytope.jl
src/Intersection.jl

For this type of use we don't need to import all the names of external packages, with the module's name is enough.

using -> import for algorithm modules

---

src/LinearMap.jl

#715 - Support function for LinearMap

---

docs/src/man/polyhedral_approximations.md
src/CartesianProduct.jl

#715 - ρ for CartesianProduct(Array)

---

docs/src/lib/approximations.md
src/Approximations/Approximations.jl
src/Approximations/upper_bounds.jl
test/runtests.jl
test/unit_upper_bounds.jl

#720 - add upper bounds

---

src/Zonotope.jl

#730 - Add constraints list of Zonotope

---

docs/src/lib/representations.md
src/Ball1.jl
test/unit_Ball1.jl

#731 - Constraints list of Ball1

---

src/AbstractPolytope.jl
test/unit_interfaces.jl

Closes #188.
We have to rebase with `master` after all methods have been added.

#188 - Add constraints_list to AbstractPolytope interface

---

docs/src/lib/representations.md
docs/src/lib/utils.md
src/HalfSpace.jl
src/Hyperplane.jl
src/Line.jl
src/helper_functions.jl
test/unit_HalfSpace.jl
test/unit_Hyperplane.jl
test/unit_Line.jl

#758 - Add function to obtain the constrained dimensions of a set

---

docs/src/lib/operations.md
src/CartesianProduct.jl
test/unit_CartesianProduct.jl

added constraints_list for CartesianProduct

---

docs/src/lib/binary_functions.md
src/concrete_intersection.jl
test/unit_Polyhedron.jl

#773 Add concrete intersection between HPolyhedron and any AbstractPolytope

---

docs/src/lib/binary_functions.md
src/helper_functions.jl
src/is_intersection_empty.jl
test/unit_HalfSpace.jl

#781 - Intersection emptiness check for two half-spaces

---

docs/src/lib/operations.md
src/Approximations/overapproximate.jl
src/Intersection.jl

#817 - Add method to swap arguments in a lazy operation

---

docs/src/man/reach_zonotopes_hybrid.md

I am a bit confused why we had this. But it works locally without that part.

Remove unused code in manual

---

src/AbstractPolytope.jl
src/HPolyhedron.jl
src/HPolytope.jl
src/VPolytope.jl
src/concrete_intersection.jl

Closes #842.
This PR adds P to the default_polyhedra_backend.

Dimension error for default Polyhedra backend in >= v0.7

---

src/is_intersection_empty.jl
src/is_subset.jl

#855 - Method ambiguities

---

.travis.yml

1. commit should fix
```julia
> running doctests.
ERROR: LoadError: ArgumentError: Package Compat not found in current path:
- Run `Pkg.add("Compat")` to install the Compat package.
```
2. commit should fix the same problem for `IntervalArithmetic` and `RecipesBase`

Fix Travis build of documentation

---

docs/make.jl
docs/make_doctests_only.jl
docs/src/lib/operations.md
src/LazySet.jl

See #71.
Proposal:
* reactivate strict doctests during testing
* deactivate doctests for actual docs building
Somehow it would be good to also build the manual. Currently there are errors and they are not detected (in both `master` and this branch).

Use strict doctests again

---

src/concrete_intersection.jl
test/unit_Polygon.jl

#883 - Intersection of two polygons does not detect tighter constraints correctly

---

src/AbstractHPolygon.jl
test/unit_Polygon.jl

#918 - vertices_list for AbstractHPolygon with infeasible constraints is incorrect

---

docs/make.jl

This fixes the following problem when building the docs locally:
```julia
!! Undefined binding 'LazySets._line_search'. [src/lib/operations.md]
```

Add Optim for building docs

---

docs/src/lib/binary_functions.md
src/Approximations/box_approximations.jl
src/is_subset.jl
test/unit_EmptySet.jl
test/unit_ballinf_approximation.jl
test/unit_box_approximation.jl

#930 - Define issubset for EmptySet

---

docs/src/lib/representations.md
src/HPolyhedron.jl
src/HalfSpace.jl
src/Hyperplane.jl
src/Line.jl
test/unit_Polyhedron.jl

Add constrained_dimensions method for HPolyhedron

---

src/plot_recipes.jl

#921 - Close vertex list for plotting

---

src/Approximations/decompositions.jl
test/unit_decompose.jl

#934 - Add exact projection method

---

src/HPolyhedron.jl
src/VPolytope.jl
test/unit_Polytope.jl

#943 - Update convexhull

---

docs/src/lib/representations.md
docs/src/man/set_operations.md
src/HalfSpace.jl
src/Hyperplane.jl
test/unit_HalfSpace.jl
test/unit_Hyperplane.jl
test/unit_plot.jl

See #750.
This PR brings only the support function.
Intuitively, it is clear what the support vector should look like, but I do not see the general formula.

#750 - Allow unbounded ρ for Hyperplane/HalfSpace

---

docs/src/lib/representations.md
src/Interval.jl

Closes #961.
Let
```julia
julia> using LazySets, BenchmarkTools
julia> x = Interval(0.9, 1.1)
Interval{Float64,IntervalArithmetic.Interval{Float64}}([0.9, 1.10001])
```
Master:
```julia
julia> @btime low($x)
97.383 ns (3 allocations: 288 bytes)
1-element Array{Float64,1}:
0.8999999999999999
```
This branch:
```julia
julia> @btime low($x)
28.365 ns (1 allocation: 96 bytes)
1-element Array{Float64,1}:
0.9
```

#961 - Make low/high of Interval faster

---

src/Approximations/box_approximations.jl
src/Approximations/iterative_refinement.jl
src/Approximations/overapproximate.jl
src/Approximations/template_directions.jl
src/CartesianProduct.jl
src/ConvexHull.jl
src/ExponentialMap.jl
src/HPolyhedron.jl
src/HalfSpace.jl
src/Hyperplane.jl
src/Intersection.jl
src/Interval.jl
src/Line.jl
src/LinearMap.jl
src/MinkowskiSum.jl
src/Zonotope.jl
src/convex_hull_algorithms.jl
src/helper_functions.jl
src/is_intersection_empty.jl

Closes #973.
I also took the liberty to add some more `where` conventions :smiling_imp:
The only type parameter for a matrix is in `LinearMap`, but there is also the numeric type `NM` and then I found it confusing to also use `MN`.

#973 - Use numeric / vector / matrix conventions

---

docs/Project.toml

Closes https://github.com/JuliaReach/LazySets.jl/issues/982.

Add Project.toml pinned to v0.19.7

---

src/HPolyhedron.jl
src/HalfSpace.jl
src/VPolytope.jl
test/unit_HalfSpace.jl
test/unit_Polytope.jl

#974 - tohrep and tovrep do not preserve numeric type

---

src/HPolyhedron.jl
test/unit_Polytope.jl

#1011 - Convert to Vector in polyhedron's LP

---

src/Approximations/overapproximate.jl
test/unit_overapproximate.jl

#1016 - Add faster zonotope interval box approximation

---

docs/src/lib/interfaces.md
docs/src/lib/representations.md
src/AbstractHPolygon.jl
src/HPolygon.jl
src/HPolygonOpt.jl
src/HPolytope.jl
test/unit_Polygon.jl
test/unit_Polytope.jl

#964 - Check if polytope is bounded on construction

---

src/HPolyhedron.jl
src/concrete_intersection.jl

polyhedron redundant constraints

---

docs/src/lib/representations.md
src/HPolyhedron.jl
src/is_intersection_empty.jl

#1049 - Default implementation of isempty for polyhedra

---

docs/src/lib/operations.md
src/LinearMap.jl
test/unit_LinearMap.jl

#1052 - Add constraints list of a lazy linear map

---

docs/src/lib/representations.md
src/HalfSpace.jl
test/unit_HalfSpace.jl

#1066 - Add linear map for a halfspace

---

src/compat.jl

`Compat` changed the interface to `Random`. This PR is needed to make v0.6 work again.

Adapt to Compat change

---

src/HPolyhedron.jl
src/compat.jl
test/unit_Polytope.jl

I haven't benchmarked this, but i would expect it to be more efficient to calculate the application of the linear map using the left division than calculating the full matrix inverse.

Use left division in linear map

---

docs/src/lib/binary_functions.md
src/concrete_intersection.jl
test/unit_Polytope.jl

Closes #1117.
I removed a good bunch of methods, but I think they were not helpful now that we have the `AbstractPolyhedron` interface.
I also added the concrete intersection between `VPolygon`s (in `master` this goes to `HPolytope`).

#1117 - Concrete intersection of (abstract) polyhedra

---

.travis.yml

Update travis script to use Julia v1.1 in the CI.
Requires: #1126.

Add Julia v1.1 to Travis

---

src/convert.jl

#1160 - Confusing docstring: Convert interval to hyperrectangle

---

src/AbstractPolyhedron_functions.jl
src/AbstractPolytope.jl

#1165 - Use size of m for return type

---

src/Approximations/overapproximate.jl
test/unit_overapproximate.jl

Closes #1170.
---
For a comparison with the fallback implementation using support functions see [this notebook](https://github.com/mforets/escritoire/blob/master/sets/HyperrectangleApproxOfLinearMap.ipynb).
For a randomly generated `M*H` of dimension 10, the speedup is around 10x.

#1170 - Faster hyperrectangular overapproximation of the linear map of a hyperrectangular set

---

docs/src/lib/utils.md
src/LazySet.jl
src/helper_functions.jl
test/check_method_implementation.jl

#1159 - Add subtypes function with concrete argument

---

src/Approximations/overapproximate.jl

#1199 - Add order reduction in overapproximation

---

src/Approximations/decompositions.jl

**Note that** the new part cannot be used by `decompose`, since it needs four argument syntax 
```julia
project(::HalfSpace{N},
block::AbstractVector{Int},
set_type::HalfSpace,
[n]::Int=dim(H)
) where {N<:Real}
```

Add halfspace and hpolyhedron concrete projection.

---

docs/src/lib/conversion.md
src/convert.jl
test/unit_Hyperrectangle.jl

#1222 - Convert BallInf to hyperrectangle

---

docs/src/lib/binary_functions.md
docs/src/lib/utils.md
src/CartesianProduct.jl
src/is_subset.jl
test/unit_CartesianProduct.jl

#1219 - Subset check between CartesianProductArrays

---

docs/src/lib/conversion.md
src/compat.jl
src/convert.jl
test/unit_Zonotope.jl

#1226 - Convert cartesian product of zonotopes to a new zonotope 

---

docs/src/lib/conversion.md
src/Approximations/overapproximate.jl
src/convert.jl
test/unit_CartesianProduct.jl
test/unit_Zonotope.jl
test/unit_overapproximate.jl

Closes #1220.
Convert cartesian product of two hyperrectangles to a single hyperrectangle or to a single zonotope.

#1220 - Convert cartesian product of two hyperrectangles

---

docs/src/lib/utils.md
src/Zonotope.jl
src/helper_functions.jl
test/unit_Zonotope.jl
test/unit_util.jl

#1245 - Zonotope conversion from flat hyperrectangle contains zero generators

---

src/Zonotope.jl

If the desired order is smaller than one, do not reduce the zonotope.

Revise reduce order

---

src/Approximations/template_directions.jl

This brings back Julia v0.6 support.
~I do not know what happened to Travis. The build is [here](https://travis-ci.org/JuliaReach/LazySets.jl/builds/514307364).~ Welcome back, Travis :wave:

Fix SphericalDirections in v0.6

---

src/concrete_intersection.jl

I think this simplifies the typical use of this function, by removing the second keyword argument. For example, with this commit one can use `intersection(P, Q, backend=CDDLib.Library())`.

Remove use_polyhedra_library arg in intersection

---

.travis.yml

This PR lets Travis build docs only in v0.7.
Note that we still run doctests in v1.0/v1.1 in the regular test suite.

Restrict docs building to v0.7

---

docs/src/lib/binary_functions.md
src/is_intersection_empty.jl
test/unit_Zonotope.jl

#1267 - isdisjoint for Zonotopes

---

docs/src/man/convex_hulls.md
src/AbstractSingleton.jl

See https://github.com/JuliaReach/LazySets.jl/issues/1281, this PR adds a better error message and a comment in the convex hull docs.

More documentation for singleton set membership 

---

src/is_subset.jl
test/unit_Polygon.jl

Logic:
- if `ρ(H.a, S)` is strictly smaller than `H.b` then `_leq` returns `true` => we can't prove that S is not contained in P
- if `ρ(H.a, S)` is equal to within the tolerance to `H.b` then `_leq` returns `true` => we can't prove that S is not contained in P
- if `ρ(H.a, S)` is greater to within the tolerance to `H.b` then `_leq` returns `false` => we can prove that S is not contained in P

Use robust subset check

---

docs/src/lib/representations.md
src/Zonotope.jl
test/unit_Zonotope.jl

Getter function for the generators of a Zonotope

---

docs/src/lib/interfaces.md
docs/src/lib/operations.md
docs/src/lib/representations.md
docs/src/man/reach_zonotopes.md
src/plot_recipes.jl
test/unit_plot.jl

Closes #1272.
Closes #578.
Closes #575.
With this change, the manual has to be updated accordingly (in several places passing the epsilon explicitly is no longer needed). We can do this in a follow-up PR -- this is now https://github.com/JuliaReach/LazySets.jl/issues/1321.

#1272 - Use eps by default in plots

---

src/HPolytope.jl

This change makes `vertices_list` work more efficiently with two-dimensional `HPolytope`s by default, making use of the `HPolygon` function.
A simple test shows a speedup of ~30x comparing the version in master and the one in this branch, for a polytope defined by four constraints.
The idea was originally given in: https://github.com/JuliaReach/LazySets.jl/issues/335
---
Requires https://github.com/JuliaReach/LazySets.jl/pull/1342/

Variable algorithm for vertices list of HPolytope

---

src/comparisons.jl
test/unit_comparisons.jl

Closes #1366.
The last commit is unrelated, but I found it weird that we have different (and actually inconsistent) behavior for `Rational`s. I would actually argue that we should also remove the default for `_leq` for the same reason, but I did not have a closer look at it.

#1366 - Approximate equality test for `Rational`s

---

docs/src/lib/binary_functions.md
src/concrete_intersection.jl
test/unit_Interval.jl

Closes #1344.
```julia
julia> using LazySets, BenchmarkTools
julia> i = Interval([1., 2.]);
julia> hs = HalfSpace([1.], 1.5);
julia> hp = Hyperplane([-1.], -1.5);
julia> b = Ball1([2.], 0.5);
julia> c = ConvexHull(Singleton([-5.]), Singleton([-1.]));
julia> @btime intersection(i, hs)  # master
60.737 μs (210 allocations: 14.02 KiB)
HPolytope{Float64}(HalfSpace{Float64}[HalfSpace{Float64}([-1.0], -1.0), HalfSpace{Float64}([1.0], 1.5)])
julia> @which intersection(i, hs)  # uses generic intersection of polyhedra
intersection(P1::AbstractPolyhedron{N}, P2::AbstractPolyhedron{N}) where N<:Real in LazySets at LazySets/src/concrete_intersection.jl:345
julia> @btime intersection(i, hs)  # new
338.991 ns (9 allocations: 160 bytes)
Interval{Float64,IntervalArithmetic.Interval{Float64}}([1, 1.5]) …
```

#1344 - Efficient intersection with intervals

---

src/VPolytope.jl

This PR is related to https://github.com/JuliaReach/LazySets.jl/issues/941. 
Notes:
- the binary convex hull of two `VPolytope` now relies on the implementation of the concrete convex hull; the flow of that function is now similar to that of `VPolygon` (taking the union and calling convex hull)
- solves the `convex_hull` of empty `VPolytope` reported [here](https://github.com/JuliaReach/LazySets.jl/issues/947)
- this has the benefit that specific 1D and 2D implementations are used, while the higher-dim case uses `Polyhedra`
Some figures for a random polytope with 20 vertices:
-  in 2D: ~ 4us with Vpolygon; ~1.8ms with CDDLib; ~8.4ms with DefaultLibrary
- in 3D: ~2.2ms with CDDLib;  ~330ms with DefaultLibrary
Related to  https://github.com/JuliaReach/LazySets.jl/pull/1343 (make CDDLib …

Improve binary convex hull of VPolytope

---

docs/src/lib/representations.md
src/VPolygon.jl
test/unit_Polygon.jl

#666 - Concrete Minkowski sum for polygons

---

src/Approximations/box_approximations.jl
test/unit_box_approximation.jl

#1176 - Box approximation for Rectification

---

docs/src/lib/interfaces.md
docs/src/lib/operations.md
docs/src/lib/representations.md
docs/src/man/reach_zonotopes.md
src/AbstractPolyhedron_functions.jl
src/AbstractSingleton.jl
src/EmptySet.jl
src/Intersection.jl
src/Interval.jl
src/LazySet.jl
src/LineSegment.jl
src/plot_recipes.jl
test/unit_plot.jl

See #237.
Most important changes:
* Plotting a vector of sets now falls back to the plot recipes for each individual set. This saves lots of code duplication and is generally preferable for both efficiency and consistency. In particular, this allows to plot  vectors containing lazy `Intersection`s.
* Arbitrary 1D sets can now be plotted.
* Common plotting options are unified.

#237 - Clean up plot_recipes

---

docs/src/lib/interfaces.md
docs/src/lib/representations.md
src/AbstractHPolygon.jl
src/AbstractHyperrectangle.jl
src/AbstractPolyhedron.jl
src/AbstractPolyhedron_functions.jl
src/Approximations/decompositions.jl
src/Ball1.jl
src/CartesianProduct.jl
src/HPolygon.jl
src/HPolygonOpt.jl
src/HPolyhedron.jl
src/HPolytope.jl
src/HalfSpace.jl
src/Hyperplane.jl
src/Line.jl
src/LineSegment.jl
src/Translation.jl
src/Universe.jl
src/VPolygon.jl
src/VPolytope.jl
src/Zonotope.jl
src/helper_functions.jl
test/unit_HalfSpace.jl
test/unit_Polygon.jl
test/unit_Polyhedron.jl

Closes #1031.
Replaces #1032.
I had to remove the `convert` method for `HalfSpace` because a generic vector cannot be converted.

#1031 - Change vector type in halfspace's def

---

src/Approximations/iterative_refinement.jl

Closes #571.
I had first added a type restriction on the input, but we do use iterative refinement with `ε = Inf` sometimes in the tests. So I decided to instead just raise an informative error message if one tries to use a smaller value for `ε`.

#571 - Restrict iterative refinement to AbstractFloat

---

src/concrete_convex_hull.jl
test/runtests.jl
test/unit_convex_hull.jl

#1383 - Convex hull of a triangle

---

src/Approximations/overapproximate.jl
test/unit_overapproximate.jl

Decomposed linear map of CartesianProductArray

---

src/concrete_intersection.jl
test/unit_Polytope.jl

Resolves the last part of #565.
When we take the concrete intersection of two polyhedra whose intersection is empty, we returned
* an `EmptySet` with our custom LP-solver implementation,
* an `HPolytope` with no constraints with the default `Polyhedra` backend, and
* an `HPolytope` with infeasible constraints with the `CDDLib` backend.
Now we always return an `EmptySet` in all three cases.

Check for emptiness in concrete intersection using Polyhedra

---

src/plot_recipes.jl

EDIT: outdated
I used `:auto` because it seems to be an intuitive value, but `Plots` does not recognize it when using `plot!`. So I had to add these `if`s. However, when I use the value `:none` instead, `plot!` overwrites the value. So I think we need these `if`s anyway, and then I prefer `:auto`.

Set default aspect ratio in plot recipes to :none

---

src/LazySets.jl

Apparently this export got lost. You could use `×` if `LinearAlgebra` was loaded, but not by just loading `LazySets`.

Export 'times' symbol

---

test/unit_ConvexHull.jl
test/unit_convex_hull.jl

See https://github.com/JuliaReach/LazySets.jl/pull/1434#issuecomment-501975584.

Move and fix tests for convex_hull

---

docs/src/lib/utils.md
src/concrete_convex_hull.jl
src/helper_functions.jl
test/runtests.jl
test/unit_convex_hull.jl

#1384 - Add four point case for convex hull

---

docs/src/lib/binary_functions.md
docs/src/lib/operations.md
docs/src/lib/utils.md
src/Approximations/overapproximate.jl
src/CartesianProduct.jl
src/LazySets.jl
src/LinearMap.jl
src/Translation.jl
src/concrete_intersection.jl
src/helper_functions.jl
src/intersection_helper.jl
src/is_intersection_empty.jl
test/unit_CartesianProduct.jl
test/unit_Translation.jl
test/unit_overapproximate.jl

Example of the algorithm:
Assume we have a cartesian product array: `I_1 \times I_2 \times I_3 \cap Y` where `Y = Halfspace([1.,1., 0.], 1.)`. It means we take union of I_1 and I_2. Basically for union I run `HPolytope(constraints_list(CartesianProductArray(I_1, I_2)))`. Resulted set I intersect with projection of `Y` onto variables 1 and 2.  Now we need to decompose it back to the original blocks`\hat{I_1} \times \hat{I_2} `.  This is the place where we cannot get exact result and need an overapproximation. 
In last step we take `\hat{I_1} \times \hat{I_2} ` and merge it with unused blocks (here it is `I_3`). So the final set is `\hat{I_1} \times \hat{I_2} \times I_3`

Decomposed intersection for CartesianProductArray

---

docs/src/lib/interfaces.md
docs/src/lib/representations.md
src/AbstractHyperrectangle.jl
src/AbstractSingleton.jl
src/EmptySet.jl
src/Interval.jl
src/ZeroSet.jl

See #600.
```julia
julia> @btime ρ($[1., 0.], $(BallInf(zeros(2), 1.)))
7.835 ns (0 allocations: 0 bytes)  # this branch
87.346 ns (2 allocations: 192 bytes)  # master
```

#600 - Specialized support function computations

---

docs/src/lib/interfaces.md
docs/src/lib/representations.md
docs/src/man/reach_zonotopes.md
src/AbstractZonotope.jl
src/Zonotope.jl

#1413 - Add concrete version of zonotope algorithm to manual

---

docs/src/lib/utils.md
src/Arrays/vector_operations.jl
test/runtests.jl
test/unit_convex_hull.jl

Closes #1463.
As a bonus, by removing the array allocation the implementation became more efficient:
```julia
@btime is_cyclic_permutation(ccw_p, ccw_expr);  # first example in test/unit_convex_hull.jl
309.650 ns (6 allocations: 496 bytes)  # master
126.715 ns (3 allocations: 176 bytes)  # this branch
```

#1463 - Rename iscounterclockwise -> is_cyclic_permutation

---

src/Arrays/matrix_operations.jl
test/unit_Zonotope.jl

Closes #1468.
The fix is only partial because it only works for `Float64`.
```julia
julia> LazySets.Arrays.rank(sparse(Float64[1 0; 0 1]))
2
julia> LazySets.Arrays.rank(sparse(Float32[1 0; 0 1]))
ERROR: MethodError: no method matching qr(::SparseMatrixCSC{Float32,Int64}, ::Type{Val{true}}; tol=9.536743f-6)
julia> LazySets.Arrays.rank(sparse(Rational{Int}[1 0; 0 1]))
ERROR: MethodError: no method matching eps(::Type{Rational{Int64}})
```

#1468 - Rank of sparse matrix

---

src/is_intersection_empty.jl
test/unit_Hyperrectangle.jl

#1457 - Unsound witness in isdisjoint for hyperrectangles

---

src/concrete_convex_hull.jl
test/unit_Zonotope.jl
test/unit_convex_hull.jl

Closes #1471.
Requires: ~~#1484.~~
---
I hesitated to keep the current version and use dispatch on values, and finally decided against it. If we have an application that requires sorting, it is easy to reimplement it.

#1471 - No sorting for two-points convex hull

---

src/AbstractPolytope.jl
src/HPolytope.jl

This PR passes the `backend` argument to `vertices_list` when needed which would be otherwise ignored.
There is also a fix in the sizehint.

Fix backend arguments in concrete minkowski sum

---

docs/make.jl

This change generates docs for functions inside the `@require` block.

Load TaylorModels when building the docs

---

docs/src/lib/representations.md
src/HPolyhedron.jl
src/HalfSpace.jl
src/Hyperplane.jl
src/LazySet.jl
src/Line.jl
src/Universe.jl
test/unit_HalfSpace.jl
test/unit_Hyperplane.jl
test/unit_Line.jl
test/unit_Polyhedron.jl
test/unit_Universe.jl

See #1125.
This replaces the case split by proper dispatch methods.

#1125 - Add isuniversal methods for unbounded set types

---

src/VPolytope.jl
test/unit_Polytope.jl

Closes #1233.
We might even want to drop the other algorithm because it is always inferior.
```julia
using LazySets, BenchmarkTools, Polyhedra
function benchmark(n)
P = rand(VPolytope, dim=n, num_vertices=10)
d = rand(n)
@btime σ($d, $P, algorithm=$"hrep")
@btime σ($d, $P, algorithm=$"sfun")
end
for n in 1:8
benchmark(n)
end
```
```julia
39.861 μs (187 allocations: 8.53 KiB)
165.692 ns (0 allocations: 0 bytes)
1.182 ms (13276 allocations: 828.88 KiB)
168.392 ns (0 allocations: 0 bytes)
4.208 ms (71792 allocations: 5.22 MiB)
179.587 ns (0 allocations: 0 bytes)
14.202 ms (248627 allocations: 21.41 MiB)
194.296 ns (0 allocations: 0 bytes)
42.561 ms (659218 allocations: 57.89 MiB)
202.488 ns (0 allocations: 0 bytes)
22.158 ms (346066 allocations: 32.52 MiB)
208.631 ns (0 allocations: 0 bytes) …
```

#1233 - Efficient support vector for VPolytope

---

Project.toml
src/LazySets.jl
src/init.jl
src/mesh.jl

Closes #1252.
This file adds functionality to plot any abstract polytope or any lazy set whose constraints list can be computed. It relies on converting an `HPolytpe` into a `Polyhedra.Mesh`, which can be plotted with `Makie`. 
It remains to see if we can refactor `plot3d` and `plot3d!`, and to load this file using a `Requires` block.

#1252 - Add mesh.jl file

---

docs/src/lib/operations.md
docs/src/lib/utils.md
src/AbstractPolygon.jl
src/Arrays/vector_operations.jl
src/VPolygon.jl
src/concrete_convex_hull.jl

Closes #1379.
We had `right_turn(O, u, v)` and `is_right_turn(u, v)`. Here I added the two missing counterparts `right_turn(u, v)` and `is_right_turn(O, u, v)`.
I shortly considered to rename `right_turn` → `Base.cross`, but then decided against it.

#1379 - Revise (is_)right_turn

---

docs/src/lib/binary_functions.md
src/Approximations/overapproximate.jl
src/intersection_helper.jl
src/is_intersection_empty.jl
test/unit_CartesianProduct.jl
test/unit_overapproximate.jl

See #1449.
Some of the tests needed to be changed because we use line search for `HalfSpace` intersections (which comes with float issues) but another method for `HPolyhedron` intersection even for just one constraint (i.e., equivalent to a `HalfSpace`).

#1449 - Generalize isdisjoint(::CPA, ::HPolyhedron) to AbstractPolyhedron

---

docs/src/lib/comparisons.md
src/comparisons.jl
test/unit_Interval.jl
test/unit_comparisons.jl

See #1485.
This PR is an idea for optional tolerance setting such that it extends to all functions that rely on `comparisons.jl`. It adds getter and setter functions for `Float64` since it's the type that we use in applications, and `Rational{Int}`. For other numeric types, the behavior is left unchanged (one cannot set defaults).

Tolerance setting

---

docs/src/lib/operations.md
src/Intersection.jl

Closes #1076.
The second commit is borrowed from #1502.
`Reachability` tests still pass with this change.

#1076 - Intersection: assert compactness; generalize to AbstractPolyhedron 

---

docs/src/lib/representations.md
src/BallInf.jl
test/unit_BallInf.jl

Closes #1459.
```julia
julia> using LazySets, BenchmarkTools
julia> for n in [1, 10, 100, 1000]
B = rand(BallInf, dim=n)
@btime σ($(ones(n)), $B)
end
79.740 ns (2 allocations: 192 bytes)
97.977 ns (2 allocations: 320 bytes)
236.966 ns (2 allocations: 1.75 KiB)
2.022 μs (2 allocations: 15.88 KiB)
48.857 ns (1 allocation: 96 bytes)
61.066 ns (1 allocation: 160 bytes)
116.163 ns (1 allocation: 896 bytes)
971.600 ns (1 allocation: 7.94 KiB)
```

#1459 - Faster support vector/function for BallInf

---

src/AbstractHyperrectangle.jl
test/unit_Hyperrectangle.jl

Closes #593.
The implementation is actually faster even if the radius does not contain zeros. The old implementation is only faster if the radius is all zero (because we had hard-coded that case; but I think this is such a rare case that we should not optimize for it).
(In the code piece below, `vertices_list2` is the new implementation.)
```julia
julia> H = rand(Hyperrectangle, dim=4)
Hyperrectangle{Float64}([-1.03944, 0.108362, 1.35677, 0.492468], [0.0479897, 0.60482, 1.01331, 0.0135837])
julia> @btime vertices_list($H);
1.661 μs (29 allocations: 2.91 KiB)
julia> @btime vertices_list2($H);
748.148 ns (19 allocations: 2.16 KiB)
julia> H = Hyperrectangle(H.center, [0., 0., 1., 0.])
Hyperrectangle{Float64}([-1.03944, 0.108362, 1.35677, 0.492468], [0.0, 0.0, 1.0, 0.0])
julia> …
```

#593 - Faster vertices_list implementation for flat hyperrectangles

---

docs/src/lib/approximations.md
src/Approximations/Approximations.jl
src/Approximations/overapproximate.jl
src/Approximations/template_directions.jl
test/unit_template_directions.jl

Closes #1292.
@mforets: Please in particular check whether in the first commit the `isbounded` methods for polar and spherical directions are correct. I am not very familiar with them.

#1292 - Custom template directions

---

src/Approximations/Approximations.jl
src/is_intersection_empty.jl

Note [this comment](https://github.com/JuliaReach/LazySets.jl/issues/936#issuecomment-444537307), but having to do `using LazySets.Approximations: project` all the time is annoying.

Export project function

---

src/CartesianProduct.jl
test/unit_CartesianProduct.jl

This constructor exists since earlier versions prior to `xxxArray`, but it is no longer used (and its use is not recommended), so we may as well remove it in library code.

Remove cp array from cp constructor

---

.travis.yml
Project.toml
src/Approximations/init.jl
src/Approximations/init_IntervalMatrices.jl
src/Approximations/overapproximate.jl
test/runtests.jl
test/unit_overapproximate.jl

Closes #1424.
Requires:
* ~https://github.com/JuliaReach/IntervalMatrices.jl/issues/14~
* external fix with `IntervalArithmetic`  (https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/317)

#1424 - Overapproximate the interval matrix map of a zonotope

---

src/AbstractPolyhedron_functions.jl
src/HPolyhedron.jl
src/LazySets.jl
src/VPolytope.jl
src/Zonotope.jl
src/concrete_intersection.jl
src/init_Polyhedra.jl
src/is_intersection_empty.jl
test/unit_Polygon.jl
test/unit_Polytope.jl
test/unit_ResetMap.jl

Closes #1055.
This is mainly a copy of #1146 with several fixes. The rational LP solver has several problems (we never used it before).
1. We now get several of these warnings:
```julia
┌ Warning: Problem is infeasible, but infeasibility ray ("Farkas proof") is unavailable; check that the proper solver options are set.
└ @ MathProgBase.HighLevelInterface ~/.julia/packages/MathProgBase/rVlFR/src/HighLevelInterface/linprog.jl:89
```
Assuming that `GLPKSolverLP(method=:Exact)` is the correct way to create the solver, there is nothing we can do I think. Hopefully this will get resolved when we switch to `MathOptInterface` in #1493.
2. The rational LP solver crashes if there are no constraints. Hence I caught this corner case explicitly to make `isempty(HPolyhedron{Rational{Int}}())` work …

#1055 - Add global default LP solver

---

docs/src/lib/operations.md
src/Approximations/overapproximate.jl
src/Intersection.jl
test/unit_overapproximate.jl

Closes #1352.
Marking this as WIP since i consider it still under discussion.

#1352 - Disambiguation for lazy intersection of polyhedra 

---

docs/src/lib/approximations.md
src/Approximations/Approximations.jl
src/Approximations/hausdorff_distance.jl
src/Ballp.jl
test/runtests.jl
test/unit_hausdorff_distance.jl

Closes #1536.
Requires:
* ~The inclusion check fails because we do not have `constraints_list(::MinkowskiSum)`. We can start with #1563.~
* ~bugfix for `minkowski_sum` (#1592)~

#1536 - Function to compute the Hausdorff distance between two sets

---

src/concrete_convex_hull.jl

I found this easier to read (I had to look up the meaning of `axes`. (Side note: There is also a better method that also takes the dimension, so one need not access the first dimension of the result.)
As a small bonus, the new version uses fewer allocations.
```julia
julia> using LazySets, BenchmarkTools
julia> P = [rand(2) for i in 1:100]
julia> @btime convex_hull($P);
9.753 μs (12 allocations: 2.03 KiB)  # this branch
9.768 μs (13 allocations: 2.17 KiB)  # master
```

Remove axes function

---

docs/src/lib/representations.md
src/AbstractPolyhedron_functions.jl
src/HPolyhedron.jl

Closes #1639 
@ueliwechsler: Can you try this version and report back, please? You need to `dev LazySets` and then go to `.julia/dev/LazySets/` and check out the branch `schillic/1639`.
EDIT: The build failure is unrelated - a new version of `JuMP` got released and now there is a problem (see #1642).

#1639 - Fix problems with type parameters on WIndows

---

docs/src/lib/interfaces.md
docs/src/lib/operations.md
docs/src/lib/representations.md
src/AbstractZonotope.jl
src/Zonotope.jl
src/concrete_minkowski_sum.jl
test/unit_AffineMap.jl
test/unit_Hyperrectangle.jl
test/unit_LinearMap.jl

I was not sure about generalizing `translate` because it is probably expected that the result is of the same type as the input. But since we can (and should) always override the implementation for subtypes, I decided to generalize it as well.

Generalize Zonotope methods to AbstractZonotope

---

docs/src/lib/operations.md
src/AffineMap.jl
src/ExponentialMap.jl
src/LinearMap.jl
src/ResetMap.jl

Closes #1606.
* I skipped `ExponentialProjectionMap` because it is not used and does not have the bug.

#1606 - Revise lazy-map constructors

---

Project.toml

There is an upstream change that brought incompatibility issues with `SpecialFunctions`. Downgrading `Distributions` is one valid solution.

Downgrade Distributions to v0.19.2

---

src/Zonotope.jl
test/check_method_ambiguity_binary.jl
test/unit_Zonotope.jl

#1662 - Dimensional check in zonotope constructor

---

src/Approximations/overapproximate.jl
test/unit_overapproximate.jl

Closes #1672.
This is a quick implementation. In general it would be preferable to have an implementation for #1113.

#1672 - Overapproximation of ResetMap by CartesianProductArray

---

docs/src/lib/operations.md
src/ConcreteOperations/reflection.jl
src/LazySets.jl
test/unit_Polytope.jl

Closes #1559.
Not 100% sure, if overloading `-` operator is a good idea, it could possibly add ambiguities. For example, if we would implement a lazy Minkowski Difference (overapproximation) functionality.

Add concrete reflection operation

---

src/Interfaces/AbstractPolyhedron_functions.jl
src/Interfaces/AbstractPolytope.jl

I think the method fits better in `AbstractPolyhedron_functions.jl` because we also use `Polyhedra` for polyhedra and we also define the default LP solvers there.

Move method

---

src/Initialization/init_Polyhedra.jl

Not sure if this is a recent feature, but we can create the backend with the correct numeric type (which I think we should always do for stability).

Create Polyhedra library with the same numeric type

---

src/ConcreteOperations/isdisjoint.jl

Closes #1727.
Platooning benchmark:
`master`:
("PLAD01_BND42", "discrete") => TrialEstimate(282.038 ms)
("PLAN01_UNB50", "discrete") => TrialEstimate(7.917 s)
("PLAD01_BND42", "dense") => TrialEstimate(860.151 ms)
("PLAN01_UNB50", "dense") => TrialEstimate(11.131 s)
this branch:
("PLAD01_BND42", "discrete") => TrialEstimate(204.435 ms)
("PLAN01_UNB50", "discrete") => TrialEstimate(7.312 s)
("PLAD01_BND42", "dense") => TrialEstimate(699.705 ms)
("PLAN01_UNB50", "dense") => TrialEstimate(10.025 s)
(Note that the performance is not as good as before the commit mentioned in #1727 because there is another regression.)

#1727 - Use faster disambiguation in isdisjoint(::CPA, ::HalfSpace)

---

src/Approximations/Approximations.jl
src/Arrays/Arrays.jl
src/Assertions/Assertions.jl
src/LazySets.jl
src/Parallel/Parallel.jl
src/Utils/assertions.jl

First part of #1699.
```julia
julia> @time Hyperplane(ones(2), 1.)  # warm-up
0.036591 seconds (47.90 k allocations: 2.362 MiB, 15.39% gc time)
Hyperplane{Float64}([1.0, 1.0], 1.0)
julia> @time Hyperplane(ones(2), 1.)  # normal runtime
0.000013 seconds (6 allocations: 288 bytes)
Hyperplane{Float64}([1.0, 1.0], 1.0)
julia> @time Hyperplane(zeros(2), 1.)  # illegal argument, triggers assertion
ERROR: AssertionError: a hyperplane needs a non-zero normal vector
Stacktrace:
[1] macro expansion at .julia/dev/LazySets/src/Utils/assertions.jl:22 [inlined]
[2] Hyperplane{Float64}(::Array{Float64,1}, ::Float64) at .julia/dev/LazySets/src/Sets/Hyperplane.jl:32
[3] Hyperplane(::Array{Float64,1}, ::Float64) at .julia/dev/LazySets/src/Sets/Hyperplane.jl:38
[4] top-level scope at …
```

#1699 - Add benchmark mode

---

src/ConcreteOperations/intersection.jl
test/unit_CartesianProduct.jl

Closes #1753.
Requires: ~~https://github.com/JuliaReach/LazySets.jl/pull/1752~~

#1753 - Concrete intersection of CPA and polyhedron without constraints

---

src/LazyOperations/CartesianProduct.jl
test/unit_CartesianProduct.jl

Closes #1729.
```julia
N = Float64
n = 100
cpa = CartesianProductArray([BallInf(zeros(N, 1), N(1)) for _ in 1:n])
dd = zeros(N, n); dd[1] = N(1); dd[3] = N(1)
ds = sparsevec([1, 3], N[1, 1], n)
@btime ρ(dd, cpa)
4.046 μs (101 allocations: 9.39 KiB)
@btime ρ(ds, cpa)  # master
8.558 μs (301 allocations: 18.83 KiB)
@btime ρ(ds, cpa)  # this branch
296.284 ns (9 allocations: 656 bytes)
```
Notice that the old implementation was even considerably slower for sparse vectors than for dense vectors due to many allocations of new small sparse vectors.

#1729 - Faster support function/vector of CartesianProductArray and sparse direction

---

docs/src/lib/interfaces.md
src/Interfaces/AbstractHPolygon.jl
src/Interfaces/AbstractPolyhedron_functions.jl
src/Interfaces/AbstractPolytope.jl
src/Sets/HPolytope.jl
src/Sets/HalfSpace.jl
src/Sets/Hyperplane.jl
src/Sets/Line.jl
test/unit_Polytope.jl

Closes #1500.
CC @ueliwechsler

#1500 - Option to apply linear_map in H-rep without invertibility check

---

docs/src/lib/representations.md
src/Approximations/overapproximate.jl
src/Sets/Zonotope.jl

#755 - Refactor Zonotopes' reduce_order

---

docs/src/lib/operations.md
src/Interfaces/LazySet.jl
src/LazyOperations/Bloating.jl
src/LazySets.jl
src/Utils/helper_functions.jl
test/runtests.jl
test/unit_Bloating.jl

Closes #622.
```julia
using LazySets, Plots
pl = plot()
for (i, p) in [(1., 2.), (4., 1.), (7., Inf)]
B = BallInf([i, 0.], 1.);
X = Bloating(B, 0.1, p);
plot!(pl, B)
plot!(pl, X)
end
plot!(; ratio=1)
```

#622 - Bloating set operation

---

docs/src/lib/binary_functions.md
src/ConcreteOperations/difference.jl
test/unit_Hyperrectangle.jl

#1305 - Set difference between axis-aligned boxes

---

test/unit_BallInf.jl
test/unit_CartesianProduct.jl
test/unit_Intersection.jl
test/unit_LinearMap.jl
test/unit_MinkowskiSum.jl
test/unit_Polygon.jl
test/unit_Polyhedron.jl
test/unit_Polytope.jl
test/unit_ResetMap.jl
test/unit_UnionSet.jl
test/unit_Zonotope.jl
test/unit_box_approximation.jl
test/unit_overapproximate.jl
test/unit_template_directions.jl

These are the test changes outsourced from #1701. The main changes are to only use `Float64` where appropriate because other number types would be converted by the LP solver. This also removes the warnings in the tests.

Fix polyhedra tests

---

test/runtests.jl

Currently there are no problems because we also load `Polyhedra` in the tests by default and resolve the conflict there.

Fix namespace conflict with Plots

---

src/Approximations/overapproximate.jl
test/unit_overapproximate.jl

This PR fixes the conversion to a zonotope for the following vector of taylor models:
```julia
2-element Array{TaylorModels.TaylorModel1{TaylorN{Float64},Float64},1}:
10.1 + 0.09999999999999964 x₁ + [0, 0]
0.0 + [0, 0]
```
In principle one can't construct a taylor model with 0 order, but for whatever reason the zero polynomial, after normalization, `Q`, in [this part of the code](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Approximations/overapproximate.jl#L1027), had zero order and in consequence `linear_polynomial` was failing because the implementation in Taylorseries uses `a[1]`,  but since they start at `a[0]` the term doesn't exist, see [here](https://github.com/JuliaDiff/TaylorSeries.jl/blob/53a865275d678280bfc002548bff0d7a18c99dbd/src/auxiliary.jl#L315).
cc: @lbenet

Fix case 0 for linear term in taylor model

---

src/Approximations/decompositions.jl
src/Approximations/iterative_refinement.jl
src/Approximations/overapproximate.jl
src/Interfaces/AbstractHyperrectangle.jl
src/LazyOperations/CartesianProduct.jl
src/LazyOperations/ResetMap.jl
src/LazyOperations/Translation.jl
src/Sets/Ball1.jl
src/Sets/HPolytope.jl
src/convert.jl

See #1802.
This PR addresses some but not all the problems. I'll leave the others, which are mainly related to HPolygon, to another PR.

#1802 - Concretely type linear constraint arrays

---

docs/src/lib/interfaces.md
src/Approximations/init.jl
src/Approximations/init_TaylorModels.jl
src/Initialization/init_Expokit.jl
src/Initialization/init_Makie.jl
src/Initialization/init_Polyhedra.jl
src/LazyOperations/ExponentialMap.jl
src/LazySets.jl
src/Plotting/mesh.jl
src/Sets/VPolytope.jl
src/Utils/samples.jl
src/init.jl

Closes #1446.
I defined new methods outside the `Requires` wrappers for better error printing. Alternatively, we could sometimes remove the `Requires` wrappers altogether and instead use our `require` helper function.
The only cases I did not add are functions that are clearly package specific (`default_cddlib_backend`, `default_polyhedra_backend`, `default_lp_solver_polyhedra`, and `polyhedron`).

#1446 - Print error message if required external package is missing

---

docs/src/lib/interfaces.md
docs/src/lib/representations.md
src/Interfaces/AbstractCentrallySymmetric.jl
src/Interfaces/AbstractPolyhedron_functions.jl
src/Interfaces/AbstractPolytope.jl
src/Sets/EmptySet.jl
src/Sets/HPolyhedron.jl
test/unit_Ball1.jl
test/unit_Ball2.jl
test/unit_BallInf.jl
test/unit_Ballp.jl
test/unit_Ellipsoid.jl
test/unit_EmptySet.jl
test/unit_Hyperrectangle.jl
test/unit_Interval.jl
test/unit_LineSegment.jl
test/unit_Polygon.jl
test/unit_Polytope.jl
test/unit_Singleton.jl
test/unit_SymmetricIntervalHull.jl
test/unit_Universe.jl
test/unit_ZeroSet.jl
test/unit_Zonotope.jl

#1125 - isuniversal methods for bounded sets

---

src/Approximations/overapproximate.jl

Closes #1855.
This PR implements a restriction on the argument type such that epsilon-close overapproximation of a set which is not guaranteed to be convex by its type is forbidden.

#1855 - Restrict epsilon-close approx to convex sets

---

docs/src/lib/sets/Ball1.md
src/Sets/Ball1.jl
test/unit_Ball1.jl

This PR may seem a bit strange. I am not particularly interested in `Ball1`. My original plan was to *quickly* go through all files and do some clean-ups. But I got lost in the details and only made it through the first file :disappointed:
Here are the commit descriptions. There is a **breaking change** in the third commit that is debatable.
1. several changes:
* removed output-type parameters
* "faster" `vertices_list` implementation by removing `push!`es and look-ups of vector entries (the "faster" is in quotes because the benchmark below shows that there is no dfference for large inputs and even a minor slowdown for 2D inputs...)
* added assertion message
* used `enumerate`
* removed redundant `LazySets.` prefix
2. added fail-fast option to membership test (see small benchmark below; …

Revision of Ball1.jl

---

src/Plotting/plot_recipes.jl
test/unit_plot.jl

Closes #576.
Things to be addressed in follow-up issues:
* Add a macro for common code in all plot recipes for extending the plot limits (difficult because that code itself is already inside a macro) ([link to discussion](https://github.com/JuliaReach/LazySets.jl/pull/1910#discussion_r365823637), #1917).
* Support plotting of nested `Intersection`s of unbounded sets ([link to comment](https://github.com/JuliaReach/LazySets.jl/pull/1910#issuecomment-574183717), #1913).

#576 - Plots for unbounded sets

---

src/Plotting/plot_recipes.jl

Closes #1318.
This is a simple solution. I could not find out how to draw the convex parts in the same color without fixing a global color. The parts will have the same color when passed explicitly, though:
```julia
julia> using LazySets, Plots
julia> cup = UnionSet(rand(BallInf), rand(Ball2));
julia> cup2 = UnionSetArray([rand(Ball1), rand(LineSegment), rand(Singleton)]);
julia> plot(cup)
julia> plot!(cup2)
julia> plot(cup, color=:red)
julia> plot!(cup2, color=:blue)
```

#1318 - Plot recipe for set union

---

docs/src/lib/conversion.md
src/Approximations/overapproximate.jl
src/convert.jl

The first commit generalizes a `convert` method from `AbstractHyperrectangle` to `AbstractZonotope` (which presumably we did not have when we originally wrote the method).
The second commit makes this `convert` method available in `overapproximate`. This would be redundant if we had #1229 already.

convert/overapproximate for zonotopic LinearMap

---

docs/src/lib/interfaces.md
src/Interfaces/LazySet.jl
test/unit_ZeroSet.jl

This implements the idea(s) from [here](https://discourse.julialang.org/t/extract-type-name-only-from-parametric-type/14188).

Add basetype function

---

src/Approximations/decompositions.jl
test/unit_decompose.jl

Closes #1726.
We use dispatch to choose the projection algorithm. I first thought about creating a dummy type for this purpose but I think passing `nothing` is acceptable since the concrete projection should actually be the standard.

#1726 - Concrete decomposition using linear_map

---

src/Approximations/decompositions.jl

See #1209 and #1207.
The projection of a half-space is simple and I added a proof idea in the documentation.
For the projection of a polyhedron I was too fast here: it is more complicated than the projection of each half-space individually. So I reverted those changes. Nevertheless, we can take the generalization of the code to arbitrary polyhedra. This gives us a naive but free projection algorithm.

Concrete projection of polyhedral sets

---

src/Approximations/overapproximate.jl
src/LazyOperations/Intersection.jl

Since about two weeks I get these warnings when using optional packages via `Requires` (but only sometimes, so this seems to be nondeterministic):
```julia
julia> using Optim
┌ Warning: Replacing docs for `LazySets._line_search :: Tuple{Any,Any,Union{HalfSpace, Hyperplane, Line}}` in module `LazySets`
└ @ Base.Docs docs/Docs.jl:223
julia> using TaylorModels
┌ Warning: Replacing docs for `LazySets.Approximations.overapproximate :: Union{Tuple{S}, Tuple{T}, Tuple{Array{TaylorModel1{T,S},1},Type{Zonotope}}} where S where T` in module `LazySets.Approximations`
└ @ Base.Docs docs/Docs.jl:223
┌ Warning: Replacing docs for `LazySets.Approximations.overapproximate :: Union{Tuple{S}, Tuple{T}, Tuple{N}, Tuple{Array{TaylorModelN{N,T,S},1},Type{Zonotope}}} where S where T where …
```

Fix warning with Optim

---

src/Approximations/overapproximate.jl
src/convert.jl
test/unit_overapproximate.jl

Closes #1638.
The first commit is only related but it makes the `convert` faster.
```julia
julia> @btime convert(Interval, rand(Hyperrectangle, dim=1));  # master
265.718 ns (7 allocations: 608 bytes)
julia> @btime convert(Interval, rand(Hyperrectangle, dim=1));  # this branch
225.956 ns (6 allocations: 512 bytes)
```

#1638 - Efficient way to obtain precise Interval bounds in 1D

---

src/Sets/VPolygon.jl
test/unit_Polygon.jl

Closes #1987.
Remains:
---
One can now do:
```julia
julia> using Revise, LazySets, StaticArrays
[ Info: Recompiling stale cache file /home/mforets/.julia/compiled/v1.2/LazySets/NjrGc.ji for LazySets [b4f0291d-fe17-52bc-9479-3d1a343d9043]
julia> S = @SMatrix(rand(2, 5))
2×5 SArray{Tuple{2,5},Float64,2,10} with indices SOneTo(2)×SOneTo(5):
0.102972  0.988928  0.607964  0.734651  0.684164
0.58481   0.228841  0.959816  0.586697  0.976767
julia> VPolygon(S)
VPolygon{Float64,SArray{Tuple{2},Float64,1,2}}(SArray{Tuple{2},Float64,1,2}[[0.10297164611362897, 0.5848102125715933], [0.9889278626351026, 0.22884117625522804]
, [0.6841638744333696, 0.9767668061708363], [0.6079638683572919, 0.9598158901016935]])
```

#1987 - VPolygon constructor from matrix columns

---

docs/src/lib/utils.md
src/Interfaces/AbstractPolygon.jl

The version of directions comparison using quadrants is both faster and more general than the version using `jump2pi`. For these reasons, we could remove the implementation altogether.
```julia
julia> p = rand(HPolygon);
julia> d = rand(2);
julia> @btime σ($d, $p); # master
737.704 ns (12 allocations: 688 bytes)
julia> @btime σ($d, $p); # this branch
632.355 ns (12 allocations: 688 bytes)
```

Use faster 2d directions algorithm by default

---

src/Interfaces/AbstractHyperrectangle.jl
src/Interfaces/AbstractZonotope.jl
src/Sets/LineSegment.jl

Closes #1911.
```julia
julia> @btime genmat(rand(Interval))
423.462 ns (7 allocations: 464 bytes)
julia> @btime genmat(rand(BallInf, dim=100))
48.197 μs (315 allocations: 98.44 KiB)
julia> @btime genmat(rand(Interval))
175.353 ns (4 allocations: 272 bytes)
julia> @btime genmat(rand(BallInf, dim=100));
21.260 μs (7 allocations: 80.02 KiB)
```
```julia
julia> @code_warntype genmat(rand(Interval))
Variables
#self#::Core.Compiler.Const(LazySets.genmat, false)
H::Interval{Float64,IntervalArithmetic.Interval{Float64}}
Body::Array{Float64,2}
1 ─ %1 = LazySets.genmat_fallback(H)::Array{Float64,2}
└──      return %1
```

#1911 - Type instability in genmat_fallback

---

src/Sets/Hyperrectangle.jl
test/unit_Hyperrectangle.jl

Make bounds check in hyperrectangle constructor optional

---

docs/src/lib/binary_functions.md
src/ConcreteOperations/minkowski_sum.jl
test/unit_Interval.jl

#2019 - Special case concrete Minkowski sum for intervals

---

src/Sets/VPolytope.jl
test/unit_Polytope.jl

#2004 - Generalize vertices type in VPolytope

---

src/Sets/Ellipsoid.jl

#2006 - Add type parameters to Ellipsoid

---

src/Approximations/overapproximate.jl
test/unit_overapproximate.jl

#1940 - Overapproximate a lazy affine map with a hyperrectangle 

---

docs/src/lib/conversion.md
docs/src/man/reach_zonotopes_hybrid.md
src/Sets/Zonotope.jl
src/convert.jl

#1900 - Add type parameters for zonotope

---

docs/src/lib/conversion.md
src/Approximations/Approximations.jl
src/Approximations/decompositions.jl
src/Approximations/overapproximate.jl
src/ConcreteOperations/intersection.jl
src/ConcreteOperations/isdisjoint.jl
src/ConcreteOperations/minkowski_sum.jl
src/Interfaces/AbstractHPolygon.jl
src/Interfaces/AbstractPolyhedron_functions.jl
src/LazyOperations/IntersectionArray.jl
src/LazyOperations/Rectification.jl
src/Sets/HPolygon.jl
src/Sets/HPolygonOpt.jl
src/Sets/HPolyhedron.jl
src/Sets/HPolytope.jl
src/Sets/HalfSpace.jl
src/Sets/VPolytope.jl
src/convert.jl
test/runtests.jl
test/unit_Polygon.jl
test/unit_Polyhedron.jl
test/unit_Polytope.jl

Closes #1851.
Closes #2035.
Closes #2036.
Closes #1771.
Closes #1802.

#1851 - Add type parameter of linear constraints

---

src/LazyOperations/LinearMap.jl
test/unit_LinearMap.jl

Closes #2070.
I left the type annotation `map::Real` as in the rest of the file, although i don't know why we don't allow any scalar-like object ( = `Number`) in the `LinearMap` type. .. (it is probably for historical reasons :) )

#2070 - Scaling from the right

---

test/unit_Polyhedron.jl

`an_element` was not tested.
The test fails for an `HPolytope` because the polyhedron is unbounded in the direction `[1, 0]` that we use in the implementation.
Also note that `an_element` returns `[Inf, Inf]`.
```julia
julia> N = Float64; P = HPolyhedron([HalfSpace(N[3//50, -4//10], N(1)),
HalfSpace(N[-1//50, 1//10], N(-1))]);
julia> an_element(P)
2-element Array{Float64,1}:
Inf
Inf
```

Test for HPolyhedron's an_element method

---

docs/src/lib/approximations.md
src/Approximations/Approximations.jl
src/Approximations/overapproximate.jl
src/Approximations/template_directions.jl
test/unit_Zonotope.jl
test/unit_template_directions.jl

Closes #2087.
Closes #2051.
This change is breaking.
---
Remains:

#2087 - Updates to template directions

---

src/ConcreteOperations/intersection.jl

fixes #697
Really, the change is just checking if the lines intersect first. I'm not sure if that's what was desired, but I'm willing to amend as desired.
In case you care about my tests/benchmarks:
```julia
julia> function simplerIntersect(L1::Line{N},L2::Line{N}) where {N<:Real}
if ((L1.a[1]==0 && L2.a[1] == 0) || (L1.a[2]==0 && L2.a[2] == 0) || (L1.a[1]*L2.a[2]) == (L2.a[1]*L1.a[2]) )
if (L1.b == L2.b)
return L1
else
return EmptySet{N}(dim(L1))
end
else
b = [L1.b, L2.b]
a = [transpose(L1.a); transpose(L2.a)]
return Singleton(a \ b)
end
end
simplerIntersect (generic function with 1 method)
julia> a = Line([1,1], 1)
Line{Int64,Array{Int64,1}}([1, 1], 1)
julia> b = Line([-1,1], 1)
Line{Int64,Array{Int64,1}}([-1, 1], 1)
julia> # obvious cross
@assert intersection(a,b) …
```

Simpler Intersection for Lines

---

src/ConcreteOperations/intersection.jl

Fixes #262 
Draft due to an error I don't understand when testing:
```julia
function i1(a::LineSegment, b::Line)
ap = Line(a.p, a.q)
m = intersection(ap, b)
if m == b
return a
elseif typeof(m) <: Singleton && m.element ∈ a
return m
else
return EmptySet(max(dim(a), dim(b)))
end
end
function i1(a::Line, b::LineSegment)
return i1(b,a)
end
s1 = LineSegment([-5,-5], [5,5])
t = Line(s1.p, s1.q)
l1 = Line([0,0], [5,5])
l2 = Line([10,10], [6,0])
l3 = Line([0,1], [5,6])
l4 = Line([5,-5], [-5,5])
i1(s1, l1)
i1(s1, l2)
i1(s1, l3)
i1(s1, l4)
```
throws 
```julia
julia> i1(s1, l4)
ERROR: MethodError: no method matching iterate(::LineSegment{Int64,Array{Int64,1}})
Closest candidates are:
iterate(::Core.SimpleVector) at essentials.jl:603
iterate(::Core.SimpleVector, ::Any) at essentials.jl:603 …
```

intersection between line and line segment

---

src/Interfaces/AbstractZonotope.jl
test/unit_Zonotope.jl

This fixes a regression uncovered in https://github.com/JuliaReach/MathematicalPredicates.jl/pull/19.

Generalize 1D zonotope constraints_list

---

docs/src/lib/interfaces.md
src/Interfaces/AbstractCentrallySymmetricPolytope.jl
test/unit_BallInf.jl
test/unit_interfaces.jl

Background: `center(rand(Ball2), 1)` works but `center(rand(BallInf), 1)` did not work - scandalous!

Inherit all functions for AbstractCentrallySymmetricPolytope

---

src/Approximations/box_approximations.jl

Closes #1745.
As discussed in the issue, this change does not always improve performance. I am fine with doing the change because currently we do not dispatch on `SingleEntryVector`, so eventually there may be a speedup.
Below are some experiments with:
* `Ball1` and `Ball2` (slower)
* `Zonotope` (equal)
* `VPolytope` (created with `Ps = [rand(VPolytope, dim=n) for n in [1, 5, 10, 20]]`) and a `Translation` of a `Zonotope` (faster)
`master`:
```julia
julia> for n in [1, 10, 100, 1000]
X = rand(Ball1, dim=n)
@btime box_approximation($X)
end
296.956 ns (8 allocations: 704 bytes)
2.867 μs (44 allocations: 6.75 KiB)
94.638 μs (404 allocations: 352.66 KiB)
9.050 ms (4004 allocations: 31.03 MiB)
julia> for n in [1, 10, 100, 1000]
X = rand(Ball2, dim=n)
@btime box_approximation($X)
end
235.835 …
```

#1745 - Use SingleEntryVector in box overapproximation

---

src/Arrays/Arrays.jl
src/Arrays/vector_operations.jl
src/Interfaces/AbstractHPolygon.jl
test/unit_Polygon.jl

Closes #2169.
```julia
julia> P = HPolygon([
HalfSpace([1.3877787807814457e-17, 0.0], -7.27918967693285e-18)
HalfSpace([3.642919299551295e-17, 2.7755575615628914e-17], 3.194076233118193e-17)
HalfSpace([-6.938893903907228e-17, 0.03196481037863655], 0.1022675780516848)
HalfSpace([-0.022382796523655775, -3.469446951953614e-18], 0.05268494728581621)
HalfSpace([-8.673617379884035e-19, -0.01331598581298936], 0.020336411343083463)
HalfSpace([0.01620615792275367, -2.949029909160572e-17], 0.03845370605895632)
]);
```
In `master` this works but redundant constraints are not removed:
```julia
julia> P.constraints
6-element Array{HalfSpace{Float64,Array{Float64,1}},1}:
HalfSpace{Float64,Array{Float64,1}}([3.642919299551295e-17, 2.7755575615628914e-17], 3.194076233118193e-17) …
```

Use approximate zero test in samedir and fix isredundant

---

src/Approximations/overapproximate.jl
test/unit_overapproximate.jl

#2154 - Compute the overapproximation of the convex hull array of zonotopes with a zonotope recursively

---

src/Sets/HalfSpace.jl

The function `is_tighter_same_dir_2D` is called from here:
https://github.com/JuliaReach/LazySets.jl/blob/d16f98bb4072debccd12b24b7dec784396f80364/src/Interfaces/AbstractHPolygon.jl#L309-L313
Recently (#2172) that code was made more robust wrt. floating-point precision. But the function `is_tighter_same_dir_2D` was forgotten.

Add floating-point tolerance to is_tighter_same_dir_2D

---

src/LazyOperations/CartesianProduct.jl
test/unit_CartesianProduct.jl

This allows to compute the linear map with a singular matrix of an unbounded polyhedral Cartesian product (and should often be faster in the bounded case).

Always use constraint representation in linear_map_cartesian_product

---

Project.toml
docs/Project.toml

For the record, there is a warning but that has been there before this PR as well:
```julia
Warning: invalid local link: unresolved path in lib/interfaces.md
│   link.text =
│    1-element Array{Any,1}:
│     Markdown.Code("", "is_right_turn")
│   link.url = "../utils/#LazySets.Arrays.is_right_turn"
```

Bump Documenter version

---

docs/src/lib/binary_functions.md
src/ConcreteOperations/convex_hull.jl
test/unit_convex_hull.jl

#941 - Add convex_hull of an array of polytopes

---

docs/src/assets/juliareach.css

currently the docs don't fit the entire width of the page (https://juliareach.github.io/LazySets.jl/dev/). this uses an updated css file (same as in ReachabilityAnalysis).

update custom css

---

docs/src/lib/binary_functions.md
src/ConcreteOperations/issubset.jl
test/unit_CartesianProduct.jl

Closes #1227.
Additionally this PR adds a subset check between `CartesianProductArray`s of different block structure by using the fallback implementation.
~Tests were already present.~
```julia
julia> @time X ⊆ Y
0.000024 seconds (111 allocations: 7.453 KiB)
false
julia> @time ⊆(X, Y, true)
0.000032 seconds (151 allocations: 9.891 KiB)
(false,   [1]  =  -0.989371
[2]  =  0.890032
[3]  =  1.15984
[4]  =  2.03698)
julia> @time X ⊆ Y
0.000003 seconds
false
julia> @time ⊆(X, Y, true)
0.000005 seconds (4 allocations: 272 bytes)
(false, [-0.9893707748634932, 0.6090025573953656, 0.6279955152649557, 0.38677706906864234])
julia> @time X ⊆ Y
0.000025 seconds (129 allocations: 8.672 KiB)
false
julia> @time ⊆(X, Y, true)
0.000030 seconds (163 allocations: 10.703 KiB)
(false,   [1]  =  -0.427312
[2] …
```

#1227 - Efficient subset check between CartesianProducts

---

src/Approximations/decompositions.jl
test/unit_Polygon.jl
test/unit_Polytope.jl

follow up of https://github.com/JuliaReach/LazySets.jl/pull/2284, adds some dimensional checks and (runtime) dispatch. the drawback of this approach is the type-instability, but it has all other benefits such as specialized methods on the returned type.

update vpolytope projection

---

docs/src/lib/sets/Zonotope.md
src/Sets/Zonotope.jl
test/unit_Zonotope.jl

#912 - Quadratic map of a zonotope

---

src/Interfaces/LazySet.jl
test/unit_BallInf.jl

Closes #2280.
we can add a test with an algorithm choice for `linear_map` which is not the default choice.

#2280 - Pass kwarg to affine_map

---

src/Initialization/init_ModelingToolkit.jl
src/Sets/HPolytope.jl
src/Sets/HalfSpace.jl
src/Sets/Hyperplane.jl
test/unit_Hyperplane.jl

The PR contains two updates:
- add macro for `HPolytope`
- in master one has to extract the tuple argument
```julia
vars, = @variables x[1:2]
HalfSpace(x[1] <= 1, x)
```
with this branch we can do
```julia
vars = @variables x[1:2]
HalfSpace(x[1] <= 1, x)
```

Add HPolytope with MT + let macro work on tuples

---

docs/src/lib/approximations.md
docs/src/lib/sets/Zonotope.md
src/Approximations/overapproximate.jl
test/unit_overapproximate.jl

#2277 - Overapproximate a polytope with a zonotope using cartesian decomposition

---

test/unit_HalfSpace.jl
test/unit_Hyperplane.jl
test/unit_Intersection.jl
test/unit_Polyhedron.jl
test/unit_comparisons.jl
test/unit_samples.jl
test/unit_util.jl

Fix global-variable issues in tests

---

docs/src/lib/sets/Interval.md
src/Sets/Interval.jl
test/unit_Interval.jl

I found it annoying that `split(rand(Interval), 2)` does not work and `split(rand(Interval), [2])` returns a list of `Hyperrectangle`s.
The first commit brings a faster implementation of `diameter` that I first thought I would use but then I decided to just use `IntervalArithmetic.mince(·)`.
x-ref: #2082

Better diameter and split methods for Interval

---

src/Interfaces/AbstractZonotope.jl

The change reduces one array allocation.
```julia
Z = rand(Zonotope, dim=4, num_generators=20)
d = rand(4);
@btime _ρ($d, $Z)  # this branch
@btime __ρ($d, $Z) # master
135.111 ns (1 allocation: 240 bytes)
164.918 ns (2 allocations: 480 bytes)
26.098671846834662
```

Faster support function for zonotopic sets

---

src/Sets/LineSegment.jl
test/unit_LineSegment.jl

Closes https://github.com/JuliaReach/LazySets.jl/issues/1485.
The test was inspired from https://discourse.julialang.org/t/less-than-approx-equals/45436. Note that without the change in this PR, the membership test fails irrespective of the LazySets tolerances.

Fix membership test for line segments

---

docs/src/lib/binary_functions.md
docs/src/lib/sets/EmptySet.md
src/ConcreteOperations/intersection.jl
src/Sets/EmptySet.jl
src/Sets/VPolygon.jl
test/unit_Polygon.jl
test/unit_Polytope.jl

This is a standard algorithm, see https://en.wikipedia.org/wiki/Sutherland%E2%80%93Hodgman_algorithm. The code follows that of http://www.rosettacode.org/wiki/Sutherland-Hodgman_polygon_clipping#Julia.
Related to https://github.com/JuliaReach/LazySets.jl/issues/698.

Add Sutherland–Hodgman VPolygon intersection algorithm

---

src/Interfaces/AbstractHyperrectangle.jl

Closes #1983.
Closes #2092.
In relation to an earlier attempt (https://github.com/JuliaReach/LazySets.jl/pull/2095), here `simlar -> copyto!` prevents from having to write specialized code for static arrays, essentially because `copy` of an SArray returns an SArray, while `similar` of an SArray returns a (mutable) MArray.
Moreover, with `vlist = Vector{typeof(c)}(undef, m)` the type of the vectors is the same as the center of the input.
I've tested that it works fine with usual vectors (no changes), with static vectors and with sparse vectors. Examples:
```julia
julia> using Revise, LazySets, StaticArrays, BenchmarkTools, Test
julia> Hyperrectangle(SA[1, 2.], SA[0.5, 0.5])
Hyperrectangle{Float64,SArray{Tuple{2},Float64,1,2},SArray{Tuple{2},Float64,1,2}}([1.0, 2.0], [0.5, 0.5])
julia> …
```

#1983 - Fix type of hyperrectangle vertices

---

src/Initialization/init_StaticArrays.jl
src/Interfaces/AbstractZonotope.jl
src/Sets/Zonotope.jl

This PR makes two changes:
1) speedup computation of vertices of a 2d zonotope of order 1, it goes from ~2us (master) to ~500ns (this branch). (*)
2) fix the `_vertices_list_iterative` such that the type of the vertices corresponds to the type of the center of the zonotope. before, it was hardcoding `Vector{N}`, which is a bad idea that prevents from obtaining an SArray output if the input is SArray.
(*) Using static arrays, runs in ~60ns.
cc @yupbank

Special case for order 1 zonotopes

---

src/Initialization/init_StaticArrays.jl
src/convert.jl
test/unit_BallInf.jl

This PR improves the runtime performance of abstract hyperrectangle -> zonotope convert methods, in particular for static arrays in two dimensions. These changes are related to https://github.com/JuliaReach/LazySets.jl/issues/2248, though it doesn't yet fix the underlying issue there (which should be fixed in the fallback), i'll address them in a separate PR.
Reference notebook: https://nbviewer.jupyter.org/github/mforets/escritoire/blob/master/2020/Week42/LazySets%232248.ipynb
The performance improvement in 2D is ~2.5x with less allocs. But more importantly, if the input hyperrectangular set has static array vectors, now the output has that type too.
For applications that want the maximum performance (and that you don't have/care about hyperrectangles with flat sides), I added the …

Improve AbstractHyperrectangular -> Zonotope 2D convert methods for static arrays

---

src/Approximations/overapproximate.jl
test/unit_box_approximation.jl

Closes #1769.
In 2D this implementation is less efficient for a moderate number of vertices due to the additional conversion from `low`/`high` in the `Hyperrectangle` constructor. I guess in higher dimensions it will be more useful. Should I remove the dispatch for `VPolygon` or add an `invoke` of the old method based on the number of vertices?
```julia
julia> P1 = VPolytope([[0.0, 0.0], [2.0, 1.0], [1.0, 2.0]]);
julia> P2 = VPolytope([rand(2) for _ in 1:100]);
julia> P3 = VPolytope([rand(2) for _ in 1:1000]);
julia> @time box_approximation(P1)
[0.0, 0.0][2.0, 2.0]
0.000008 seconds (5 allocations: 416 bytes)
Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}([1.0, 1.0], [1.0, 1.0])
julia> @time box_approximation(P2)
[0.001830275380493962, 0.005165832293896333][0.9791389830947983, …
```

#1769 - Faster box approximation of VPolytope

---

docs/src/lib/conversion.md
src/Initialization/init_StaticArrays.jl
src/Sets/BallInf.jl
src/Sets/Hyperrectangle.jl
src/convert.jl
test/unit_BallInf.jl
test/unit_Hyperrectangle.jl

Closes #2248.
Closes #1879.
---
This PR incorporates the change from https://github.com/JuliaReach/LazySets.jl/pull/2251.
Moreover, i added static versions for `BallInf` generators and `Hyperrectangle` generators. For the latter, i couldn't find a efficient implementation which considers the (runtime) behavior of possibly zero radius components. So i kept both versions. The reference notebook is again https://nbviewer.jupyter.org/github/mforets/escritoire/blob/master/2020/Week42/LazySets%232248.ipynb

Generalize AbstractHyperrectangle -> Zonotope conversion

---

src/Sets/Universe.jl
test/unit_Universe.jl

In `master` this would return an `HPolyhedron` with no constraints, which does not have an associated dimension.

linear_map_inverse for Universe

---

src/Sets/Zonotope.jl

This is a minor improvement.
```julia
julia> p = 4
julia> @btime for ξi in Iterators.product([[1, -1] for i = 1:$p]...)  # master
collect(ξi)
end
3.174 μs (71 allocations: 6.08 KiB)
julia> @btime for ξi in Iterators.product([(1, -1) for i = 1:$p]...)  # this branch
collect(ξi)
end
2.996 μs (71 allocations: 5.92 KiB)
julia> p = 10
julia> @btime for ξi in Iterators.product([[1, -1] for i = 1:$p]...)  # master
collect(ξi)
end
202.285 μs (4109 allocations: 689.28 KiB)
julia> @btime for ξi in Iterators.product([(1, -1) for i = 1:$p]...)  # this branch
collect(ξi)
end
201.645 μs (4109 allocations: 688.89 KiB)
```

Use tuple instead of vector

---

docs/src/lib/binary_functions.md
src/ConcreteOperations/minkowski_sum.jl
test/unit_Singleton.jl

#2417 - Specialize concrete minkowski sum for singletons

---

src/Approximations/box_approximation.jl
src/Sets/Ball2.jl
test/unit_overapproximate.jl

Closes #589.
```julia
julia> E = rand(Ellipsoid);
julia> B = rand(Ball2);
julia> @btime box_approximation($E)
74.695 ns (1 allocation: 96 bytes)
Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}([0.0, 0.0], [1.4142135623730951, 1.4142135623730951])
julia> @btime box_approximation($B)
52.039 ns (1 allocation: 96 bytes)
Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}([-1.3320384136380545, -0.5810181282958253], [0.3527491162460336, 0.3527491162460336])
julia> @btime box_approximation($E)
126.373 ns (3 allocations: 224 bytes)
Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}([0.0, 0.0], [1.4142135623730951, 1.4142135623730951])
julia> @btime box_approximation($B)
289.367 ns (7 allocations: 608 bytes)
Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}([-1.332038 …
```

#589 - More efficient box approximation of specific set types

---

src/Sets/Interval.jl
test/unit_Interval.jl

Closes #2453.
Notes:
- The method for `IntervalBox` can certainly be improved, but this is better than nothing (we can improve it as a follow-up PR).
- The method for `Interval` creates static arrays because that's consistent with the implementation of the interval box type (note that the conversion from `IntervalBox` to `Hyperrectangle` returns SArrays already).

#2453 - Vertices list of IntervalArithmetic types

---

test/unit_ResetMap.jl

These tests seemed to be missing, see https://codecov.io/github/JuliaReach/LazySets.jl?branch=master . Although the latest codecov report seems to be 3 months old (!). It would be nice if we can re-trigger it somehow. Maybe it's related to [this](https://github.com/JuliaReach/ReachabilityAnalysis.jl/issues/204); i didn't investigate further.

Add some tests for ResetMap

---

test/unit_Zonotope.jl

Closes https://github.com/JuliaReach/LazySets.jl/issues/2013.
This adds a new test as it is discussed in the linked issue.

Test for concrete projection of a zonotope

---

src/Interfaces/AbstractPolyhedron_functions.jl
src/Sets/Ball1.jl
src/Sets/Ball2.jl
src/Sets/BallInf.jl
src/Sets/Ballp.jl
src/Sets/EmptySet.jl
src/Sets/Universe.jl
test/unit_Ball1.jl
test/unit_Ball2.jl
test/unit_BallInf.jl
test/unit_Ballp.jl
test/unit_EmptySet.jl
test/unit_Hyperrectangle.jl
test/unit_Universe.jl

See #1209.
~Requires #2475.~
Concrete `project()` for:
* `Ball1`, `Ball2`, `BallInf`, `Ballp`
* `EmptySet`
* `Universe`

#1209 - Concrete projection of BallX, EmptySet, Universe

---

docs/src/lib/interfaces.md
docs/src/lib/lazy_operations/LinearMap.md
src/Interfaces/AbstractPolyhedron_functions.jl

This PR generalizes the concrete projection of polyhedra based on the idea of the constrained dimensions (#1213).
As a bonus it also removes the boundedness check of the `HPolytope` in the end.
If a constraint's constrained dimensions all get projected away, the constraint becomes redundant and we can just ignore it.
A 2D `Hyperrectangle` can be projected exactly to dimension 1 (`x`). This is still true if we consider the constraint representation. The constraints have the form `ax + 0y <= b` or `0x + ay <= b`. In the first case one can project away the redundant dimension `y`. In the second case one can drop the whole constraint. (Note that this is only correct because we assume that our half-spaces are feasible.)
- The implementation is more efficient for a class of cases; in particular …

Generalize special case for concrete projection of polyhedra

---

src/ConcreteOperations/isdisjoint.jl
test/unit_Zonotope.jl

This fixes a serious bug in #1269 (the result was inverted). The tests were also wrong :face_with_head_bandage:

Fix bug in isdisjoint of two zonotopic sets

---

src/Utils/samples.jl
test/unit_samples.jl

This PR adds a `DefaultUniform` struct and is set by default, this means the we can use `sample(X, m)` without having to load `Distributions` to sample using a uniform distribution, since that is already available in Julia Base.

Add default uniform sampler

---

docs/src/lib/interfaces.md
docs/src/lib/lazy_operations/LinearMap.md

This fixes the docs error that sometimes happens since #2475.
Don't ask me why
```julia
project(S::LazySet, ::AbstractVector{Int}, ::Type{var"#s27"} where var"#s27"<:LazySet, ::Int=dim(S))
```
works but
```julia
project(S::LazySet, ::AbstractVector{Int}, ::Type{T} where T<:LazySet, ::Int=dim(S))
```
does not...

Fix docs (project methods)

---

src/Interfaces/AbstractPolyhedron_functions.jl
src/Sets/HPolyhedron.jl

See https://github.com/JuliaReach/LazySets.jl/issues/2348.

Use promotion in HPolyhedron's support function

---

.travis.yml
docs/src/man/lazy_intersections.md
docs/src/man/reach_zonotopes_hybrid.md

Recently we breach the 30 minutes :face_with_head_bandage:

Increase timeout for docs build

---

src/LazyOperations/CartesianProduct.jl
test/unit_CartesianProduct.jl

#2521 - Concrete projection a hyperrectangular cartesian product

---

src/LazyOperations/CartesianProduct.jl
test/unit_CartesianProduct.jl

#2522 - Concrete projection of interval x zonotope

---

docs/src/lib/utils.md
src/Utils/samples.jl
test/unit_samples.jl

See https://github.com/JuliaReach/LazySets.jl/issues/2536#issuecomment-771679414.
Uniform sampling from a convex polytope turns out to be much more difficult (#2546).

Sampling from a convex polytope

---

src/ConcreteOperations/minkowski_sum.jl

In `master`:
```julia
julia> Z = minkowski_sum(X, Y)
ERROR: UndefVarError: default_polyhedra_backend_nd not defined
```
This branch:
```julia
julia> Z = minkowski_sum(X, Y)
ERROR: AssertionError: package 'Polyhedra' not loaded (it is required for executing `minkowski_sum`)
```
I am not 100% sure about the error message but I think it is better to have that.

Better error message in minkowski_sum of V-reps

---

src/ConcreteOperations/intersection.jl
test/unit_Polygon.jl

Closes #2187.
The problem (see #2187's OP) is that `intersection` of two `HPolygon`s is supposed to combine the constraints in a sorted order but it does not. This PR proposes a quick fix: sort them in the end.
Ultimately the code should be fixed, but since it is complicated and the issue has been open for several months, I think we should first fix the bug and then propose an efficient fix later.

#2187 - Sort constraints in HPolygon intersection

---

src/Interfaces/AbstractPolyhedron_functions.jl
src/Interfaces/AbstractZonotope.jl
src/Interfaces/LazySet.jl

Closes #2319.
The first commit fixes broken links.
The second commit removes broken links that I could not get to work after trying all kinds of things.

#2319 - Invalid local links in documentation

---

docs/src/lib/sets/HalfSpace.md
src/Sets/HalfSpace.jl
src/Sets/Hyperplane.jl
src/Sets/Line2D.jl
test/unit_HalfSpace.jl
test/unit_Hyperplane.jl
test/unit_Line2D.jl

#1209 - Concrete projection of Hyperplane & Line2D

---

src/Approximations/decompositions.jl
src/Approximations/template_directions.jl
src/Sets/ZeroSet.jl

Inspired by [this](https://docs.julialang.org/en/v1/manual/style-guide/#Do-not-write-x-f(x)).
```julia
julia> n = 1000;
julia> Z = ZeroSet(n); x = zeros(n);
julia> @btime $x ∈ $Z;
85.407 μs (1000 allocations: 15.63 KiB)  # master
754.619 ns (0 allocations: 0 bytes)  # this branch
julia> d = fill([1.0, 0, 0, 0], n);
julia> @btime LazySets.Approximations._isnormalized($d);
15.814 μs (1 allocation: 7.94 KiB)  # master
14.916 μs (0 allocations: 0 bytes)  # this branch
```

Revise usage of 'all'

---

docs/src/lib/interfaces.md
src/Interfaces/AbstractCentrallySymmetric.jl
src/Interfaces/AbstractPolytope.jl
src/Interfaces/LazySet.jl
src/LazyOperations/Complement.jl
src/Sets/EmptySet.jl
test/unit_Ball2.jl
test/unit_Complement.jl
test/unit_EmptySet.jl
test/unit_LazySet.jl
test/unit_Polyhedron.jl
test/unit_Polytope.jl

Closes #1926.
Closes #1979 (I copied the code for `isboundedtype(::Type{<:LazySet})` from there and extended it to the current code base).

#1926 - Add isboundedtype function

---

src/Approximations/overapproximate.jl
test/Approximations/overapproximate.jl

this is a fix to the fact that:
```julia
using TaylorSeries
x = set_variables("x", numvars=2, order=10)
2-element Array{TaylorN{Float64},1}:
1.0 x₁ + 𝒪(‖x‖¹¹)
1.0 x₂ + 𝒪(‖x‖¹¹)
p = (1 + x[1] - 2x[2])^2
1.0 + 2.0 x₁ - 4.0 x₂ + 1.0 x₁² - 4.0 x₁ x₂ + 4.0 x₂² + 𝒪(‖x‖¹¹)
p - constant_term(p) - linear_polynomial(p)
0.0 + 𝒪(‖x‖²)
```
which fails because the order of linear_polynomial is 1. hence we implement `_nonlinear_polynomial` that has the correct order. discussed on slack with @dpsanders

fix generator columns for the nonlinear terms in TM -> Zono conversion

---

src/Approximations/ballinf_approximation.jl
src/ConcreteOperations/issubset.jl
src/Interfaces/AbstractPolyhedron_functions.jl
src/LazyOperations/AffineMap.jl

See https://github.com/JuliaReach/LazySets.jl/issues/1837
The PRs updates the AffineMap docstring. Also removed "convex" in a few other places.

Update AffineMap docstring 

---

src/LazyOperations/Bloating.jl

See https://github.com/JuliaReach/LazySets.jl/issues/1837
The PRs updates the Bloating docstring.

update Bloating docstring

---

src/LazyOperations/CachedMinkowskiSumArray.jl

See #1837.
This file updates the Cached MinkowskiSumArray.
Unrelated: the struct `CachedPair` has an abstract field. We should change it to `Vector{N}` or add a new field.

update cached MSA docstrings

---

src/LazyOperations/ConvexHull.jl

See #1837.
This PR updates the `ConvexHull.jl` docstrings.

Update ConvexHull docstring

---

src/Plotting/plot_recipes.jl

Closes #2644.
I could not reproduce the problem with "simple" sets (not like the one in #2644).

#2644 - Fix _update_plot_limits! for empty inputs

---

docs/src/lib/interfaces.md
docs/src/man/reach_zonotopes.md
src/Plotting/plot_recipes.jl

Closes #2647.
- The `UnionSet` and `UnionSetArray` recipe now just plots a sequence of sets with the same options (in particular the same color and a single label).
- There was a plotting argument `fast` but using it was not comfortable, so I turned it into a keyword argument.
- I also changed the name of the `fast` argument to `same_recipe` because that describes the effect better. That it is faster is a nice side effect but less important.

#2647 - Revise plot recipe for UnionSet

---

docs/src/lib/sets/Star.md
src/Sets/Star.jl
src/convert.jl
test/Sets/Star.jl

#2646 - Add intersection between star set and halfspace

---

src/LazyOperations/UnionSetArray.jl
test/LazyOperations/UnionSet.jl

This PR brings a convenience function that we also have for other array set types.

Add empty constructor for UnionSetArray

---

src/LazyOperations/ConvexHullArray.jl

See #1837.
The second commit brings the following improvements:
- assertion
- membership for arbitrary `CHArray`s (the code was already general, so I just removed the type restriction)
- faster support function/vector
```julia
julia> @time ρ(d, X)  # master
0.000007 seconds (2 allocations: 176 bytes)
2.860035012482964
julia> @time ρ(d, X)  # this branch
0.000006 seconds (1 allocation: 16 bytes)
2.860035012482964
julia> @time σ(d, X)  # master
0.000010 seconds (11 allocations: 1.156 KiB)
2-element Vector{Float64}:
3.007942344104169
3.278858578896459
julia> @time σ(d, X)  # this branch
0.000006 seconds (10 allocations: 960 bytes)
2-element Vector{Float64}:
3.007942344104169
3.278858578896459
```

Updates for ConvexHullArray

---

src/LazyOperations/InverseLinearMap.jl

```julia
julia> X = InverseLinearMap(rand(2,2), rand(BallInf));
julia> @time vertices_list(X);  # master
0.000025 seconds (22 allocations: 2.094 KiB)
julia> @time vertices_list(X);  # this branch
0.000018 seconds (21 allocations: 2.078 KiB)
```
Also, I marked `InverseLinearMap` as solved in #1837 because there is no convexity assumption in that file.

Improve InverseLinearMap's vertices_list

---

src/LazyOperations/LinearMap.jl

See #1837.
I am not 100% sure whether the generalization of `σ`/`ρ` is correct. My intuitive argument is that a linear map preserves the general shape (it only rotates/resizes/stretches) and this should also hold for non-square matrices.

#1837 - Remove convexity requirement in LinearMap

---

src/LazyOperations/UnionSetArray.jl
test/LazyOperations/UnionSet.jl

See #1837.
- remove convexity assumption in docstrings
- fix `an_element` if the first sets are empty
- faster `ρ`
```julia
julia> d = rand(2);
julia> X = UnionSetArray([rand(BallInf) for _ in 1:10]);
julia> @time ρ(d, X)  # master
0.000006 seconds (2 allocations: 176 bytes)
1.4787628756277493
julia> @time ρ(d, X)  # this branch
0.000005 seconds (1 allocation: 16 bytes)
1.4787628756277493
```

#1837 - Updates for UnionSetArray

---

src/LazyOperations/SymmetricIntervalHull.jl

See #1837.
- remove convexity assumption in docstrings
- reorder some methods to keep them together
- faster `get_radius!`
```julia
julia> X = rand(Ball2);
julia> Y = SymmetricIntervalHull(X);
julia> @time LazySets.get_radius!(Y, 1, 2)  # master
0.000015 seconds (31 allocations: 2.484 KiB)
2.486354302955953
julia> @time LazySets.get_radius!(Y, 1, 2)  # this branch
0.000006 seconds (3 allocations: 208 bytes)
2.486354302955953
```

#1837 - Updates for SymmetricIntervalHull

---

src/LazyOperations/Rectification.jl

See #1837.
We convert 1D bounded sets to `Interval`s in the constructor. So we need to additionally check convexity now.

#1837 - Remove convexity requirement in Rectification

---

docs/src/lib/lazy_operations/MinkowskiSum.md
src/LazyOperations/CachedMinkowskiSumArray.jl
src/LazyOperations/MinkowskiSum.jl
src/LazyOperations/MinkowskiSumArray.jl

See #1837.
- remove convexity assumption in docstrings
- move helper function `σ_helper` and rename to `_σ_msum_array`
- faster `_σ_msum_array`
- generalize `vertices_list(::MinkowskiSum)` (there was nothing specific to the set arguments in the old method)
```julia
julia> d = rand(2);
julia> X = MinkowskiSumArray([rand(Ball2), rand(Ball1)]);
julia> @time σ(d, X)  # master
0.000013 seconds (6 allocations: 576 bytes)
2-element Vector{Float64}:
0.14808679137967445
-1.1446662574273074
julia> @time σ(d, X)  # this branch
0.000010 seconds (6 allocations: 416 bytes)
2-element Vector{Float64}:
0.14808679137967445
-1.1446662574273074
julia> Y = rand(Ball1) + rand(BallInf);
julia> vertices_list(Y)  # master
ERROR: MethodError: no method matching vertices_list(::MinkowskiSum{Float64, Ball1{Float64, …
```

#1837 - Updates for MinkowskiSum & MinkowskiSumArray

---

docs/src/lib/interfaces.md
src/Interfaces/AbstractZonotope.jl
src/Sets/Zonotope.jl
test/Sets/Zonotope.jl

Closes #1453.
- I added `remove_redundant_generators(::AbstractZonotope)` because otherwise the call might fail. All non-`Zonotope` subtypes do not store the generators and hence the implementation is just the identity.
- I pulled up the handling of the 1D case because that is always more efficient. I also removed the `view` there because it is slower than just using `sum`. And I outsourced that code to a helper function.
- In contrast to the proposal in https://github.com/JuliaReach/LazySets.jl/issues/1453#issuecomment-812109639 I just perform the same checks again on the reduced zonotope. If that is not correct, I can change it.
I did not know what test to add because I could not find an error. Here is an example where the output changes.
```julia
julia> Z = Zonotope(rand(2), [2. 3 1; 0 …
```

#1453 - Remove redundant generators in constraints_list

---

src/Sets/Zonotope.jl

Improvement for #2642: If only zero generators have been removed, the matrix has already been constructed.

More efficient remove_redundant_generators

---

src/Plotting/mesh.jl

Closes #2748.
This change breaks compatibility with older Makie versions. But I guess this is fine. We could automatically check for the version like [this](https://stackoverflow.com/a/68023115) but that would require to add `Pkg` as a dependency, which is odd.

#2748 - Remove Makie.AbstractPlotting

---

src/Sets/Interval.jl
test/Sets/Interval.jl

`master`:
```julia
julia> c = chebyshev_center(Interval(1.0, 2.0))
glp_simplex: unable to recover undefined or non-optimal solution
ERROR: MethodError: no method matching sethrep!(::Polyhedra.Interval{Float64, StaticArrays.SVector{1, Float64}, StaticArrays.Size{(1,)}}, ::Polyhedra.Intersection{Float64, StaticArrays.SVector{1, Float64}, StaticArrays.Size{(1,)}})
Closest candidates are:
sethrep!(::Any, ::Any, ::Any) at ~/.julia/packages/Polyhedra/ajeAR/src/defaultlibrary.jl:115
sethrep!(::DefaultPolyhedron, ::HRepresentation) at ~/.julia/packages/Polyhedra/ajeAR/src/defaultlibrary.jl:120
sethrep!(::DefaultPolyhedron, ::HRepresentation, ::Any) at ~/.julia/packages/Polyhedra/ajeAR/src/defaultlibrary.jl:120
```

Add chebyshev_center for Interval

---

src/Approximations/symmetric_interval_hull.jl
test/Approximations/symmetric_interval_hull.jl
test/runtests.jl

Closes #2782.
```julia
julia> S = rand(Singleton, dim=1000);
julia> @time symmetric_interval_hull(S);  # master
0.002510 seconds (5 allocations: 31.781 KiB)
julia> @time symmetric_interval_hull(S);  # this branch
0.000012 seconds (3 allocations: 15.906 KiB)
```
---
```julia
julia> @time symmetric_interval_hull(M*S);  # master
2.491252 seconds (2.01 k allocations: 15.534 MiB)
julia> @time symmetric_interval_hull(concretize(M*S));  # proposal from #2782
0.007192 seconds (7 allocations: 39.750 KiB)
julia> @time symmetric_interval_hull(M*S);  # this branch
0.000738 seconds (5 allocations: 23.875 KiB)
```
---
```julia
julia> @time symmetric_interval_hull(S+S);  # master
0.005102 seconds (6 allocations: 31.812 KiB)
julia> @time symmetric_interval_hull(concretize(S+S));  # idea from #2782 …
```

#2782 - Faster symmetric_interval_hull of singletons

---

src/Approximations/symmetric_interval_hull.jl
test/Approximations/symmetric_interval_hull.jl

Closes #2785.
```julia
julia> H = rand(Hyperrectangle, dim=1000);
julia> M = sprand(1000, 1000, 0.01);
julia> @time symmetric_interval_hull(M*H);  # master
29.072374 seconds (2.01 k allocations: 15.534 MiB, 0.04% gc time)
julia> @time symmetric_interval_hull(M*H);  # this branch
0.000179 seconds (11 allocations: 195.625 KiB)
julia> M = rand(1000, 1000);
julia> @time symmetric_interval_hull(M*H);  # master
2.494493 seconds (2.01 k allocations: 15.534 MiB)
julia> @time symmetric_interval_hull(M*H);  # this branch
0.009323 seconds (8 allocations: 7.661 MiB)
```

#2785 - Faster SIH of a linear map of a hyperrectangle

---

src/Utils/comparisons.jl

The first commit changes the tolerance to what `default_tolerance` returns (before we had a `ztol` of `Float64(10)*sqrt(eps(Float64))` for `Float64`, but `default_tolerance(Float64)` returned `sqrt(eps(Float64))`, which I think was not intended). (I kept the factor 10 because a test relied on it, but now this is done consistently in only one place.)
The second commit adds the convenience function `set_tolerance`, which can be used to set all three tolerances at once. When calling it only with the numeric type, it resets the values to the default.

Revise numeric tolerance

---

src/LazyOperations/Bloating.jl
src/LazyOperations/Translation.jl
src/Sets/BallInf.jl
test/LazyOperations/AffineMap.jl
test/LazyOperations/Bloating.jl
test/LazyOperations/Translation.jl
test/Sets/BallInf.jl

The idea is to, instead of adding, remove the support vector of the corresponding ball. It works except for `p == 1` and `p == Inf`, because for these two cases the support vector is not unique. But there is a canonical support vector that makes the idea work as well. For `p == Inf` I changed the implementation to return that instead because it was easy. For `p == 1` I kept the old implementation and instead excluded that norm in `Bloating`.
Commits:
1. Change the implementation of σ for `BallInf` to give correct results with `p == Inf`. That also required to generalize some tests.
1. Allow for nonpositive bloating, excluding `p == 1` because σ there does not return the canonical support vector.
Indeed `Bloating(Bloating(S, -ε, p), ε, p)` is the same as `S` for `p > 1` now.
---
The 1-norm …

Allow for nonpositive lazy bloating

---

Project.toml
src/Initialization/init_WriteVTK.jl
src/Plotting/paraview.jl
src/Sets/HPolyhedron.jl
src/convert.jl
src/init.jl

This PR adds support for writing LazySets types into VTK XML files with https://github.com/jipolanco/WriteVTK.jl 
That files can be visualized with https://www.paraview.org/

Add WriteVTK optional dep for visualization with Paraview

---

docs/src/lib/binary_functions.md
docs/src/lib/interfaces.md
docs/src/lib/sets/HalfSpace.md
docs/src/lib/sets/Hyperplane.md
src/ConcreteOperations/distance.jl
src/Interfaces/AbstractHyperrectangle.jl
src/Sets/HalfSpace.jl
src/Sets/Hyperplane.jl
test/Sets/HalfSpace.jl
test/Sets/Hyperplane.jl
test/Sets/Hyperrectangle.jl

~This is PR based on #2802.~
Commits:
1. Add `normalize` for `Hyperplane`.
2. Add `distance` for a point and a `HalfSpace`.
3. Add `distance` for a point and a `Hyperplane`.
4. Add `distance` for a point and an `AbstractHyperrectangle`.
5. Let `distance` between two sets where one set is an `AbstractSingleton` fall back to the point-set distance.

Add point-set distance methods

---

src/Sets/Hyperrectangle.jl
test/Sets/Hyperrectangle.jl

Closes #2811.
This could be generalized to `AbstractHyperrectangle` or `AbstractZonotope`, but it does the job..

#2811 - special case of genmat of sparse hyperrectangle

---

docs/src/lib/binary_functions.md
src/ConcreteOperations/cartesian_product.jl
src/Sets/HPolygon.jl
src/Sets/HPolygonOpt.jl
src/Sets/HPolyhedron.jl
src/Sets/HPolytope.jl
src/Sets/HalfSpace.jl
test/ConcreteOperations/cartesian_product.jl
test/LazyOperations/MinkowskiSum.jl

(The first commit is required but independent. I outsourced it to #2815.)
The Cartesian product in H-rep is simple, so I added it as a native method which is now the default. The old implementation via `Polyhedra` can be used with the new algorithm `"hrep_polyhedra"` (not sure about the name).

cartesian_product not requiring Polyhedra

---

src/Approximations/Approximations.jl
src/Approximations/init.jl
src/Approximations/init_Expokit.jl
src/Approximations/symmetric_interval_hull.jl
src/LazySets.jl
src/Utils/require.jl
src/init.jl
test/Approximations/symmetric_interval_hull.jl

Using `Expokit` in `Approximations` required a small refactoring.
```julia
using LazySets, SparseArrays, Expokit, Test
for n in [1, 10, 100, 200]
A = sparse(rand(n, n) .- rand(n, n));
δ = 0.1;
M = SparseMatrixExp(A * δ);
println("n = $n\nSingleton")
X = rand(Singleton, dim=n);
EX = ExponentialMap(M, X);
@time SX = symmetric_interval_hull(EX);  # master
@time SX2 = LazySets.Approximations.symmetric_interval_hull2(EX);  # this branch
@test isequivalent(SX, SX2)
println("Hyperrectangle")
Y = rand(Hyperrectangle, dim=n);
EY = ExponentialMap(M, Y);
@time SY = symmetric_interval_hull(EY);  # master
@time SY2 = LazySets.Approximations._symmetric_interval_hull_krylov(EY);  # this branch
@time SY3 = LazySets.Approximations._symmetric_interval_hull_exp(EY);  # this branch
@test isequivalent(SY, …
```

Faster symmetric_interval_hull for ExponentialMap of singletons and hyperrectangles

---

src/Approximations/overapproximate.jl
src/ConcreteOperations/difference.jl
src/ConcreteOperations/minkowski_sum.jl
src/LazyOperations/Intersection.jl
src/Plotting/mesh.jl
src/Plotting/plot_recipes.jl
src/Utils/comparisons.jl

Closes #2823.
This branch is based on #2822.
I did not turn the `Symbolics` examples into doctests because they use an old syntax. We should fix that once we use the new version in #2825.

#2823 - Change code examples to doctests

---

src/Utils/samples.jl
test/ConcreteOperations/samples.jl

Alternative to #2547 that seems more biased toward the edges. Related to #2536.
The idea is to start from the Chebyshev center and then walk toward random vertices. Crucially, some vertices can be skipped, which has the effect that the samples are not biased toward the center.
TODOs:
---
```julia
julia> using LazySets, Polyhedra, Plots
julia> X = rand(VPolygon);
julia> @time V = sample(X, 1000, sampler=LazySets.PolytopeSampler);
0.000688 seconds (8.01 k allocations: 758.172 KiB)
julia> @time V2 = sample(X, 1000, sampler=LazySets.PolytopeSampler2);  # sampler from this branch
glp_simplex: unable to recover undefined or non-optimal solution
glp_simplex: unable to recover undefined or non-optimal solution
1.107326 seconds (1.30 M allocations: 67.599 MiB)
julia> plot(X)
julia> scatter!([v[1] …
```

Alternative polytope sampler

---

docs/src/lib/interfaces.md
src/Approximations/box_approximation.jl
src/Interfaces/AbstractCentrallySymmetric.jl
src/Interfaces/AbstractHyperrectangle.jl
src/Interfaces/LazySet.jl

Closes #2845.
I added a new function `extrema`, which computes `low` and `high`. For certain set types this is faster than computing them individually.
With that, there are two similar implementations for `ConvexHull`: using `box_approximation` and using `extrema`. I tried both and sometimes the `box_approximation` implementation is orders of magnitude faster, while in other cases it is slightly slower due to additional allocations (I marked those cases below). This is mainly because we do not have efficient methods of `extrema` for certain set combinations yet. I kept both implementations but made the `box_approximation` one the default.
```julia
julia> H1 = rand(Hyperrectangle, dim=1000);
julia> H2 = rand(Hyperrectangle, dim=1000);
julia> C = CH(H1, H2);
julia> M = H1 + H2;
julia> @time …
```

#2845 - More efficient box_approximation of CHull and MSum

---

docs/src/lib/binary_functions.md
src/ConcreteOperations/issubset.jl
test/ConcreteOperations/issubset.jl
test/runtests.jl

Closes #2831.
This PR also adds witness production for the interval-interval inclusion check.
The method checks inclusion in unions of arbitrary sets, as long as they can be converted to `Interval`s. That means it will fail for unions of non-convex sets.

#2831 - Inclusion of interval in union of intervals

---

src/Approximations/overapproximate.jl

The actual change is the `if` condition. I also reordered the methods to first show the `Taylor1` method.

Fix _nonlinear_polynomial for constant polynomials

---

src/Interfaces/LazySet.jl
test/Sets/Polytope.jl

This PR proposes to change the semantics of `copy` to that in `Base` (see #2261).
```julia
help?> copy
copy(x)
Create a shallow copy of x: the outer structure is copied, but not all internal values.
For example, copying an array produces a new array with identically-same elements as the original.
```
The old behavior is readily available with `deepcopy` (no method definition needed).
The implementation is generic but not bulletproof because it relies on a constructor with the arguments being the fields of the struct, in the right order. I would add tests that this works for each type (and define methods where it does not), but first I wanted to ask @mforets if you agree with that new behavior.
Also note that the generic implementation is slower than the old implementation, probably …

Redefine copy(::LazySet)

---

src/Sets/HParallelotope.jl
test/Sets/HParallelotope.jl

See #2772 and #2786.
In fact, I would rather propose that we check for emptiness in the constructor. The fact that we can create an empty parallelotope creates several problems with the default definitions. And I think it is never intended to actually create an empty set this way. I proposed this alternative in #2876.

Fix isempty(::HParallelotope)

---

.github/workflows/ci.yml

I realized that the change in #2900 means that there is no coverage running on `master` anymore. So I suggest to undo the change.

Undo #2900

---

docs/src/lib/sets/Hyperplane.md
docs/src/lib/utils.md
src/Sets/Hyperplane.jl
src/Utils/samples.jl
test/Sets/HalfSpace.jl
test/Sets/Hyperplane.jl

See #2734.
The idea is to take a random point from some distribution. If it is not in the half-space, reflect the point in the hyperplane.
The only tricky question is what to choose as the distribution. I think the user has to help here. I set the default to [0, 1]^n.
See the example for the blue and the (dual) red half-space below. The green points are samples from blue (taken from [0, 1]^2 and all inside). The purple points are samples from red (taken from [0, 1]^2 and then reflected).

Sampling from HalfSpace

---

docs/src/lib/sets/Hyperplane.md
docs/src/lib/sets/Line2D.md
docs/src/lib/utils.md
src/Sets/Hyperplane.jl
src/Sets/Line2D.jl
src/Utils/samples.jl
test/Sets/Hyperplane.jl
test/Sets/Line2D.jl

See #2734.
Similarly as in #2912, the sampling assumes an oracle for a random point. Then it just projects the point onto the hyperplane.

Sampling from Hyperplane/Line2D

---

docs/src/lib/binary_functions.md
src/ConcreteOperations/intersection.jl
test/Sets/Polygon.jl

This also fixes the problem in #2934.
```julia
julia> p = rand(HPolygon; seed=0);
julia> q = rand(VPolygon);
julia> @time intersection(p, q);  # master
0.000727 seconds (3.11 k allocations: 173.297 KiB)
julia> @time intersection(p, q);  # this branch
0.000038 seconds (112 allocations: 7.750 KiB)
```
I also changed the `prune` argument of one method to a keyword argument for consistency, which makes this a _breaking change_.

Faster concrete intersection of mixed polygons

---

Project.toml
test/LazyOperations/Intersection.jl
test/runtests.jl

This test was temporarily deactivated in #2923.
I suggest to include a check based on the version of `GLPK` since at least for now some package(s) in my default Manifest hold(s) the new `GLPK` version with the fix back and hence tests would fail locally.

Bring back fixed test

---

src/LazyOperations/CartesianProduct.jl

Hi, just noticed this typo in the docs:
and thought, *oh this smells like a great first contribution*
Have a nice day

Escape inverse slash in docstring.

---

docs/src/lib/sets/SimpleSparsePolynomialZonotope.md
src/ConcreteOperations/cartesian_product.jl
src/ConcreteOperations/minkowski_sum.jl
src/Sets/SimpleSparsePolynomialZonotope.jl
test/Sets/SimpleSparsePolynomialZonotope.jl

This PR adds the operations on SSPZ described in Niklas presentation. Currently I added those into the same file of SSPZ, but maybe we want to move those in the corresponding files in `concrete_operations`?

operations on simple sparse polynomial zonotopes

---

src/ConcreteOperations/issubset.jl
test/ConcreteOperations/issubset.jl

```julia
using LazySets, Plots
B1 = Hyperrectangle([0.0, 0], [1.0, 1])
B2 = Hyperrectangle([0.5, 1.5], [0.5, 1.5])
B3 = Hyperrectangle([0.0, 1], [0.5, 2])
U = UnionSetArray([B1, B2, B3])
H = Hyperrectangle([0.2, 1], [0.7, 1])
plot(U)
plot!(H)
julia> H ⊆ U
true
```

Inclusion check for box in union of boxes

---

docs/src/lib/binary_functions.md
src/ConcreteOperations/issubset.jl

Closes #3012.
The previous code for hyperrectangles was already general, so this PR mainly renames the variables.

#3012 - Generalize code for inclusion in union

---

src/init.jl

Fixes #3040 
Context: The problem seems to be that `Revise.add_require` dispatches on `Expr` for it's last argument but the `@require ... nothing` statement parses `nothing` as a `Symbol`. Thus, we never hit that dispatch. I'll make a PR to Revise to fix it over there but, for now, this workaround should do and should have no undesired side effects.

Hotfix for Revise/Require bug

---

docs/src/lib/interfaces.md
src/Interfaces/AbstractCentrallySymmetric.jl
src/Interfaces/ConvexSet.jl
src/Interfaces/LazySet.jl

- Redefine `isconvextype` of `ConvexSet` and `AbstractCentrallySymmetric` to `true`. The latter is debatable, but I do not see a use case for non-convex centrally symmetric sets. (This should have been done before when we introduced `ConvexSet`, but fortunately we redefined the function for all convex subtypes, so the answers were still correct.)
- Define `isconvextype` for `LazySet` as `false`.
- Fix some docs of `ConvexSet`.

Fix isconvextype

---

docs/src/lib/interfaces.md
docs/src/lib/sets/Ball2.md
docs/src/lib/sets/Interval.md
src/Approximations/underapproximate.jl
src/ConcreteOperations/difference.jl
src/Interfaces/AbstractPolyhedron_functions.jl
src/Interfaces/AbstractSingleton.jl
src/Interfaces/ConvexSet.jl
src/LazySets.jl
src/Sets/Ball2.jl
src/Sets/Interval.jl
test/Approximations/underapproximate.jl
test/Sets/Ball2.jl
test/Sets/Interval.jl
test/Sets/Polytope.jl
test/Sets/Singleton.jl

The first commit fixes an inconsistency: `chebyshev_center` existed with kwarg `get_radius` and `compute_radius`. I went for the latter because that was used in two places.
```julia
julia> X = rand(VPolygon);
julia> B = underapproximate(X, Ball2);
```

underapproximate with a Ball2

---

docs/src/lib/interfaces.md
src/Interfaces/ConvexSet.jl
src/Interfaces/LazySet.jl

Also extend the docstrings a bit to clarify that the results are not necessarily contained.
There is a really weird (Julia?) bug when removing the method for `ConvexSet`. I tried many different combinations, to no avail. What I ended up with was to keep the methods for `ConvexSet` but also to define undocumented methods for `LazySet`. So the functionality is there, just not directly visible in the documentation (I added a line about this in the online documentation).

Generalize low, high, extrema to LazySet

---

docs/src/lib/sets/Line2D.md
src/Sets/Line2D.jl

Main changes:
- catch invalid inputs (two identical points) in the constructor
- use `σ` for `Hyperplane`s
- cheaper witness construction for `isuniversal`
- slightly change `an_element` implementation to be consistent with the `Hyperplane` implementation
- fix `project` for block `[2, 1]` (which swaps dimensions)

Revise Line2D code

---

docs/src/lib/sets/Hyperrectangle.md
src/Sets/Hyperrectangle.jl

There was a bug in `genmat` for sparse vectors. The new implementation is consistent with the implementation for dense vectors.

Revise Hyperrectangle code

---

docs/src/lib/interfaces.md
docs/src/lib/sets/ZeroSet.md
src/Interfaces/AbstractSingleton.jl
src/Sets/ZeroSet.jl
test/Sets/ZeroSet.jl

Code changes:
- Fix: `linear_map` did not preserve the numeric type.
- The `center(X, i)` method was generalized to `AbstractSingleton`.
- `σ` was redundant (identical to the implementation for `AbstractSingleton`).

Revise ZeroSet code

---

docs/src/lib/sets/Zonotope.md
src/Sets/Zonotope.jl

The only code change is that `scale` makes a copy and calls `scale!`.

Revise Zonotope code

---

docs/src/lib/interfaces.md
docs/src/lib/sets/HPolyhedron.md
docs/src/lib/sets/HPolytope.md
src/Approximations/overapproximate.jl
src/Interfaces/AbstractPolyhedron_functions.jl
src/Interfaces/ConvexSet.jl
src/Sets/HPolyhedron.jl
src/Sets/HPolytope.jl
test/Sets/Polyhedron.jl

The first commit adds an `isbounded` method for a list of constraints and generalizes `_isbounded_stiemke` to a list of constraints (hence moved to a different file).
The second commit revises `HPolytope` with  no essential code changes. I added a new note on how `isbounded` behaves in the type documentation because this may be confusing.

Revise HPolytope code and generalize isbounded to list of constraints

---

docs/src/lib/sets/VPolytope.md
src/Sets/VPolytope.jl

Changes:
- Fix `translate!` and `project` for empty polytope
- Fix `tohrep` for empty polytope (created an `EmptySet` of dimension -1)
- Better conversion from `VRep`
- Better `project` in 1D
```julia
julia> P = VPolytope([[-0.15330599660046973, -0.5838096094570292], [-0.7591127909105239, -1.192999658387627], [0.7380486638517654, -1.3390682799566664], [-1.0158204730815894, -0.008656516404044098], [0.6470895258893331, -0.11120778290971557], [-1.27356201159646, 0.2040335091701241], [0.026857226377266084, -1.2352895693477395]]);
julia> Q = polyhedron(P);
julia> @time VPolytope(Q);  # master
0.000008 seconds (3 allocations: 144 bytes)
julia> @time VPolytope(Q);  # this branch
0.000009 seconds (2 allocations: 128 bytes)
julia> @time project(P, [1])  # master
0.000019 seconds (24 allocations: …
```

Revise VPolytope code

---

docs/src/lib/approximations.md
src/Approximations/ballinf_approximation.jl
src/Approximations/box_approximation.jl
src/Approximations/symmetric_interval_hull.jl
test/Approximations/box_approximation.jl

Relevant code changes:
- `symmetric_interval_hull` of an `Interval` now also returns a `Hyperrectangle` (makes the function type stable)
- `box_approximation_helper` was inlined resp. replaced by more efficient code
- `concretize(SymmetricIntervalHull)` does not call `concretize` recursively anymore, which is better
The `Expokit` code was not generalized (I opened an issue instead).

Revise box-/ballinf-approximation and sih code

---

src/Approximations/Approximations.jl
src/Approximations/approximate.jl
src/Approximations/hausdorff_distance.jl
src/Approximations/init_Ipopt.jl
src/Approximations/underapproximate.jl

Main code changes:
- fix `_underapproximate_box` (sometimes swapped low and high ends)
- generalize `underapproximate` with directions to unbounded sets
```julia
julia> clist = constraints_list(rand(BallInf));
julia> pop!(clist);
julia> X = HPolyhedron(clist);
julia> Y = underapproximate(X, BoxDirections(2));
```

Revise some Approximations code

---

docs/src/lib/approximations.md
docs/src/man/iterative_refinement.md
src/Approximations/Approximations.jl
src/Approximations/iterative_refinement.jl
src/Approximations/overapproximate.jl

Code changes:
- rename `_approximate` into `overapproximate_hausdorff` (open for other suggestions, but I wanted to remove the `_` and make clear that it is an overapproximation); this function now also returns a polygon immediately because there is no other use case; I also fixed a bug that could occur if the algorithm has not converged yet (could not happen through use of the main public API)
- change `constraint` method into a standard `convert` method

Revise iterative_refinement code

---

docs/src/lib/interfaces.md
docs/src/lib/lazy_operations/Intersection.md
docs/src/lib/sets/EmptySet.md
src/Approximations/overapproximate.jl
src/Interfaces/LazySet.jl
src/Plotting/plot_recipes.jl

The first commit adds a `plot_vlist` function for simplification and later extension.
The second commit changes the default value of SPZ overapproximation to 10 splits per dimension. This uncovered a potential bug (see below). I still kept the changes here because the old code base is also affected (one just does not see it so obviously).
The third commit removes the restriction that epsilon needs to have the same numeric type.

Revise plot_recipes code and overapproximation of SPZ

---

src/ConcreteOperations/issubset.jl
src/LazyOperations/Complement.jl
src/convert.jl

This actually produced warnings in the CI runs (but not locally, at least for me).

Remove unused type parameters

---

docs/src/lib/binary_functions.md
src/ConcreteOperations/convex_hull.jl
src/ConcreteOperations/minkowski_sum.jl

The only code changes are in `function minkowski_sum(P::LazySet, Q::LazySet ...)` (formerly `function minkowski_sum(P::ConvexSet, Q::ConvexSet ...)`):
1. Instead of `isapplicable`, which does not help with lazy operations, and the potentially expensive `isbounded`, I used traits.
2. I added a case in `_convex_hull_2d_preprocess!` and only apply it if the `prune` argument is `true` (because it is also correct to return more vertices and often there are no redundant vertices).

Revise minkowski_sum code and generalize to LazySet

---

docs/src/lib/binary_functions.md
docs/src/lib/interfaces.md
src/ConcreteOperations/convex_hull.jl
src/Interfaces/AbstractPolytope.jl
src/Interfaces/LazySet.jl
src/Sets/SimpleSparsePolynomialZonotope.jl
test/ConcreteOperations/convex_hull.jl

Closes #2755.
The code changes are:
- ~Copy the vertices before calling `convex_hull!`.~
- Also sort the vertices in the 1D case (actually one other method relied on that).
- Unary convex hull of general sets (but currently only works for convex sets and unions). This made the old implementation for `UnionSetArray` redundant (which however returned the vertices instead of a set; I think this was a mistake).
- Outsource the unary convex hull of `SSPZ` to the corresponding file.

Revise convex_hull code and generalize to LazySet

---

docs/src/lib/binary_functions.md
docs/src/lib/lazy_operations/Bloating.md
src/ConcreteOperations/issubset.jl
src/LazyOperations/Bloating.jl

Closes #1856.
The main code changes are:
- `_issubset_in_hyperrectangle` now does not require `interval_hull` anymore (and is also more efficient)
- I inlined the `_default_issubset` function because it was only used by one method.
- I used some approximate equality checks.
- I fixed a crash in `⊆(::LazySet, ::UnionSetArray)`.
The second commit adds `is_polyhedral` for `Bloating` to make an old test pass.

Revise issubset code and generalize to LazySet

---

docs/src/lib/conversion.md
src/Interfaces/AbstractHyperrectangle.jl
src/Interfaces/AbstractZonotope.jl
src/LazyOperations/ConvexHullArray.jl
src/Sets/Interval.jl
src/Sets/VPolygon.jl
src/convert.jl

The first commit adds a method `_constraints_list_zonotope` to resolve a TODO.
The second commit contains the main changes. It mainly removes some implementations that are redundant because of an identical implementation of the supertype.
The remaining commits add kwargs to some `vertices_list` methods to make the above removal work.

Revise convert code and generalize to LazySet

---

docs/src/lib/conversion.md
docs/src/lib/interfaces.md
docs/src/lib/sets/HPolyhedron.md
src/Initialization/init_Polyhedra.jl
src/Sets/HPolyhedron.jl

Main code changes:
- I documented the `convert` method from `HRep` rather than the `HPolyhedron(::HRep)` method because that is the standard Julia way to convert.
- I documented and exported `triangulate`.

Revise HPolyhedron code

---

src/LazyOperations/UnionSetArray.jl

Code change: Make `dim` for empty arrays consistent with other array-set types (return `0` if the array is empty).

Revise UnionSetArray code and generalize to LazySet

---

docs/src/lib/lazy_operations/CartesianProduct.md
src/LazyOperations/CartesianProduct.jl

The removal of the type parameter in `vertices_list` is to fix the docs entry.

Revise CartesianProduct code

---

docs/src/lib/lazy_operations/ResetMap.md
src/LazyOperations/ResetMap.jl

I merged two docstrings because of problems with `Documenter` filtering the correct methods.

Revise ResetMap code

---

src/LazyOperations/SymmetricIntervalHull.jl

The only code change is to use `extrema`, which is generally more efficient than a support-vector query.

Revise SymmetricIntervalHull code and generalize to LazySet

---

src/Approximations/overapproximate_zonotope.jl
test/Approximations/overapproximate.jl

This is an alternative to the method added in #2326 which does not require a parameter for directions.

Overapproximation for intersection of zonotope and hyperplane

---

src/LazyOperations/CartesianProduct.jl
src/LazyOperations/CartesianProductArray.jl

Closes #1758.
The first commit is just formatting (4 spaces instead of 3).
```julia
julia> d = SingleEntryVector(10, 100, 1.0)
julia> X = CartesianProductArray([rand(Ball2, dim=10) for _ in 1:10])
julia> Y = CartesianProduct(rand(Ball2, dim=50), rand(Ball2, dim=50))
julia> @time σ(d, X)
0.000013 seconds (21 allocations: 3.688 KiB)  # master
0.000010 seconds (2 allocations: 1.016 KiB)  # this branch
julia> @time ρ(d, X)
0.000018 seconds (11 allocations: 1.422 KiB)  # master
0.000010 seconds (1 allocation: 16 bytes)  # this branch
julia> @time σ(d, Y)
0.000013 seconds (5 allocations: 2.812 KiB)  # master
0.000013 seconds (2 allocations: 1.359 KiB)  # this branch
julia> @time ρ(d, Y)
0.000011 seconds (3 allocations: 1008 bytes)  # master
0.000005 seconds (1 allocation: 16 bytes)  # this …
```

#1758 - faster support function/vector for CartesianProduct/CartesianProductArray

---

docs/src/lib/interfaces.md
src/Interfaces/AbstractZonotope.jl
test/Sets/Zonotope.jl

I tried several examples and sometimes this approximation is really not good. But other times it can be useful.
```julia
julia> Z = rand(Zonotope, num_generators=10); Z.generators
2×10 Matrix{Float64}:
-1.97436   -0.00678346  -1.04514   0.527674  0.949779   0.537129  -1.14433   -0.0677212  1.03545  -1.46856
0.915773   0.459995     0.773422  1.39259   0.763097  -0.796472  -0.223115  -0.606334   0.55431   0.510208
julia> Z1 = reduce_order(Z, 2, LazySets.GIR05());
julia> Z2 = reduce_order(Z, 2, LazySets.COMB03());
julia> Z3 = reduce_order(Z, 2, LazySets.ASB10());  # new method
julia> plot(Z1, lab="GIR05", leg=:outerleft)
julia> plot!(Z2, lab="COMB03")
julia> plot!(Z3, lab="ASB10")
julia> plot!(Z, lab="original")
```

Add order-reduction method with parallelotope

---

src/Approximations/overapproximate.jl
src/Approximations/overapproximate_zonotope.jl
src/Interfaces/LazySet.jl
src/LazyOperations/Intersection.jl
src/Plotting/mesh.jl
src/Sets/BallInf.jl
src/Sets/HPolygon.jl
src/Sets/HPolygonOpt.jl
src/Sets/HPolyhedron.jl
src/Sets/HPolytope.jl
src/Sets/Hyperrectangle.jl
src/Sets/Universe.jl
src/Sets/VPolytope.jl
src/Utils/matrix_exponential.jl
src/Utils/samples.jl
src/convert.jl

Closes #2080.
The remaining documentation only loaded inside `@requires` blocks uses package-specific types or extends a function that is only imported from the external package, so they cannot be moved.

#2080 - Pull out documentation from requires blocks

---

src/ConcreteOperations/minkowski_sum.jl

This fixes two issues in `_minkowski_sum_hrep`:
1. EliminationAlgorithm results in an UndefVarError without the Polyhedra quantifier.
2. `algorithm` is a value, not a type. Hence `algorithm <: EliminationAlgorithm` results in a TypeError.

Fix check for elimination algorithm type in _minkowski_sum_hrep

---

src/LazyOperations/Intersection.jl
test/LazyOperations/Intersection.jl

Closes #1348.
This also improves https://github.com/JuliaReach/LazySets.jl/issues/1144#issuecomment-1341598035, but it is a workaround rather than a complete solution to #1144.

#1348 - Improved bound for line search

---

src/Approximations/overapproximate.jl

Fixes wrong name in overapproximate for HPolyhedron, resulting in an UndefVarError.

Fix variable naming error in overapproximate to HPolyhedron

---

src/Approximations/overapproximate.jl
test/Approximations/overapproximate.jl

In addition to #3228, this adds a test and makes the names `dir`/`dirs` consistent (`dirs` everywhere).

Fix undefined variable and make names dir/dirs consistent

---

src/Sets/HPolyhedron.jl
test/Sets/Polyhedron.jl

```julia
julia> P = HPolyhedron([HalfSpace([0, -1.0], -1.0)]);
julia> x = σ([1.0, 0], P)  # the result is not a feasible solution because y should be >= 1
2-element Vector{Float64}:
Inf
0.0
```
The ray from the LP solver cannot simply be translated into a feasible solution (ignoring `Inf` entries). I am not 100% sure the new version does either (the new version takes a feasible point and replaces all directions of the ray by `±Inf`), but at least it improves the situation.
I also outsourced the code so it is easier to reuse the code.

Fix support vector of unbounded HPolyhedron

---

src/Interfaces/AbstractHPolygon.jl
src/Sets/HPolygon.jl
src/Sets/HPolygonOpt.jl
test/Sets/Polygon.jl

Closes #2426.
I think the problem was that our implementation of `<=` is not antisymmetric, so for very similar directions, the index was not unique. Now the method returns the smallest possible index in such cases.

#2426 - Fix binary search in addconstraint! for polygons

---

src/Sets/HParallelotope.jl

Closes #3203.
There is a small chance that the result is unbounded (this was also possible before).
```julia
julia> D = [1. 1; 1 1];
julia> offset = [1., 1, -1, -1];
julia> Q = HParallelotope(D, offset);
julia> P = HPolyhedron(vcat(Q.directions, -Q.directions), Q.offset);  # convert to polyhedron
julia> isbounded(P)
false
```

#3203 - Make rand of HParallelotope return a nonempty set

---

docs/src/lib/sets/HParallelotope.md
src/Sets/HParallelotope.jl
src/convert.jl
test/Sets/HParallelotope.jl

Closes #2786.
This PR adds a consistency check to the `HParallelotope` constructor. Thus we accept that `vertices_list` and `isempty` return wrong results for inconsistent sets.

#2786 - Add consistency check to HParallelotope constructor and use cheap isempty method

---

src/Sets/LineSegment.jl

This is slightly more efficient because it does not allocate a `Vector`.

Let generators of LineSegment return an iterator

---

src/Approximations/Approximations.jl
src/Approximations/init.jl
src/Approximations/init_Expokit.jl
src/Approximations/symmetric_interval_hull.jl
test/LazyOperations/ExponentialMap.jl

#3117 - Generalize exponential backend in symmetric_interval_hull methods

---

src/Interfaces/LazySet.jl
test/Sets/Polytope.jl

With this new option we can easily add a 3D plot recipe with `Plots` (#35):
```julia
using LazySets, Plots
import MiniQhull
B = BallInf(zeros(3), 1.0)
V, C = LazySets.delaunay_vlist_connectivity(B; compute_triangles_3d=true)
C = Matrix{Int}(C .- 1)  # -1 for zero indexing; convert to Int64 on 64-bit systems
x = [v[1] for v in V]
y = [v[2] for v in V]
z = [v[3] for v in V]
i = [C[1, j] for j in 1:size(C, 2)]
j = [C[2, j] for j in 1:size(C, 2)]
k = [C[3, j] for j in 1:size(C, 2)]
plot(x, y, z, seriestype=:mesh3d; connections=(i, j, k))
```

Add option to get 2D Delaunay triangulation for 3D sets

---

docs/src/lib/interfaces.md
src/Interfaces/LazySet.jl
src/LazySets.jl
src/Utils/helper_functions.jl
test/Interfaces/interfaces.jl
test/Sets/EmptySet.jl
test/Utils/check_method_implementation.jl

Closes #3194.
Once we have an implementation, we can easily add it again. But for now this just breaks some assumptions.

#3194 - Remove AbstractStar interface

---

docs/src/lib/interfaces.md
docs/src/lib/sets/DensePolynomialZonotope.md
docs/src/lib/sets/SimpleSparsePolynomialZonotope.md
docs/src/lib/sets/SparsePolynomialZonotope.md
src/Approximations/overapproximate_zonotope.jl
src/Interfaces/AbstractPolynomialZonotope.jl
src/Sets/DensePolynomialZonotope.jl
src/Sets/SimpleSparsePolynomialZonotope.jl
src/Sets/SparsePolynomialZonotope.jl
src/Utils/helper_functions.jl
test/Interfaces/interfaces.jl
test/Sets/DensePolynomialZonotope.jl
test/Sets/SimpleSparsePolynomialZonotope.jl

Closes #230.
- The first commit shifts some code from the three implementations to the interface and adds some simple methods for `DensePolynomialZonotope`.
- The second commit removes some arguments to a method that made the method confusing (and type unstable).
- The third commit fixes an error in the docstring of `DensePolynomialZonotope`.
- The fourth commit adds a method for `overapproximate` of a `DensePolynomialZonotope` with a `Zonotope`.
EDIT: I implemented a sampler for polynomial zonotopes (currently in a branch that depends on some changes here). Below is the sampling of the set in the paper, and in blue you see the zonotope approximation from this branch.

#230 - Overapproximate DensePolynomialZonotope with Zonotope

---

src/Sets/Tetrahedron.jl

Closes https://github.com/JuliaReach/LazySets.jl/issues/3259

Membership check for Tetrahedron

---

src/Sets/VPolygon.jl

```julia
julia> V = rand(VPolygon, num_vertices=1000); d = rand(2);
julia> @time LazySets._brute_force_support_vector_old(d, V.vertices)
0.000077 seconds (847 allocations: 66.109 KiB)
433
julia> @time LazySets._brute_force_support_vector_new(d, V.vertices)
0.000045 seconds (1 allocation: 16 bytes)
433
```

Faster brute-force search in support-vector computation of VPolygon

---

src/Sets/Tetrahedron.jl
test/Sets/Tetrahedron.jl

Closes https://github.com/JuliaReach/LazySets.jl/issues/3303

Generalize check if point is in hyperplane

---

docs/src/lib/sets/VPolytope.md
src/Sets/VPolytope.jl

See #600.
There is essentially no difference, but the generated code is a bit shorter.
```julia
julia> L = rand(VPolytope, dim=50, num_vertices=100); d = rand(50);
julia> @time ρ_old(d, V)
0.000015 seconds (1 allocation: 16 bytes)
15.335757954706304
julia> @time ρ_new(d, V)
0.000021 seconds (1 allocation: 16 bytes)
15.335757954706304
```

#600 - Specialized support function for VPolytope

---

docs/src/lib/binary_functions.md
src/ConcreteOperations/minkowski_difference.jl
test/ConcreteOperations/minkowski_difference.jl
test/runtests.jl

#1721 - Concrete minkowski difference for hyperrectangular sets

---

docs/src/lib/sets/Ball1.md
docs/src/lib/sets/Ballp.md
src/Sets/Ball1.jl
src/Sets/Ball2.jl
src/Sets/Ballp.jl

See #600.
The default implementation needs to allocate the support vector, which can be avoided.
```julia
julia> B1 = rand(Ball1, dim=100); d = rand(100);
julia> @time ρ_old(d, B1)
0.000010 seconds (2 allocations: 912 bytes)
8.280132936590725
julia> @time ρ_new(d, B1)
0.000013 seconds (1 allocation: 16 bytes)
8.280132936590725
###
julia> Bp = rand(Ballp, dim=100); d = rand(100);
julia> @time ρ_old(d, Bp)
0.000023 seconds (3 allocations: 1.766 KiB)
11.071392754318621
julia> @time ρ_new(d, Bp)
0.000016 seconds (1 allocation: 16 bytes)
11.071392754318621
```

#600 - Specialized support function for Ball1 and Ballp

---

docs/src/lib/sets/LineSegment.md
src/Sets/LineSegment.jl

See #600.
The version in `master` uses the default implementation for `AbstractZonotope`, which constructs the generator matrix.
```julia
julia> L = rand(LineSegment); d = rand(2);
julia> @time ρ_old(d, L)
0.000012 seconds (7 allocations: 496 bytes)
-0.5400307176763027
julia> @time ρ_new(d, L)
0.000009 seconds (1 allocation: 16 bytes)
-0.5400307176763026
```

#600 - Specialized support function for LineSegment

---

docs/src/lib/lazy_operations/ExponentialMap.md
src/LazyOperations/ExponentialProjectionMap.jl
test/LazyOperations/ExponentialMap.jl

See #600.
The default in `master` uses the fallback for `AbstractAffineMap`, which in this case is already much slower. The new version avoids two matrix multiplications and one evaluation of the matrix exponential.
```julia
julia> @time ρ_master(d, projmap)
0.001999 seconds (1.03 k allocations: 163.281 KiB)
0.3059712619328761
julia> @time ρ_svec(d, projmap)
0.000146 seconds (54 allocations: 8.500 KiB)
0.30597126193287605
julia> @time ρ_new(d, projmap)
0.000127 seconds (29 allocations: 4.266 KiB)
0.30597126193287616
```

#600 - Specialized support function for ExponentialProjectionMap

---

docs/src/lib/conversion.md
src/convert.jl

This fixes the only current (non-external) method invalidations by `using LazySets`.

Define convert methods to HPolygon in eval loop

---

src/LazyOperations/ConvexHullArray.jl
src/LazyOperations/UnionSet.jl
src/LazyOperations/UnionSetArray.jl

Closes #993.
```julia
julia> cup = UnionSet(rand(Ball2), rand(Ball1)); d = rand(2);
julia> @time σ(d, cup; algorithm="support_function");  # master
0.000011 seconds (4 allocations: 256 bytes)
julia> @time σ(d, cup; algorithm="support_function");  # this branch
0.000011 seconds (3 allocations: 176 bytes)
###
julia> cup = UnionSetArray([rand(Ball2) for _ in 1:20]); d = rand(2);
julia> @time σ(d, cup; algorithm="support_vector");  # master
0.000018 seconds (23 allocations: 2.000 KiB)
julia> @time σ(d, cup; algorithm="support_function");  # master
0.000030 seconds (3 allocations: 320 bytes)
julia> @time σ(d, cup; algorithm="support_vector");  # this branch
0.000015 seconds (21 allocations: 1.578 KiB)
julia> @time σ(d, cup; algorithm="support_function");  # this branch
0.000022 seconds (2 …
```

#993 - More efficient support vector for UnionSet and UnionSetArray

---

docs/src/lib/approximations.md
docs/src/lib/interfaces.md
src/Approximations/Approximations.jl
src/Approximations/box_approximation.jl
src/Interfaces/AbstractHyperrectangle.jl
src/Interfaces/LazySet.jl
src/Sets/Ball2.jl
src/Sets/BallInf.jl
src/Sets/Ellipsoid.jl
src/Sets/Hyperrectangle.jl
test/Approximations/box_approximation.jl
test/Sets/Ball2.jl
test/Sets/BallInf.jl
test/Sets/Ellipsoid.jl
test/Sets/Hyperrectangle.jl

Closes #822.
The first two commits add `□` and `○` as set constructors.
The last commit adds `□` as alias for `box_approximation`.

#822 - Unicode operators

---

docs/src/lib/lazy_operations/CartesianProduct.md
docs/src/lib/lazy_operations/Intersection.md
docs/src/lib/lazy_operations/MinkowskiSum.md
src/LazyOperations/CartesianProduct.jl
src/LazyOperations/CartesianProductArray.jl
src/LazyOperations/Intersection.jl
src/LazyOperations/IntersectionArray.jl
src/LazyOperations/MinkowskiSum.jl
src/LazyOperations/MinkowskiSumArray.jl
test/LazyOperations/CartesianProduct.jl
test/LazyOperations/Intersection.jl
test/LazyOperations/MinkowskiSum.jl

The commits extend the convenience constructors for binary lazy operations to the n-ary case (and also move the old methods closer to the constructors).
The second commit also defines `==` for `Intersection` so that it ignores the `IntersectionCache`.
~~This currently does not work because of some peculiarity in `detect_ambiguities` together with `...`. I asked in JuliaLang#49571.~~

Convenience constructors and == for Intersection

---

src/Interfaces/AbstractZonotope.jl

The previous implementation added a dummy dimension for optimization. But here we are only interested in feasibility, and zonotopes are always bounded, so that is redundant.
(This also allows to replace some vectors by single instances. They are internally converted to a vector again, but maybe one day we have a more efficient solver bridge.)
```julia
julia> @time [1.0, 0.2] ∈ Z
0.000699 seconds (1.80 k allocations: 65.766 KiB)
false
julia> @time [1.0, 0.1] ∈ Z
0.000720 seconds (1.80 k allocations: 65.500 KiB)
true
julia> @time [1.0, 0.2] ∈ Z
0.000492 seconds (1.70 k allocations: 59.750 KiB)
false
julia> @time [1.0, 0.1] ∈ Z
0.000697 seconds (1.70 k allocations: 59.500 KiB)
true
```

More efficient membership check in AbstractZonotope

---

src/ConcreteOperations/minkowski_sum.jl

Closes #2778.
This PR removes the workaround for the "unreachable reached" Julia bug (which is still around). The solution is to just use a different dispatch. For that the method `_minkowski_sum_vrep_2d` had to be changed. It tried to be generic in `VT` but was not. The vector `R` was filled with `Vector{N}`s, so unless `VT` was `Vector{N}` (or a supertype like `AbstractVector{N}`, but that would be strange), the code would crash.

#2778 - Simplify code in 2D minkowski_sum

---

src/ConcreteOperations/isdisjoint.jl
test/ConcreteOperations/isdisjoint.jl

[Reference implementation](https://github.com/TUMcps/CORA/blob/e07eb39690eb0152058585aa637b07b94e7560b0/contSet/%40mptPolytope/isIntersecting_.m#L170)
In 2D this check seems less efficient (more allocations, see below) than the default algorithm, so I only use it for 3D and higher.
```julia
julia> Z = rand(Zonotope);
julia> P1 = rand(HPolygon);  # intersects
julia> P2 = rand(HPolygon);  # disjoint
julia> @time isdisjoint(Z, P1)
0.000681 seconds (2.23 k allocations: 78.219 KiB)  # this branch
0.000794 seconds (2.21 k allocations: 77.891 KiB)  # master
false
julia> @time isdisjoint(Z, P2)
0.001043 seconds (2.19 k allocations: 75.156 KiB)  # this branch
0.000629 seconds (2.16 k allocations: 73.641 KiB)  # master
true
julia> Z = rand(Zonotope, dim=3);
julia> P1 = convert(HPolyhedron, …
```

Specialized disjointness check between zonotope and polyhedron

---

src/Utils/lp_solvers.jl
src/init.jl

As part of another project where we also use LP solvers in parallel, I've realized that it is better/more correct to use a task-local solver. The problem is that as tasks are executed, they may [migrate between threads](https://docs.julialang.org/en/v1/manual/multi-threading/#man-task-migration) (in particular when they yield). This means that an LP started in one task on say thread 1, might move to thread 2 following a yield and another task might start on thread 1. In this case, the second task interferes with the model used for the first task, as that was selected from thread 1. Instead, we should use task-local storage (so does the global RNGs, not sure why I read the older version of the RNG code where it was thread-local). With the current thread-local version, it is still correct …

Switch from thread-local to task-local LP solvers

---

src/Plotting/plot_recipes.jl

Follow-up #3355, which made plotting vectors of sets worse.
Also fix plotting of 1D unions and non-polyhedral unions.

Fix plotting

---

docs/src/man/tour.md

Closes #3347.
This is option 2. See #3353 for an alternative.

#3347 - Add link to CITATION.bib to manual

---

docs/src/lib/binary_functions.md
src/ConcreteOperations/intersection.jl
test/LazyOperations/CartesianProduct.jl

intersection of CartesianProduct with polyhedron

---

src/Interfaces/AbstractZonotope.jl
test/Sets/Zonotope.jl

If the output dimension is 1, we may still want to return a `Zonotope` for type stability. But the result can have just one generator.
```julia
julia> @time linear_map(M, Z)  # master
0.000015 seconds (3 allocations: 176 bytes)
Zonotope{Float64, Vector{Float64}, Matrix{Float64}}([0.6565135067379049], [0.06137160508809101 -1.0290195455026827 -0.29127884051790404])
julia> @time linear_map(M, Z)  # this branch
0.000011 seconds (3 allocations: 160 bytes)
Zonotope{Float64, Vector{Float64}, Matrix{Float64}}([0.6565135067379049], [-1.2589267809324955;;])
```

Better linear_map of AbstractZonotope for 1D output

---

src/ConcreteOperations/intersection.jl
src/Interfaces/AbstractHPolygon.jl
src/Sets/HPolygon.jl
src/Sets/HPolygonOpt.jl
src/Sets/Line2D.jl

1. commit: Move constructor docs to struct docs.
2. commit: Remove method `Line2D(::HalfSpace)` because this is part of the public API and it is unclear what that means. It was exclusively used to intersect 2D polygon edges represented as `HalfSpace`s. Instead I added an internal method, which even avoids the conversion to `Line2D`.

Line2D: merge docs, remove method from HalfSpace

---

src/Interfaces/LazySet.jl

The allocations for the box approximation can be avoided.
```julia
julia> Z = rand(Zonotope)
Zonotope{Float64, Vector{Float64}, Matrix{Float64}}([0.10104230899250279, -1.1832339310014397],
[-0.262802732729493 1.238614056354156 0.055185218674978366; -0.2756791598938217 0.4863133839073846 -0.09633869247786447])
julia> @time norm(Z, Inf)  # master
0.000027 seconds (8 allocations: 336 bytes)
2.0415651672805106
julia> @time norm(Z, Inf)  # this branch
0.000017 seconds (3 allocations: 176 bytes)
2.0415651672805106
```

Faster infinity norm

---

src/ConcreteOperations/convex_hull.jl
src/Interfaces/LazySet.jl
src/Sets/HPolytope.jl
test/ConcreteOperations/convex_hull.jl
test/Sets/Polytope.jl

Closes #3414.
Interestingly, `Polyhedra`'s 1D backend is much better. This suggests to use a smarter algorithm for `low`/`high`/`extrema` of `HPolytope`/`HPolyhedron` in 1D. I still suggest that we merge this branch and add these algorithms in a separate issue.
```julia
julia> P = convert(HPolytope, Interval(1, 2))
julia> @time vertices_list(P)  # new behavior in this branch
0.000328 seconds (691 allocations: 41.000 KiB)
2-element Vector{Vector{Float64}}:
[1.0]
[2.0]
julia> @time vertices_list(P; backend=LazySets.default_polyhedra_backend_1d(Float64))  # old behavior
0.000092 seconds (51 allocations: 2.094 KiB)
2-element Vector{SVector{1, Float64}}:
[2.0]
[1.0]
julia> @time vertices_list(P; backend=LazySets.default_polyhedra_backend_nd(Float64))
glp_simplex: unable to recover undefined or …
```

#3414 - fix _two_points_1d! & better vertices_list of 1D HPolytope

---

src/Approximations/underapproximate.jl
src/Initialization/init_SCS.jl
src/Utils/sdp_solvers.jl

The old implementation overwrote a function, which caused printing of a warning (see below).
This PR uses the same approach as for exponential backends (only that currently there is only one solver available).
To simplify things, I removed the numeric argument for `default_sdp_solver`, which was anyway not used.
```julia
WARNING: Method definition default_sdp_solver(Type{var"#s13"} where var"#s13"<:Number) in module LazySets at LazySets/src/Utils/sdp_solvers.jl:2 overwritten at LazySets/src/Initialization/init_SCS.jl:2.
```

Use switching logic from expm for SDP solver

---

src/Sets/SparsePolynomialZonotope.jl

This PR introduces some minor updates to sparse polynomial zonotope docs.

spz docs nitpicks

---

src/Interfaces/AbstractZonotope.jl
test/Sets/Zonotope.jl

The change in #3364 was not correct. Negative generators should be added absolute-wise.

Fix linear_map of AbstractZonotope for 1D output

---

Project.toml
test/Aqua.jl
test/Project.toml
test/runtests.jl

Aqua reports piracies (`<=`, `rand`) and unbound args (the latter of which I do not understand - maybe that is a bug in Aqua) that we should fix.

Run Aqua in tests and fix problems

---

test/runtests.jl

We now check for ambiguities with Aqua.

Remove old (now duplicate) ambiguity tests

---

src/Approximations/overapproximate_zonotope.jl
test/Sets/SparsePolynomialZonotope.jl

This is a breaking change because it renames a keyword argument.

Remove redundant generators in zonotope overapproximations

---

src/LazyOperations/AffineMap.jl
src/LazyOperations/Bloating.jl
src/LazyOperations/CartesianProduct.jl
src/LazyOperations/CartesianProductArray.jl
src/LazyOperations/Complement.jl
src/LazyOperations/ConvexHull.jl
src/LazyOperations/ConvexHullArray.jl
src/LazyOperations/Intersection.jl
src/LazyOperations/IntersectionArray.jl
src/LazyOperations/MinkowskiSum.jl
src/LazyOperations/MinkowskiSumArray.jl
src/LazyOperations/Translation.jl
src/LazyOperations/UnionSet.jl

#1193 - Concrete translation of lazy operations

---

docs/src/man/reach_zonotopes_hybrid.md
src/ConcreteOperations/convex_hull.jl
src/ConcreteOperations/intersection.jl
src/ConcreteOperations/isdisjoint.jl
src/ConcreteOperations/issubset.jl
src/Interfaces/AbstractHyperrectangle.jl
src/Interfaces/AbstractPolyhedron_functions.jl
src/LazyOperations/CartesianProductArray.jl
src/LazyOperations/Intersection.jl
src/Plotting/plot_recipes.jl
src/Sets/HPolyhedron.jl
src/Sets/Hyperplane.jl
src/Sets/VPolygon.jl
src/Sets/VPolytope.jl
test/LazyOperations/UnionSet.jl

Also exclude macro lines from coverage.

Use `eachindex`/`axes` instead of `1:length`/`1:size`

---

src/Sets/Zonotope.jl

This is a follow-up to #3467, which just copy-pasted from ReachabilityAnalysis.
1. The vector type should not be restricted because it is just copied.
2. The method was actually never used because `MMatrix` is not a concrete type and the `<:` was missing.

Generalize reduce_order with StaticArrays matrix

---

src/Approximations/decompositions.jl
test/Approximations/decompose.jl

Outsourced from `ReachabilityAnalysis`.

decompose for fixed target type with overapproximation

---

src/convert.jl
test/Sets/Polyhedron.jl
test/Sets/Polytope.jl

The change in #3466 introduced a problem when there is no identity constructor for the constraints' vectors. This is for instance the case for `SingleEntryVector`. I am not sure we want this constructor, but this case should be caught earlier anyway with the new methods added here.

Add missing `convert` methods for `HPolytope`/`HPolyhedron`

---

src/Approximations/overapproximate_zonotope.jl

Argument: This method just calls `reduce_order`, which also accepts `AbstractZonotope` and `Real`.

Generalize order-reducing overapproximate method

---

test/Sets/SparsePolynomialZonotope.jl

This was causing the following warnings:
```julia
┌ Warning: Assignment to `SSPZ` in soft scope is ambiguous because a global variable by the same name exists: `SSPZ` will be treated as a new local. Disambiguate by using `local SSPZ` to suppress this warning or `global SSPZ` to assign to the existing global variable.
└ @ ~/work/LazySets.jl/LazySets.jl/test/Sets/SparsePolynomialZonotope.jl:109
┌ Warning: Assignment to `SPZ` in soft scope is ambiguous because a global variable by the same name exists: `SPZ` will be treated as a new local. Disambiguate by using `local SPZ` to suppress this warning or `global SPZ` to assign to the existing global variable.
└ @ ~/work/LazySets.jl/LazySets.jl/test/Sets/SparsePolynomialZonotope.jl:110
```

Rename clashing variables in test

---

src/Sets/Polygon.jl
test/Sets/PolygonNC.jl

`isempty` is necessary for plotting.

isempty and convex_hull for Polygon

---

src/ConcreteOperations/convex_hull.jl
src/Sets/Polygon.jl
test/ConcreteOperations/convex_hull.jl
test/Sets/PolygonNC.jl

The first commit is from #3499 because the `convex_hull` method is needed for the test.

Let binary `convex_hull` with `EmptySet` fall back to the unary method

---

Project.toml
src/Interfaces/AbstractHyperrectangle.jl
test/Sets/Hyperrectangle.jl

The build error in the documentation is because it takes a while to update to new releases.

Non-uniform split of hyperrectangles

---

src/Interfaces/AbstractPolyhedron_functions.jl
test/Sets/Polyhedron.jl

Embarrassing that the test was expecting the wrong result...
~~The build error is unrelated (https://github.com/JuliaReach/ReachabilityBase.jl/pull/69).~~

Fix projection of polyhedron in unconstrained dimensions

---

Project.toml
docs/src/index.md
docs/src/lib/interfaces/LazySet.md
src/Interfaces/LazySet.jl
src/LazySets.jl
test/runtests.jl

I decided to not re-export the function because it has nothing to do with this library. A user can always get it via `LazySets.basetype`.
The build error in the documentation is because it takes a while to update to new releases.

Outsource `basetype` to ReachabilityBase

---

Project.toml
src/Sets/SimpleSparsePolynomialZonotope.jl
test/Sets/SparsePolynomialZonotope.jl

The build error in the documentation is because it takes a while to update to new releases.

Let `remove_redundant_generators` remove almost-zero columns

---

src/Approximations/init_IntervalConstraintProgramming.jl
src/Approximations/overapproximate_zonotope.jl
test/Approximations/overapproximate.jl

EDIT: ~~I outsourced the ICP-related code to #3482.~~ This was merged to `master` and rebased.

Zonotope overapproximation of intersection between zonotope and axis-aligned half-space based on ICP

---

docs/src/lib/sets/Interval.md
src/Sets/Interval.jl

The helper function `_radius` was actually just `radius`.

Add `radius` for `Interval`

---

docs/make.jl

Some of the builds are marked in yellow because there was a GitHub outage. But a second run has finished if you click on them.

Move API in docs

---

test/runtests.jl

This is needed to run `LocalCoverage`.

Allow passing `nothing` argument to tests

---

test/runtests.jl

In #3522 I proposed to pass `nothing`, but it turns out the correct way is to pass `""`.

Allow passing empty string to tests

---

docs/src/lib/API.md
docs/src/lib/concrete_binary_operations/difference.md
src/API/API.jl
src/API/Binary/exact_sum.jl
src/ConcreteOperations/difference.jl
src/LazySets.jl
src/Sets/Interval/difference.jl
test/Sets/SparsePolynomialZonotope.jl

I find it inconsistent that `⊞` and `\` are concrete while all other symbols use the lazy operations.
Furthermore, `\` is not a real alias for `difference` because you cannot pass additional (e.g., keyword) arguments to the function.

Remove symbol aliases of concrete operations

---

src/Interfaces/LazySet.jl

The wrapper type `VectorIterator` is redundant because an `AbstractVector` already exposes all relevant functions. I will also remove it from `ReachabilityBase`.

Remove redundant `VectorIterator`

---

src/Sets/HPolyhedron/convert.jl
src/Sets/HPolytope/convert.jl
test/Sets/Polyhedron.jl

Now the methods for `HPolyhedron` and `HPolytope` are (correctly) identical (up to the set type) and should be shared.

Fix `convert` of `HPolyhedron` from `Polyhedra.HRep` 

---

src/Interfaces/AbstractPolytope.jl
src/Sets/HPolytope/HPolytopeModule.jl
src/Sets/HPolytope/vertices_list.jl
src/Sets/VPolytope/VPolytopeModule.jl
src/Sets/VPolytope/minkowski_sum.jl

These `_vertices_list` methods were added in #1495. The purpose was to selectively pass the `backend` argument, to be ignored by some subtypes of `AbstractPolytope`. Now this method is only available for `VPolytope`; hence, one can directly call `vertices_list` and these helper methods are redundant.

Remove redundant `_vertices_list` methods

---

src/Initialization/init_StaticArraysCore.jl
src/Sets/VPolygon/VPolygon.jl
src/Sets/VPolygon/VPolygonModule.jl
src/Utils/helper_functions.jl
test/Sets/Polygon.jl

#3631 - Support `VPolygon` constructor from `SMatrix`

---

src/Sets/LineSegment/init_LazySets.jl
src/Sets/LineSegment/intersection.jl
test/Sets/LineSegment.jl

Closes #3629.
The old code from #2138 was not correct. This PR adds a simple but non-optimized fix in the same spirit.
This works now:
```julia
LS1 = LineSegment(Float32[-34.67, -46.06], Float32[-13.03, -49.77]);
LS2 = LineSegment(Float32[-22.473152, -48.13686], Float32[-19.031397, -48.730015]);
intersection(LS1, LS2)
```

#3629 -  Fix `intersection` of `LineSegments`

---

src/Approximations/box_approximation.jl
test/Sets/Line.jl

```julia
julia> X = Line([0.0, 1.0], [-1.0, 1.0]);
julia> box_approximation(X)  # master
Hyperrectangle{Float64, Vector{Float64}, Vector{Float64}}([NaN, NaN], [Inf, Inf])
julia> box_approximation(X)  # this branch
ERROR: ArgumentError: the box approximation of an unbounded set is undefined
```

Disallow `box_approximation` for unbounded sets

---

src/ConcreteOperations/issubset.jl

The function `_issubset_in_emptyset` calls `isempty`. The removed loop used a shortcut for set types that are never empty, but the compiler figures that out and also skips `isempty`. So this was not really faster. Hence, I suggest to remove the loop to keep the codebase smaller.

Merge metaprogramming loops

---

src/Initialization/init_IntervalArithmetic.jl

#3495 - Avoid repeated creation of `zero_box`/`sym_box`

---

src/Interfaces/AbstractPolyhedron_functions.jl
src/Interfaces/LazySet.jl
src/Sets/VPolygon/VPolygonModule.jl
src/Sets/VPolygon/extrema.jl
src/Sets/VPolygon/high.jl
src/Sets/VPolygon/low.jl
src/Sets/VPolytope/VPolytopeModule.jl
src/Sets/VPolytope/extrema.jl
src/Sets/VPolytope/high.jl
src/Sets/VPolytope/low.jl
test/Sets/Polygon.jl
test/Sets/Polyhedron.jl
test/Sets/Polytope.jl

Closes #3419.
```julia
julia> P = convert(HPolytope, Interval(1, 2));
julia> @time extrema(P)
0.000274 seconds (701 allocations: 42.406 KiB)  # master
0.000007 seconds (3 allocations: 160 bytes)
([1.0], [2.0])
julia> @time extrema(P, 1)
0.000361 seconds (699 allocations: 42.281 KiB)  # master
0.000004 seconds (1 allocation: 32 bytes)
(1.0, 2.0)
julia> @time low(P)
0.000386 seconds (350 allocations: 21.188 KiB)  # master
0.000011 seconds (1 allocation: 64 bytes)
1-element Vector{Float64}:
1.0
julia> @time low(P, 1)
0.000408 seconds (350 allocations: 21.141 KiB)  # master
0.000005 seconds (1 allocation: 16 bytes)
1.0
julia> @time high(P)
0.000322 seconds (350 allocations: 21.188 KiB)  # master
0.000008 seconds (1 allocation: 64 bytes)
1-element Vector{Float64}:
2.0
julia> @time high(P, 1) …
```

#3419 - Fast `low`/`high`/`extrema` for polyhedra

---

src/Approximations/overapproximate.jl
src/LazyOperations/Intersection.jl
src/Plotting/plot_recipes.jl
test/Utils/plot.jl

- Fix two bugs
- Allow plotting of general 1D sets (incl. tests)

Revision of plotting

---

src/Sets/EmptySet/cartesian_product.jl

The implementation in #3664 was not consistent with the behavior of the lazy `CartesianProduct`. Instead, an empty set of the corresponding dimension should be returned (see for instance the example [here](https://en.wikipedia.org/wiki/Cartesian_product#Non-commutativity_and_non-associativity)).

fix `cartesian_product` with `EmptySet`

---

src/ConcreteOperations/convex_hull.jl
src/Sets/EmptySet/convex_hull.jl
test/ConcreteOperations/convex_hull.jl

This fixes an error in #3664 and uses the function from the main module.

`EmptySet`: fix and merge binary `convex_hull`

---

docs/src/lib/interfaces/AbstractCentrallySymmetricPolytope.md
docs/src/lib/sets/Ball1.md
docs/src/lib/sets/HParallelotope.md
docs/src/lib/sets/Interval.md
docs/src/lib/sets/LineSegment.md
docs/src/lib/sets/Singleton.md
docs/src/lib/sets/ZeroSet.md
src/Interfaces/AbstractCentrallySymmetricPolytope.jl
src/Sets/Interval/difference.jl
src/Sets/Interval/radius_hyperrectangle.jl
src/Sets/Interval/rectify.jl

Argument: Methods with docstrings and type parameters are unreliable to link to.

`Interval`: remove type parameter from signatures

---

docs/src/lib/sets/Polygon.md
docs/src/lib/sets/SimpleSparsePolynomialZonotope.md
docs/src/lib/sets/SparsePolynomialZonotope.md
src/ConcreteOperations/linear_combination.jl
test/LazyOperations/ConvexHull.jl
test/Sets/Polygon.jl

If one argument is empty, the result of `linear_combination` is empty as well.

Fix and generalize `linear_combination`

---

src/Sets/EmptySet/distance.jl
test/Sets/EmptySet.jl

The implementation added in #3672 was not correct.
The distance to an empty set is the infimum over the empty set, which is `Inf`.
https://github.com/JuliaReach/LazySets.jl/blob/efdaaf3812d22b6910e898f1f611dd84450a8948/src/API/Binary/distance.jl#L18-L23

Fix `distance` between `EmptySet`s

---

src/Plotting/mesh.jl

New versions of `Makie` detect invalid arguments and throw an error. We do not test the use of `plot3d` and hence this went undetected.

Remove invalid `linewidth` argument from `plot3d`

---

src/Approximations/overapproximate.jl
test/Approximations/overapproximate.jl

Improve documentation

---

docs/src/lib/API.md
docs/src/lib/interfaces/AbstractHyperrectangle.md
docs/src/lib/sets/BallInf.md
docs/src/lib/sets/EmptySet.md
docs/src/lib/sets/HalfSpace.md
docs/src/lib/sets/Hyperplane.md
docs/src/lib/sets/Hyperrectangle.md
docs/src/lib/sets/Line.md
src/API/API.jl
src/API/Binary/distance.jl
src/API/Mixed/distance.jl
src/Interfaces/AbstractHyperrectangle.jl
src/Sets/EmptySet/EmptySetModule.jl
src/Sets/EmptySet/distance.jl
src/Sets/HalfSpace/distance.jl
src/Sets/Hyperplane/distance.jl
src/Sets/Line/distance.jl
test/API.jl
test/Sets/EmptySet.jl

This PR also adds an implementation for `EmptySet`.

Add `distance` between point and set to API

---

test/Sets/EmptySet.jl

This is a revision of the test structure introduced in #3672.
Main changes:
- guard tests that require external packages
- define `isidentical` shorthand
- test additional functions (`constrained_dimensions`, `triangulate`, `linear_map_inverse`)
- identify validation bug in `exponential_map`
- identify validation bug in `≈`
- do not test length of witness vectors (assumed to be done in membership test)
- define common set `E3` only once

Revise tests for `EmptySet`

---

src/Sets/EmptySet/isapprox.jl
test/Sets/EmptySet.jl

The implementation added in [10ed89b](https://github.com/JuliaReach/LazySets.jl/pull/3664/commits/10ed89b192f964381cd1ad2b364bf05509169fc6) is not good. While most binary operations should validate the input sets and throw an error, this should not be the case for `==` and `≈`, which should just return `false`.

Allow `≈` for `EmptySet`s of different dimension

---

src/Interfaces/AbstractPolyhedron_functions.jl
src/Interfaces/LazySet.jl
src/Sets/Universe/UniverseModule.jl
src/Sets/Universe/diameter.jl
src/Sets/Universe/norm.jl
src/Sets/Universe/permute.jl
src/Sets/Universe/project.jl
src/Sets/Universe/radius.jl
src/Sets/Universe/volume.jl
test/Sets/Universe.jl

- let `diameter` for `Universe` throw `ArgumentError`
- let `norm` for `Universe` throw `ArgumentError`
- let `radius` for `Universe` throw `ArgumentError`
- add `volume` for `Universe`
- add input validation to `affine_map`
- change input validation for `linear_map` to assertion and move
- let `permute` for `Universe` validate inputs
- let `project` for `Universe` validate inputs

Fixes for `Universe`

---

docs/src/lib/interfaces/LazySet.md
src/Interfaces/LazySet.jl
test/Sets/Interval.jl

This is a proposal to remove a confusing method, in particular given that we have `scale` now.

Remove scalar `linear_map`

---

src/Sets/Line/distance.jl
test/Sets/Line.jl

Here is a counterexample:
```julia
julia> L = Line([1., 0], [-1., 2]);
julia> x = [0., 0];
julia> distance(x, L; p=1)
1.2000000000000002
julia> plot(L, xlims=[-2, 2], ylims=[-2,2], ratio=1); plot!(Singleton(x))
julia> p = 1.; plot!(Ballp(p, x, distance(x, L; p=p)))
```
The shortest distance is obviously 1 (horizontal connection). The orthogonal connection is only valid in the Euclidean norm.

Fix `distance` of point and `Line`

---

docs/src/lib/API.md
src/API/API.jl
src/API/Binary/convex_hull.jl

As an alternative to this PR, I was wondering whether we should remove the binary `convex_hull` method from the library.
The convex hull is traditionally defined for a single set. Originally, there was no way to express unions of two sets, but now we can express that via a `UnionSet`. So it feels a bit arbitrary that we offer this binary method.
A similar argument goes for the lazy binary operation `ConvexHull`, which could be turned into a unary operation.

Add binary `convex_hull` method to `API` module

---

docs/src/lib/interfaces/ConvexSet.md
src/Interfaces/ConvexSet.jl

The build error on Windows is simply a timeout.

`ConvexSet`: make `σ` a required method

---

src/API/Unary/diameter.jl
src/API/Unary/radius.jl
src/Sets/EmptySet/diameter.jl
src/Sets/EmptySet/norm.jl
src/Sets/EmptySet/radius.jl
test/Sets/EmptySet.jl

I would argue that the old implementations of `norm`/`radius`/`diameter` for `EmptySet` were not correct. Instead of throwing an error, they should return 0 because the smallest enclosing ball has radius/diameter 0.

`EmptySet`: redefine `norm`/`radius`/`diameter`

---

src/ConcreteOperations/exact_sum.jl
src/Interfaces/AbstractPolynomialZonotope.jl
src/Interfaces/LazySet.jl

This function is used in one place to prevent bugs later when adding other parametric set types.
The function is not exported.

Add `isparametrictype` trait

---

src/ConcreteOperations/minkowski_sum.jl
src/Sets/VPolygon/minkowski_sum.jl
test/Sets/Polygon.jl

Fix #3836 
There ought to be a solution where it is not necessary to take the convex hull after, but for now, this is an easy fix. The convex hull is right now (without these changes) computed implicitly by constructing a `VPolygon` in Sets/VPolygon/minkowski_sum.jl.

Fix  `_minkowski_sum_vrep_2d`

---

src/Approximations/box_approximation.jl
test/Approximations/box_approximation.jl

#3844 - Make `box_approximation` of polyhedral `Intersection`s precise and work

---

src/API/Unary/area.jl
src/Interfaces/AbstractHyperrectangle.jl
src/Interfaces/LazySet.jl
src/Sets/Ball2/area.jl
src/Sets/BallInf/area.jl
src/Sets/EmptySet/area.jl
test/ConcreteOperations/area.jl
test/Sets/Ball2.jl
test/Sets/BallInf.jl
test/Sets/EmptySet.jl
test/Sets/Hyperrectangle.jl

Closes #3814.
Since `surface` was removed in #3816, we agreed to let `area` also work for 3D sets (interpreted as the *surface area*). In higher dimensions, the definition is far less clear and probably not interesting, so for now the usage is restricted to 2D and 3D arguments.
This PR also implements `area` for the following 3D sets:
- `AbstractHyperrectangle`
- `Ball2`
- `BallInf`
- `EmptySet`
The only missing case is the general 3D polytope (`LazySet` method → #3853).

#3814 - Allow `area` for 3D sets and add common cases

---

src/Interfaces/LazySet.jl

Argument: The helper functions are not used anywhere else and consist of only a single function call.

Inline one-line helper functions

---

docs/make.jl
docs/src/lib/approximations/overapproximate_norm.md
docs/src/refs.bib
src/Approximations/Approximations.jl
src/Approximations/overapproximate_norm.jl
test/Approximations/box_approximation.jl
test/Approximations/overapproximate_norm.jl
test/runtests.jl

I added a function to efficiently compute an upper bound over the l1 norm of a zonotope

Add overapproximation of the l1 norm of a zonotope

---

docs/src/lib/matrixsets/MatrixZonotope.md
src/Approximations/Approximations.jl
src/Approximations/overapproximate_norm.jl
src/LazySets.jl
src/MatrixSets/MatrixZonotope.jl
src/MatrixSets/MatrixZonotopeModule.jl
src/MatrixSets/center.jl
src/MatrixSets/norm.jl
test/Approximations/overapproximate_norm.jl
test/MatrixSets/MatrixZonotope.jl

The function `_rowwise_zonotope_norm`  encapsulates the shared code between `norm` and `overapproximate_norm`. Passing as an argument the transpose of the matrix zonotope returns the $$\ell_1$$ norm since this is just the maximum column sum.
I moved the `MatrixZonotopeModule`  in the  `LazySets.jl` file  to be located before the `Approximation` module

Add `norm` and `overapproximate_norm` for matrix zonotope

---

src/Approximations/overapproximate.jl
src/Approximations/overapproximate_zonotope.jl

The old implementation `convert`ed to `SimpleSparsePolynomialZonotope`, but that created new parameters for each independent generator. With splitting in the parameter domain, this could quickly explode. The new implementation simply avoids this conversion (by computing the Minkowski sum directly).

Faster `overapproximate` of `SparsePolynomialZonotope` with `UnionSetArray{<:Zonotope}`

---

docs/src/lib/API.md
docs/src/lib/approximations/box_approximation.md
docs/src/lib/lazy_operations/ConvexHull.md
docs/src/lib/lazy_operations/Intersection.md
docs/src/lib/lazy_operations/MinkowskiSum.md
docs/src/lib/lazy_operations/SymmetricIntervalHull.md
docs/src/lib/lazy_operations/Translation.md
docs/src/lib/lazy_operations/UnionSet.md
docs/src/lib/sets/HalfSpace.md
docs/src/man/tour.md
src/API/Binary/isdisjoint.jl
src/API/Binary/minkowski_difference.jl
src/API/Mixed/support_function.jl
src/API/Mixed/support_vector.jl
src/Approximations/box_approximation.jl
src/Approximations/symmetric_interval_hull.jl
src/LazyOperations/ConvexHull.jl
src/LazyOperations/ConvexHullArray.jl
src/LazyOperations/Intersection.jl
src/LazyOperations/IntersectionArray.jl
src/LazyOperations/MinkowskiSum.jl
src/LazyOperations/MinkowskiSumArray.jl
src/LazyOperations/SymmetricIntervalHull.jl
src/LazyOperations/Translation.jl
src/LazyOperations/UnionSet.jl
src/Sets/HalfSpace/HalfSpace.jl
src/Sets/HalfSpace/HalfSpaceModule.jl

As per [Julia convention](https://docs.julialang.org/en/v1/manual/documentation/#Global-Variables), aliases should not be documented. The documentation system automatically shows the full docstring of the main function.

Remove documentation for aliases

---

.github/workflows/TagBot.yml

TagBot cannot trigger the creation of tagged documentation because it needs a key for that. This fix is documented [here](https://documenter.juliadocs.org/stable/man/hosting/#GitHub-Actions).

Fix creation of tagged docs versions

---

docs/src/refs.bib
src/Approximations/init_IntervalMatrices.jl
src/Approximations/overapproximate.jl
test/Approximations/overapproximate.jl

In this PR I add:
- `overapproximation`  for a matrix zonotope multiplication based on [eq 4.10](https://mediatum.ub.tum.de/doc/1287218/1287218.pdf)
- `overapproximation` method to represent a matrix zonotope as an interval matrix

Add `overapproximation` for matrix zonotope multiplication
